### ISSUE TITLE
cmakeFlags: Document CI Usage Only or Remember

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1100]
Currently, as noticed by a power user in #1098, `cmakeFlags` are a hidden selection of NxN options for examples that can be played-through in the CI.

We should either clearly document that users shall not use them or alternatively, making things way more complex, the `submitAction.sh` should copy not only the `cmakeFlags` to the run folder (for later `createParameterSets`/`configure` calls) but also the last used `-t <number>` test number that was used with `configure` (if applicable).

I would prefer documenting that `cmakeFlags` are only used by the CI since this does not overcomplicate things.

The work-flow for users is:
- create a fresh case from the example file
- reduce the cmakeFlags to a specific single line if you want a test != 0

**Comment by n01r** [comment]
We can keep it that way. I do not object your reasoning. The flags are just a powerful way for power users to do extensive testing but in the end the simple way is better.

**Comment by ax3l** [comment]
I think the following: copying the `cmakeFlags` does not harm in `submitAction.sh` and I would add a PR for that.

Probably we should not "auto-remember" what the last `-t`. It complicates things and both solutions can be argued to be unexpected ("why does it remember -t if I do not select it?" and "why doesn't it select the same case again?")

**Comment by n01r** [comment]
We can add a `LastConfiguration.txt` that just prints the complete `cmake` command. :stuck_out_tongue:    
> I think the following: copying the cmakeFlags does not harm in submitAction.sh and I would add a PR for that.

Copying the `cmakeFlags` would be fine when still the user directive is to not use them.
Of course while doing the tests I would remember which test case I used because I name my folders that way and not much time passes until I maybe need them again, if I want to correct anything.
> Probably we should not "auto-remember" what the last -t. It complicates things and both solutions can be

Yes, we should not auto-remember. You are only going to use the `cmakeFlags`-feature if you are a developer and not without thinking about it, anyway. The last configuration IS preserved anyway because  certain `PARAM_...`s are overwritten anyway. But when one configures it again without specifying a test case `configure -t 0` is executed effectively and based on which example is used, the previous settings are lost.
But as I said: only developers care about this and they know because they aim for a specific test case flag, anyway IF they choose to compile again.

**Comment by ax3l** [comment]
need for in binary-documentation added to #867 

I think we should avoid writing an additional file, because using `-c` will also overwrite some of the options.

this problem will probably be solved automatically with a new short-cut that I want to introduce in the build-workflow. I did not document it in an issue yet but it essentially uses by default an `in-case build/ dir` which of course will store the full `cmake` configs (and allows direct re-compile if a param changes plus other neat features like "submitAction.sh detected your param files are newer than you binaries").

**Comment by steindev** [comment]
Closed w/ #3537.
