### ISSUE TITLE
Second tool for charge conservation

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1105]
Following the discussion in #1102, there seems to be the need for more tools checking the charge conservation in PIConGPU.

Until know, the following ideas were brought up:
 - ( @ax3l ) "I was thinking we should also add a small (additional) script such as we use it for the heating: just a simple 1D plot that shows the np.amax() of the quantity we plot in imshow() over time."
 - ( @psychocoderHPC ) "might be a tool with a error histogram insteat of the 1d plot is also or more helpfull."
 - ( @ax3l ) "An error histogram would be only for one time step and could go as a forth plot in the slice tool (2x2 subplots?) Not sure if needed but interesting."
 - ( @PrometheusPi ) what about using not only the max error but also the means error with sigma error bars over time

**Comment by ax3l** [comment]
the last idea sounds good: we plot the median + 2 sigma over time?

**Comment by ax3l** [comment]
oh wait, does not make so much sense. because: the median should usually even for big errors be zero. if you abs the values, then the value says even less. so the only thing that gives you an indirect hint is then the sigma envelope.

I am actually back to plotting the max(abs) over time, that is a quick indicator.

**Comment by PrometheusPi** [comment]
One could use `mean(abs())` but using `mean()`would be useful as well since a deviation from zero would clearly mark an error.

**Comment by ax3l** [comment]
not necessarily. the problem is that this masks all the critical points (such as border communication errors) and smooths the mean. also, the sigma envelope will not reveal them reliably.

**Comment by PrometheusPi** [comment]
I agree that an error not necessarily causes the mean to be ≠ 0. 
But a mean ≠ 0 clearly shows an error. So one should not rely on mean = 0 for charge conservation.

**Comment by PrometheusPi** [comment]
@ax3l 
You stated "I am actually back to plotting the max(abs) over time, that is a quick indicator."
Could you share this script by opening a pull request?

**Comment by ax3l** [comment]
oh, I am just "back to plotting max" in terms of reasoning :)

**Comment by ax3l** [comment]
> But a mean ≠ 0 clearly shows an error. 

no, because:
- for non-abs, it just shows all values are more or less equal around zero
- for abs, it will still be > 0 due to floating point precision

!= 0 is neither necessary nor sufficient for an error that I described.

It is also no problem to plot both, I am just talking from my experience with charge conserving schemes and checks on that.

**Comment by PrometheusPi** [comment]
what do you think of:
 - plot `np.amax(diff)`over time (dots)
 - plot `np.mean(np.abs(diff))` (dots) with error bars `np.std(diff)`
 - warning to stderr if `np.abs(np.mean(diff)) > np.std(diff)`

**Comment by PrometheusPi** [comment]
Yes, mean(diff)≠0 is of course not the exact statement to check for deviations.

**Comment by ax3l** [comment]
I think the first to points are a good idea for that script, last point is too arbitrary.

**Comment by PrometheusPi** [comment]
Both scripts are merged. I will close this issue.
