### ISSUE TITLE
shebang not used in *.cfg files

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1106]
The `tbg` tools uses `source` to execute the `*.cfg` files.
Thus the shebang is not needed by `tbg`. 

@ComputationalRadiationPhysics/picongpu-maintainers Is there any other good reason to keep the shebang in the `*.cfg` files. If not, I will open a pull request to remove it.

**Comment by ax3l** [comment]
@psychocoderHPC what do you think? As with the `.profile` we were always proud they are valid bash scripts ;)

**Comment by ax3l** [comment]
(@PrometheusPi I assigned @psychocoderHPC as long as it is a question that needs evaluation. In case it becomes a task, feel free to change the label and assign yourself again.)

**Comment by PrometheusPi** [comment]
@ax3l @psychocoderHPC and me discussed this already offline. I just opened the issue to check for the opinion of the other maintainers.

**Comment by ax3l** [comment]
excellent :sparkles: don't forget to write the results of offline discussions when doing so

**Comment by PrometheusPi** [comment]
2nd line, first post:
" Thus the shebang is not needed by tbg. "

**Comment by psychocoderHPC** [comment]
This [link](http://stackoverflow.com/questions/7615430/do-you-need-shebang-in-all-bash-scripts) said that we not need shebang if we use `source` to execute a script.
We should remove all shebangs if the file is not marked with linux rights `x` and is only used by a second tool with `source`

**Comment by PrometheusPi** [comment]
I agree (as discussed offline).

**Comment by ax3l** [comment]
@PrometheusPi As I explain it to every new maintainer, here is a reminder: You should note, who participated in an offline discussion, what were the results and reasoning. otherwise you are closing out the community, you might remember the talk at PHSP14 by Karl Rupp? "Private communication kills the community."

Your description simply does not state a previous discussion and adresses all maintainers about a very, very minor problem. If you discussed that with a second maintainer (and the responsible developer) in person, then state that. It is as simple as that ;)
