### ISSUE TITLE
non-executable files with shebang

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1109]
There are currently two non-executable files in the picongpu repo that start with a shebang other than `*.cfg` and `*.tpl` files:

```
picongpu/src/tools/bin/pic2xdmf.py
``` 
This file is not read/called/etc. by any other file in the repo. Should it be executable?

```
picongpu/src/tools/share/gnuplot/BinEnergyPlot.gnuplot
```
This file is called by `picongpu/src/tools/bin/BinEnergyPlot.sh`. But there it is explicitly executed with `gnuplot -persist` (line 138) so the shebang `#!/usr/bin/gnuplot -persist` seems not necessary.  Do you agree @ax3l ?

**Comment by ax3l** [comment]
yes, would be nice if `pic2xdmf.py` could get an `a+x` (or at least `u+x`).

yes, `src/tools/share/gnuplot/BinEnergyPlot.gnuplot` is a *template* for `src/tools/bin/BinEnergyPlot.sh` and does not need executable rights (since it is read in and executed from evaluation of the replaced string). the shebang is ignored in that case, one could remove it for clarity that it won't work natively, n the other hand it does not harm since it is a comment describing the file format.

**Comment by PrometheusPi** [comment]
@ax3l `src/tools/share/gnuplot/BinEnergyPlot.gnuplot` is still not executable but starts with a shebang.
It is your code. What do you prefer?
 - keep it as is
 - remove shebang (not needed)
 - make it executable

**Comment by ax3l** [comment]
can be removed, the file is just a template for an other script, only used in memory via `echo   "$script" | gnuplot -persist` and has a clear suffix. I'll remove it asap.
