### ISSUE TITLE
Rerunable / Restartable

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#120]
Many batch systems support a flag if a job can be aborted and/or restarted. We may want to use that sometimes.
### List of flags and their meaning

qsub/torque: `Rerunable`, `fault_tolerant`
...

**Comment by BrianMarre** [comment]
@psychocoderHPC is this issue still relevant?

**Comment by PrometheusPi** [comment]
Good point.
With automatic checkpoint via [signals](https://picongpu.readthedocs.io/en/latest/expert/signals.html) enabled and [`--checkpoint.tryRestart`](https://picongpu.readthedocs.io/en/latest/usage/plugins/checkpoint.html#cfg-file) as default, this would already be possible. But I think no (default) `*.cfg` uses this currently 
Should we set this as default? Or should we close this issue since users can do it on their own?

**Comment by psychocoderHPC** [comment]
I will close the issue, we have everything to support rerun and basic fault tolerance.
For crusher I also shipped a not easy to understand example of how you could allocate more nodes as you need for your job to handle broken nodes: https://github.com/ComputationalRadiationPhysics/picongpu/blob/1e50e0c69e1d371763ebcf56903496d8942ebee1/etc/picongpu/crusher-ornl/batch.tpl#L120-L155

> Should we set this as default?

I do not think that this is a good default because it is only working with your configured checkpointing and it could lead to unexpected large IO dumps and could fill up the disk above the disk quota.
