### ISSUE TITLE
compile time error if charge is missing

### ISSUE THREAD

**Issue by heikoburau** [ComputationalRadiationPhysics/picongpu#1208]
If a species doesn't specify a charge, it will cause a compile-time error in:
InitialiserController.hpp (line 129)

```
            ForEach<VectorAllSpecies, LogOmegaP<> > logOmegaP;
            logOmegaP();
```

**Comment by PrometheusPi** [comment]
If fixed please rove line 79 in ` src/picongpu/include/simulation_defines/param/speciesDefinition.param`.

**Comment by ax3l** [comment]
in this issue and #1209 it is to decide if a "forgotten" or omitted mass and charge shall sanely fall back to `0` or if we want to force (as currently) users to express "photons have mass zero" and "charge zero" so they do not accidentally forget to define it and are then confused that their "new and slick electron species" is not creating an electric current.

Fully a usability question.

**Comment by n01r** [comment]
If there is a fallback... should that maybe throw a message in an output file so that a user who might really have forgotten it can easily find the mistake? Otherwise I'd opt for a compile time error for not setting a mass.

**Comment by ax3l** [comment]
I think we leave it to `wontfix` since setting a mass and charge explicitly, also to `0.0`, is actually something we don't want to handle via an implicit fallback.

in the specific case mentioned  above, and if set to 0, the log currently plots `nan` for the "plasma frequency of photons". One could still filter that output during init for particles with mass != 0, but that's a different issue.

**Comment by BrianMarre** [comment]
@steindev could this issue be closed?

**Comment by PrometheusPi** [comment]
Yes, this can be closed.
