### ISSUE TITLE
Refactor Ionization: Particle Creation

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#1357]
With the refactoring of the technical parts that do the low level particle creation in #1353 the ionization module needs a refactoring to use that new API. This overall refactoring of ionization should make it less technical and more physics-focused.

Please do this timely after #1353 was merged.

CCing @Heikman @n01r @psychocoderHPC

**Comment by ax3l** [comment]
@n01r has this been implemented?

**Comment by n01r** [comment]
Actually no, not yet. I remember having offline discussions with @Heikman he treats something slightly different than I do. I have to get back onto this to remember where the difference was.

**Comment by n01r** [comment]
In offline discussions with @psychocoderHPC we agreed on moving the change of the parent ion's attributes to one place in the code to keep the state of the ion always valid between algorithms. 
Currently when a new electron is created the functor `WriteElectronIntoFrame` clones the electron from the ion and changes the ion's momentum. Yet the number of `boundElectrons` is changed in the `<Model>_Impl`. That means that even though nothing touches the ion in between, its state is invalid which can lead to unwanted side-effects.

It is foreseeable that we might want to give additional properties to the new free macro electrons as well as change the residual ion in a model-specific way. E.g.:
- give initial momentum to the electron (*single/ multi-photon ionization*)
- create one electron with higher weighting instead of multiple electrons in one step (maybe *Thomas-Fermi*)
- leave the ion in an excited state (*direct impact ionization*)
...

The naming `WriteElectronIntoFrame` is too narrow then. It should also take a model-specific creation/ attribute assignment functor, then, for instance.

**Comment by n01r** [comment]
I'm closing this issue due to it being resolved for a while now.
