### ISSUE TITLE
Question: ionization Helium vs Nitrogen

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#1469]
For an LWFA simulation with a gas mixture of He and N using BSI ionization scheme, I have seen an interesting, grid like spacial structure in the electron charge density for the electrons from He, which are not observable (or at least much weaker) for electrons from N. Both ion species setups are the same (except for the target electron species).

cc: @n01r, @ax3l, @BeyondEspresso  @Highiander

Have you any explanation for this structure? 
Why are these structure that large (multiple super-cells)? 

(absolute) electron charge density from **He electrons**:
![e_density_lwfaion](https://cloud.githubusercontent.com/assets/5121158/15402369/b146e948-1da8-11e6-8ac4-a82f6528bb77.png)

(absolute) electron charge density from **N electrons**:
![en_density_lwfaion](https://cloud.githubusercontent.com/assets/5121158/15402450/1eb82bd6-1da9-11e6-93da-0587d88c3321.png)

_The x- and y-axis are position and given in cells. The z-axis (color) is the charge density in PIConGPU units. Color interpolation is set to "nearest"._

**Comment by bussmann** [comment]
Random number generator seeding? Rounding error in exponential function? Bad phase space sampling? It could be that the probability to ionize is a function that is badly sampled by the normally distributed random numbers generated.

I was expecting to see something like this once ionization was tested in production.

**Comment by PrometheusPi** [comment]
Whatever causes this effect, it creates "interesting physics":
![e_density_lwfaion_50k](https://cloud.githubusercontent.com/assets/5121158/15411515/62499dfe-1dd5-11e6-876d-4fb5930d0f3c.png)

A cut at `y=1825 cells `, this structure reveals to be "round", thus ruling out effects directly correlated to the Cartesian grid.  
![e_density_lwfaion_45k_xz](https://cloud.githubusercontent.com/assets/5121158/15411731/c3b4cfd6-1dd6-11e6-89d3-977c08618000.png)

(The simulation used a linear polarized laser (Gaussian laser, x-polarized).)

**Comment by PrometheusPi** [comment]
It looks like it might be related to `FieldE_z`. There structure looks similar in contrast to the structure of the total electric field.

`abs(E_z)`:
![ezabs_lwfaion_45k_xz](https://cloud.githubusercontent.com/assets/5121158/15412325/797b3270-1ddb-11e6-836a-d9baacf030cb.png)

`E=sqrt(E_x^2 + E_y^2 + E_z^2)`:
![e_lwfaion_45k_xz](https://cloud.githubusercontent.com/assets/5121158/15412338/8e35ed72-1ddb-11e6-82fa-805c08f5a589.png)

**Comment by psychocoderHPC** [comment]
@bussmann The BSI scheme is not using a random number generator.

**Comment by psychocoderHPC** [comment]
@PrometheusPi  Which version of PIConGPU you are running (master,dev) or #1423?
Could you please upload your branch and give use a link with a diff to the currently used base version (to check your changes).

**Comment by n01r** [comment]
Sorry for the delayed answer!
This is really weird! The step-like structure is clear because as @psychocoderHPC was saying: BSI does not use a random number generator. There are only hard ionization levels. 
I just had a look at the code:   
The `BSI_Impl.hpp` caches the 3-dim field, not only the z-component.
```C++
/* interpolation of E- */
                const fieldSolver::numericalCellType::traits::FieldPosition<FieldE> fieldPosE;
                ValueType_E eField = Field2ParticleInterpolation()
                    (cachedE.shift(localCell).toCursor(), pos, fieldPosE());
```
and in `AlgorithmBSI.hpp`:
```C++
/* ionization condition */
            if (math::abs(eField) / ATOMIC_UNIT_EFIELD >= AU::IONIZATION_EFIELD_HYDROGEN[cs] && chargeState < protonNumber)
            {
                /* set new particle charge state */
                parentIon[boundElectrons_] -= float_X(1.0);
            }
```
the absolute value of the E-field vector is used.

**Comment by n01r** [comment]
@PrometheusPi Could you maybe show me the initialization of these two species?
Since this part had to be hacked to account for different macroparticle numbers, not only weightings, maybe the structure comes from there.
What does the initial atom distribution look like?

**Comment by psychocoderHPC** [comment]
@n01r 
- I checked the ionization modules: Is it correct that the weighting of a particle is not used for any equation?
- Maybe [this comment](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1423/files#r64031848) points to an invalid memory access.

**Comment by n01r** [comment]
- True, the weighting is not used since we do not have energy conservation, yet.   
An "*ionization current*" would be needed which accounts for energy loss in the laser pulse when ionization happens.
- I have never seen the structure before even though I have fully ionized before. Ionization does not happen, though, if the `chargeState` equals `protonNumber`. But yes, I think the access of the ionization energies has probably no correct fallback, yet if `chargeState` equals `protonNumber`!

**Comment by BeyondEspresso** [comment]
@psychocoderHPC The picongpu code for the simulation is now available in this repository
https://github.com/BeyondEspresso/picongpu/tree/topic-generalizeBSI
https://github.com/BeyondEspresso/picongpu/tree/ccaba0c8dba28fabb7229ecf7cc7a5a6d565064d

**Comment by PrometheusPi** [comment]
@psychocoderHPC and @n01r thanks for the fast reply, @BeyondEspresso thanks for uploading the code.

The simulation data can be found on *hypnos* at `/bigdata/hplsim/production/debus_LWFA/runs/LWFA_ionization_20`.
The data analysis of this simulation had to be placed in `/bigdata/hplsim/production/LWFA_ionization_dataAnalysis`.

**Comment by n01r** [comment]
Terribly sorry :bow: for overlooking the possible bad memory access! Thx @psychocoderHPC for spotting it. Pull #1423 has been updated. The ADK model will be fixed in a different pull request.

**Comment by psychocoderHPC** [comment]
IMO this issue is not solved by avoiding the iligal memory access, it was only a read and should not effect the results.

**Comment by n01r** [comment]
I also think so. As I said, I never encountered it before even though I did a lot of runs while fully ionizing the material. My guess is still the initial ion distribution since the structure seems to be quite symmetric.

**Comment by PrometheusPi** [comment]
The `he_particleCounter` is homogeneous in front of the laser.

**Comment by psychocoderHPC** [comment]
@PrometheusPi  What does `he_particleCounter` is homogeneous in front of the laser means? Is the error gone?

**Comment by PrometheusPi** [comment]
@psychocoderHPC No, it means that this weird structure is not coming from the initial `He` distribution. So it is coming definitely from ionization (or from some weighting effect?).

**Comment by PrometheusPi** [comment]
The effect is not coming from the initial `He` weighting. Its distribution is pretty much the same:

![he_hist_lwfaion](https://cloud.githubusercontent.com/assets/5121158/15430472/5f44bc12-1e5a-11e6-8731-352d310f8cf0.png)

**Comment by n01r** [comment]
Hmm ... the resemblance of the electron density and the z-component of the electric field is pretty striking. Is it possible that `math::abs` was instantiated wrongly? Did I forget a specific include?

**Comment by psychocoderHPC** [comment]
I am currently checking our `math::abs`  and found that we use 
  - `abs()` for double -> can't find any declaration in cuda
  - `absf()` for float what is a function for double in cude, we need to use `fabsf()` -> but this should only  slow down our code

**Comment by psychocoderHPC** [comment]
Wrong `abs()` implementation is addressed in #1470.

**Comment by PrometheusPi** [comment]
But if it caused by `abs`, why does it only occure with Helium and not with Nitrogen?

**Comment by PrometheusPi** [comment]
@n01r I am not sure whether `E_z` is caused by the extra `e_He` or if it is the other way round.

**Comment by psychocoderHPC** [comment]
Could you please compare if E_z can have a influence. IMO E_z should be very small compared to the other components

Am 20. Mai 2016 20:23:34 MESZ, schrieb Richard Pausch <notifications@github.com>:
>@n01r I am not sure whether `E_z` is caused by the extra `e_He` or if
>it is the other way round. 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ComputationalRadiationPhysics/picongpu/issues/1469#issuecomment-220682032

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PrometheusPi** [comment]
The amplitude of `E_z` is usually very low compared to the amplitude of the total electric field anywhere in the cut we see further up.

![ez_vs_e_hist_lwfaion](https://cloud.githubusercontent.com/assets/5121158/15438403/dc4f8bb2-1e80-11e6-806a-535f5309e2f4.png)

@psychocoderHPC Thus I think there is no physically relevant influence of the `E_z` field in front of the laser. Most of he `E_z` fields are at 0.1% of the total electric field.

**Comment by ax3l** [comment]
Very pretty, but `E_z` is negligible for the ionization rate in that case. It solely depends on the strong `E_x` which is modulated by the plasma transversally in its "pre-pulse" flank which is *only* decreasing with a Gaussian in intensity.

This effect is often also seen in pre-ionized simulations with LWFA where the under-dense plasma in front of the laser is filamented in the order of the plasma wavelength which can in strong cases (near the depletion limit, for high densities, crazy gradients, etc.) even lead to a [beam break-up](http://physh.ru/pics/1024/nature-cover-bubble.png).

`E_x` BSI levels (thx @n01r) vs. He `e-` (step 40k, x-y):

![ex_modulation_dens](https://cloud.githubusercontent.com/assets/1353258/15476370/e4e2c042-210e-11e6-9e53-f538b4932d55.png)

(greyscale is the Helium free e- density; Blue is the isosurface line for `E_x` for the first level / the valence electron, ionizations in front of that might be due to statistical fluctuations in the E-field.)

The (free/ionized) charge with BSI of a point  `y` in plasma on the y axis depends on the `Max^Ly_i=y of E_x(i)` (the maximum `E_x` *infront* of the laser pulse). If you calculate that, one will still see a modulation transversally. Be aware that the modulation of the laser beam is not straight in propagation direction due to the spatial envelope.

Abs. of Gradient of Intensity (of `E_x`):
![intens_modulation](https://cloud.githubusercontent.com/assets/1353258/15476975/a15accbc-2112-11e6-960e-f5219e896801.png)

The missing symmetry in x direction is coming from the reflection on the top of the box (curls in the yee solver have a preferential direction).

Since the first and second ionization level for He (and N) are very low it makes a lot of sense to start directly with a few-level pre-ionized target (e.g., estimate from Saha with a realistic temperature) to get rid of those initial artifacts.

**Comment by n01r** [comment]
:+1: Beautiful Python speedhack you did there!

**Comment by ax3l** [comment]
My fingers were dancing! :dancer:

**Comment by n01r** [comment]
I saw ^^

**Comment by n01r** [comment]
The Jupyter notebook for analysis:
[2016_05_24_Check_BSI_for_errors.ipynb.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/291378/2016_05_24_Check_BSI_for_errors.ipynb.zip)

**Comment by ax3l** [comment]
@n01r if there are no further questions or problems, feel free to close this issue as a documentation of the current state & its evaluation. of course, you can also link posters of yours in your pub/zenodo database.
