### ISSUE TITLE
RNG implementation allows only Xor methods

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#1476]
The current implementation of the [uniform distributions](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/src/libPMacc/include/random/distributions/uniform/Uniform_float.hpp#L51) allows only `Xor` methods.
The implementation specialization must depend on the method.

The `curand_uniform` for float with the method `MRG32k3a` is implemented in cuda as

``` C++
QUALIFIERS float curand_uniform(curandStateMRG32k3a_t *state)
{
    return ((float)(curand_MRG32k3a(state)*MRG32K3A_NORM));
}
```

**Comment by Flamefire** [comment]
This is not completely right. The current implementation relies on the generator returning a random `uint32_t` value. It is unfortunate, that the `MRG32k3a` has this normalization constant and does not just return a `uint32_t` like many others do. However one can also get that to return an `uint32_t` so everything works with every generator.
The idea behind my implementation was to completely decouple the generation and the distribution methods. Making this change here would revert this.

**Comment by Flamefire** [comment]
This can be closed as invalid. First due to the fact that there is a working implementation for `curandStateMRG32k3a_t` #1487 and 2nd due to the possibility to specialize the distribution by the `RNGMethod` which might be helpful for MRG as that one could directly output a uniform float distribution. But more importantly the specialization can be used for normal distributions, where the "normal-distribution-state" might need to be created.

**Comment by psychocoderHPC** [comment]
issue is outdated, we switched to alpaka RNGs and pmacc RNGs based on alpaka
