### ISSUE TITLE
Initialization externally injected electron bunch

### ISSUE THREAD

**Issue by BifengLei** [ComputationalRadiationPhysics/picongpu#1919]
A expected situation is seen in the picture: an externally injected electron bunch (green square) following  a laser pulse  after some distance, d1.
![image](https://cloud.githubusercontent.com/assets/15086852/23658013/1c29d670-0341-11e7-802c-242fd52124cf.png)

 One of usual ways to do this is as following:
1. define the  initial electron bunch profile (position, momentum, charge distribution ) 
2. specify the initialization time for electron bunch, when it has d1 distance after the laser pulse, then it propagates together with the laser pulse.

Is there a solution to do this in PIConGPU?

**Comment by PrometheusPi** [comment]
In order to initialize an electron bunch you could use the bunch initialization routine written in python: #1914 
A detailed workflow is documented in the ipython notebook.

**Comment by PrometheusPi** [comment]
In order to set up the laser in front of the bunch you either start simulating the laser (which is initialized usually on the y=0 plane) and add the bunch after the laser has propagated into the simulation box or you use a different y-plane to initialize the laser (see #1796 for details).
However the second approach might cause some problems if part of the laser propagate towards the electron bunch. ( @psychocoderHPC what do you thin of this setup? )

**Comment by ax3l** [comment]
Be aware that a non-zero plane laser needs more thoroughly testing still and is rather new #1893
It also won't help much yet since it needs to be started on the 1st GPU right now #1891

So init a laser, propagate, checkpoint and add the beam to the checkpoint is probably the quickest way to proceed and already works in the last stable release `0.2.4` currently in `master`.

**Comment by PrometheusPi** [comment]
@BifengLei I would propose the following approach:
 - cherry-pick the commits in #1914 
 - define and setup your own bunch using the `*.ipynb`(for any questions please post them in #1914 or here)
 - run an initialization simulation as described in the notebook
 - set up your main simulation with a gas/plasma profile way out so that before the moving window starts  no particles are initialized (no particles in the setup)
 - run this (so far particle free) simulation till the laser reaches the front and picongpu will start the moving window and write a checkpoint there.
 - copy the particle and field data from your init initialization simulation to your main simulation checkpoint (as described in the `*.ipynb`) **but** adjust the following two lines [1st](https://github.com/PrometheusPi/picongpu/blob/2be3d896e14900bfc52b720d058a58c3822ab28a/src/tools/share/python/modules4picongpu/bunchInit.py#L270) and [2nd](https://github.com/PrometheusPi/picongpu/blob/2be3d896e14900bfc52b720d058a58c3822ab28a/src/tools/share/python/modules4picongpu/bunchInit.py#L281) to use `+=` instead of `=` in order to avoid overwriting the laser field.
 - restart your main simulation from this checkpoint

**Comment by ax3l** [comment]
> cherry-pick the commits in #1914

if he is working on `master`, which I would recommend, he can just download the `bunchInit.py ` from your PR.

**Comment by PrometheusPi** [comment]
@ax3l That is true. :+1:

**Comment by PrometheusPi** [comment]
@BifengLei The current release and the `dev` branch support, bunch initialization for openPMD with both ADIOS and HDF5 backends. Furthermore, lasers can be initialized from arbitrary planes and directions with our new incident field method. The only issue remaining is the relativistic Poisson solver. But we circumvent this by [generating the bunch](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/lib/python/picongpu/extra/input/createBunch_example.ipynb) field-free, pushing the bunch with the [composite pusher](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/param/species.param#L86-L87), switching from [Free](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/param/species.param#L91-L92) to e.g. [Boris](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/param/species.param#L83) usher after 10k steps thus generating the E and B fields via the field solver.  

I will thus close this issue as solved.
