### ISSUE TITLE
Plugin Data Reader: Slow np.loadtxt

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2482]
Reported first by @codingS3b: some python readers, e.g. for the energy histogram plugin, are slow.

The main reason is their usage of `numpy.loadtxt` which we could replace with another numpy reader or pandas' `read_csv` to speed things up.

**Comment by codingS3b** [comment]
It might not be the case that the `numpy` function is slow, but that results from reading the files are not cached and so every query to `EnergyHistogram(...).get(species, iteration)` needs to open the file again for reading.

In the case for the UI this is especially bad because the user triggers the `get()` function by moving a slider, causing a call to the read function everytime.

**Comment by ax3l** [comment]
I thought so in the first place too, but even plotting single iterations is slow.
I googled it a little, and `numpy.loadtxt` is in general a under-performing function:
- http://akuederle.com/stop-using-numpy-loadtxt
- https://github.com/numpy/numpy/issues/3019
- https://github.com/numpy/numpy/issues/7480
- http://wesmckinney.com/blog/a-new-high-performance-memory-efficient-file-parser-engine-for-pandas/

**Comment by seberg** [comment]
I will note that NumPy is fast since NumPy 1.23, so this proably just doesn't matter anymore.

**Comment by sbastrakov** [comment]
Thank you for the information @seberg , I will close the issue.
