### ISSUE TITLE
ADIOS: Require Post-1.13.0

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#2562]
Due to a large amount of fixed issues in ADIOS <= 1.13.0 regarding transforms and particle data, we will need a newer release of ADIOS.

Full list:

https://github.com/ornladios/ADIOS/issues/170

- reads:
  - https://github.com/ornladios/ADIOS/pull/162
  - https://github.com/ornladios/ADIOS/pull/163
- writes:
  - zlib https://github.com/ornladios/ADIOS/pull/165
  - bzip2, isobar and zfp https://github.com/ornladios/ADIOS/issues/174

Update the ADIOS dependency.

**Comment by ax3l** [comment]
@pnorbert do you already have an idea when the next ADIOS release is planned?

**Comment by pnorbert** [comment]
No, we don't. We kind of trail away from the six month cadence of releases of adios 1.x since we fully focus on developing adios 2.x. Rather, we just make a release when we have enough stuff to do that. However, we can make a new release any time your team needs. What is your timeline?

We also have updates on SZ and new feature ZCHECKER from the same researchers, and a new lossy compression MGARD from Mark Ainsworth, so actually we can make this a 1.14 release. But we have to work on the autotool/cmake builds and on documentation before we make a release. So give us at least a month ;-)

**Comment by ax3l** [comment]
Ok, that's great!

We are just in the planning to release a new major PIConGPU version and would like to have all dependencies in a fixed stable version as a dependency again, that's why I am asking about 1.14 (or a 1.13.1 with just fixes as above). If we depend on a untagged dependency for stable releases we can't describe the state of our software reliably and it makes documentation and user support a mess.

**Comment by pnorbert** [comment]
Understandable. So when do you need to have a new adios release to be available?

**Comment by ax3l** [comment]
A few weeks is fine, if you say a month that will work as well.

**Comment by pnorbert** [comment]
@ax3l Can you try the new package on your system with your app to make sure it builds and runs fine? 
https://users.nccs.gov/~pnorbert/adios-1.13.1.tar.gz
Then we can publish the new release.

**Comment by ax3l** [comment]
cc @n01r

**Comment by n01r** [comment]
Will do!

I'll edit this command and compile my findings.

**Comment by n01r** [comment]
Okay, did the RT and it seems all fine :)
Thanks @ax3l and @pnorbert!

**Comment by pnorbert** [comment]
Thanks for the note, fixed it and now the release package is in 
[https://users.nccs.gov/~pnorbert/adios-1.13.1.tar.gz](https://users.nccs.gov/~pnorbert/adios-1.13.1.tar.gz)
Documentation is in [https://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.13.1.pdf](https://users.nccs.gov/~pnorbert/ADIOS-UsersManual-1.13.1.pdf)

**Comment by ax3l** [comment]
@pnorbert thank you so much, that's super helpful for us!
