### ISSUE TITLE
Crashing simulation on k20

### ISSUE THREAD

**Issue by Banjafar** [ComputationalRadiationPhysics/picongpu#2572]
My simulation is crashing on k20 because of insufficient memory on the nodes. Near the end of the simulation, each process consumes around 30% of the memory with the current number of particles that I'd like to increase it in the future. So, using 4 GPUs per node will crash the simulation! What is the recommended approach in this case? 

For now, I manually decrease GPUs per node in k20.tpl but I feel it's too wasteful.

**Comment by ax3l** [comment]
The queue (node) template in `.tpl` files, such as the `k20.tpl` describe the nodes. The configuration `.cfg` files describe how many devices (gpus) you want to use.

If you are running out of memory you can either reduce resolution (until the results get wrong) or just use more GPUs in your `.cfg` file.

For hypnos, do *not* edit the `k20.tpl` since it is already perfectly tuned for the `k20` queue it describes.

**Comment by ax3l** [comment]
> each process consumes around 30% of the memory

Are you referring to host-memory or device memory (`nvidia-smi`)? Don't mismatch threads and processes in output of `top`.

Hypnos' GPU nodes are designed to have a way larger host-memory pool compared to the device memory. If you are running out of mem on them, it's because the memory pool on the device (gpu) is full, not the host memory.

**Comment by Banjafar** [comment]
nvidia-smi reports around 4400 out of 4700 MB, 30% is from the host memory. (seen in ```top``` or ```ps -aux|grep picongpu```)

**Comment by ax3l** [comment]
> nvidia-smi reports around 4400 out of 4700 MB

That's ok since we do the following for device RAM: we allocate all leftover RAM for the particle heap with [mallocMC](https://github.com/ComputationalRadiationPhysics/mallocMC).

This heap is also the "memory pool" that you are running out of during the simulation around step 32'000+.

Unfurtunately we do not have yet a simple way to query this pool's fill level yet. We have a [resource log plugin](https://picongpu.readthedocs.io/en/latest/usage/plugins/resourceLog.html#usage-plugins-resourcelog) that gives you diagnostics like particles per GPU but you would then have to calculate by hand again how much is still free.

A good project to be added as a new plugin!

Nevertheless, for your current problem: continue to use *all GPUs per node* and take more nodes. This is the only way to get more total device memory.

I forgot to mention above: you can also tweak your simulation a bit with [static load balancing](https://picongpu.readthedocs.io/en/latest/usage/tbg.html#cfg-file-macros) via the `--gridDist ...` parameter in the `.cfg` file, if you know where many particles are to be expected.

**Comment by n01r** [comment]
**offline** with @Banjafar:
So we've checked the number of macroparticles in the whole simulation and there seem to be just 20 million in total. As a very rough estimate, a single k20 GPU can handle about 60 million particles.

The box size is `4096 x 2048` and the box is divided in a spaghetti setup so that one GPU has `128 x 2048` cells. I don't see why the simulation would actually crash from that.
But the `stderr` is empty and one option to find out what's wrong could be the following:

1. Set up periodic boundaries in `x` direction
2. Use a plane wave laser
3. Instead of using `pic-build` to build your example use the longer route
    1. `mkdir -p ~/build`
    2. `cd ~/build`
    3. `pic-configure <path/to/param/set>`
    4. `ccmake .`
        *  go to `PMACC_BLOCKING_KERNEL` and hit the return key to enable the option
        *  activate `ALPAKA_CUDA_SHOW_REGISTER` and `ALPAKA_CUDA_SHOW_CODELINES` the same way
        * hit `t` for the advanced options and go to `CUDA_NVCC_FLAGS`
        * then hit the return key and write `-g;-G` for debug symbols on host and device side
        * hit `c` to configure and `g` to generate
4. Recompile with `make -j install`
5. Reduce the box size to `128 x 2048` and choose just 1 GPU in the `.cfg`
6. Add `--checkpoint.period 20000,<step-before-last-crash>:<step-before-last-crash>` to the `TBG_plugins`
7. Resubmit

The idea is that hopefully, if another crash happens, we get a checkpoint shortly before and then we can run a `cuda-gdb` to see a `backtrace` of where the crash happens.

**Comment by BrianMarre** [comment]
@PrometheusPi is this issue still relevant?

**Comment by PrometheusPi** [comment]
@BrianMarre probably not - if it is still relevant @Banjafar, please reopen it.
