### ISSUE TITLE
Restart script with extended time

### ISSUE THREAD

**Issue by NastasiaM** [ComputationalRadiationPhysics/picongpu#2780]
Hi!
I have questions about the restart script. 
1)Can I start all this thing from the last checkpoint of the simulation (I think I can, but I don't know exactly how)
2)Is it possible to violate a little bit the walltime limit with this thing? For example, I need the simulation to run for ~120 hours in total, and my limit is 100 hours, can I do it 2*60 hours?

Happy Halloween :)

**Comment by ax3l** [comment]
Hi,

1) by default, we restart from the most-progressed checkpoint unless otherwise requested via:

```
--checkpoint.restart.step <N>
```
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/docs/TBG_macros.cfg#L208-L214

2) yes just change the walltime in the `.cfg` file or maybe checkpoint more often and restart several times?

**Comment by NastasiaM** [comment]
Hi,
I tried to start from the last checkpoint and it started from the beginning. Am I doing smth wrong?
Here is .cfg file.
[0004gpus.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/2546134/0004gpus.txt)

**Comment by psychocoderHPC** [comment]
I will close this issue, I assume it is solved.
