### ISSUE TITLE
hidden gpu row with moving window

### ISSUE THREAD

**Issue by hightower8083** [ComputationalRadiationPhysics/picongpu#2843]
Hi all

I've got puzzled with this concept of a _hidden GPU row_ in the moving frame cases. 
Do I understand correctly that moving frame option isn't possible for a single-GPU sims, and if i have for example 2 GPUs, only one would be working in such a case? (at least its what i saw in the tests)

If it is so, it seems kinda handicapping for the cases of small LWFA runs on the recent monster-cards (like V100, which is capable to do a run alone)..

**Comment by ax3l** [comment]
Yes, we use one plane of "devices" in moving window direction in order to efficiently implement it. More details are written [here](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions#moving-window) in our wiki.

From the beginning, we developed with multi-GPU nodes in mind which is why this looks a bit odd. If one really wants to simulate e.g. a small 2D3V sim on today's beefy cards (Titan RTX has even 24 GByte RAM) one could do a little trick to sub-partition a single GPU with [Nvidia's "MPS" tool (CUDA Multi-Process Service)](https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf).

Nevertheless, we should also try to implement this as a natively supported mode (half the one GPU and slide the window over it).

**Comment by hightower8083** [comment]
Thanx @ax3l !  Sorry I didn't see this wiki section, my bad..

I totally agree that in a multi-gpu way, this is probably the most optimal way. On the other hand, when the window shift is sub-cycled (e.g. acts each 10-20 steps), the timing of the plasma injection routines can be kinda negligible. Anyway, I still find it a bit confusing user-wise that when one does a legitimate  2-GPU case with, for example, 3072 cells along `y`, the resulting grid silently gets 1536-cell size..

It's up to you to decide the strategy, but I think that the single-GPU cases are starting to be more and more interesting -- out V100s have 32Gb per card so each can handle efficiently even a moderate 3D case

**Comment by ax3l** [comment]
Yes, I agree that this is a bit confusing.

The question is if one plans the simulation from a "compute/memory" perspective (current description) of from a "selected window domain" perspective ("physical box"). In either way, the current hidden docs in the wiki need to be moved to the `docs/source/usage/` manual section so one can find the details quicker.

**Comment by hightower8083** [comment]
well, probably a simplest pre-patch to improve user-awareness could be some comment about the grid configuration in the output printed at the simulations start..

**Comment by ax3l** [comment]
We have already a little `log<picLog::PHYSCIS>` section in `include/picongpu/simulationControl/MySimulation.hpp` that notifies the user the sliding window is on or off. Can definitely go there as well, do you like to PR this?

https://github.com/ComputationalRadiationPhysics/picongpu/blob/23d90f1e0b7111d5cd27d83e1738a7771b0f9b10/include/picongpu/simulationControl/MySimulation.hpp#L259-L266

**Comment by hightower8083** [comment]
Sure I'll look into this, but only next week -- family New Year vacations =)
