### ISSUE TITLE
Building an Example using Alpaka failed

### ISSUE THREAD

**Issue by hpcresearch-ht** [ComputationalRadiationPhysics/picongpu#3107]
Hi 
I am trying to build example using alpaka and I am getting the following errors in the header files of Alpaka

```
/home/picongpu/thirdParty/alpaka/include/alpaka/core/ConcurrentExecPool.hpp: In destructor ‘alpaka::core::detail::ConcurrentExecPool<TIdx, TConcurrentExec, TPromise, TYield, TMutex, TCondVar, TisYielding>::~ConcurrentExecPool()’:
 /home/picongpu/thirdParty/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:358:19: error: base operand of ‘->’ is not a pointer
currentTaskPackage->setException(std::make_exception_ptr(except));
```

```
/home/picongpu/thirdParty/alpaka/include/alpaka/core/ConcurrentExecPool.hpp: In member function ‘void alpaka::core::detail::ConcurrentExecPool<TIdx, TConcurrentExec, TPromise, TYield, TMutex, TCondVar, TisYielding>::concurrentExecFn()’:
/home/picongpu/thirdParty/alpaka/include/alpaka/core/ConcurrentExecPool.hpp:442:19: error: base operand of ‘->’ is not a pointer
currentTaskPackage->runTask();
```

Thanks in advance

**Comment by sbastrakov** [comment]
Hello @hpcresearch-ht , thanks for your report. Could you provide your OS, compiler, and cmake options used for alpaka. Also, what is the reason you use alpaka from picongpu, and not as a [stand alone](https://github.com/ComputationalRadiationPhysics/alpaka)? Not saying this way should not work, just wondering.

**Comment by sbastrakov** [comment]
Also, does PIConGPU alltogether build for you with the same environment?

**Comment by sbastrakov** [comment]
@hpcresearch-ht from the output you provided it looks like you are using the last release of PIConGPU (or `master` branch, which is the same). It might be that you encountered [this alpaka issue](https://github.com/ComputationalRadiationPhysics/alpaka/issues/838). You can try to fix it manually with the suggested change (put `std::shared_ptr<ITaskPkg>` explicitly as the type instead of `auto`). Or I believe the `dev` branch of PIConGPU has this fix already.

**Comment by hpcresearch-ht** [comment]
Hi @sbastrakov 
The System configurations :  Ubuntu 18.04
RAM : 12GB
Boost : 1.71
Cuda:  10.1
cmake options : Disabled Fibers and Enabled CUDA

Wanted to test the GPU acclearated Applications of PIConGPU have succesfully built cudamemtest and MallocMC but got struck on Alpaka 

Will try the manual fix

Thank You

**Comment by sbastrakov** [comment]
Thanks for details @hpcresearch-ht . Sorry for a stupid question, I am confused if you are trying to build a PIConGPU example (created with `pic-create` and then building with `pic-build`, as described in [our docs](https://picongpu.readthedocs.io/en/0.4.3/usage/basics.html)). Or you are trying to build everything manually and separately, and the issue is with an Alpaka example, something [here]( https://github.com/ComputationalRadiationPhysics/picongpu/tree/master/thirdParty/alpaka/example) ?

**Comment by hpcresearch-ht** [comment]
@sbastrakov  I am not trying to build with pic-build , I am trying to do it manually. Yes the issue is with the examples of Alpaka. I am looking only for the GPU accelerated applications of PIConGPU
Are there other GPU accelerated application in PIConGPU other than those in thirdparty folder

**Comment by sbastrakov** [comment]
@hpcresearch-ht sorry for asking again, I am still not sure if I understand what you mean by applications. Sorry if I am explaining the obvious in the following text.

PIConGPU is a plasma simulation code. It is run for a particular set of physical parameters and using particular numerical schemes, alltogether configured in a setup. Examples of setups for PIConGPU are in `share/picongpu/examples`. Each example is basically a certain physical problem to simulate. The code has to be build separately for each setup. Our workflow of `pic-create` -> `pic-build` -> run described in the docs (linked earlier) helps with that. You can do it all manually, but I believe it is much easier to configure your environment and use our tools. Depending on how you build it, PIConGPU can run on GPUs or CPUs. So this is in case you want a GPU-accelerated plasma simulation run.

Now, Alpaka is a parallel programming library for portable single-source programming for a variety of hardware. PIConGPU is its client and so depends on it and that's why we have it in the repository. However, Alpaka is not dependent on PIConGPU, nor even aware of it. [Here](https://github.com/ComputationalRadiationPhysics/alpaka) is the main Alpaka repository. Alpaka has its own examples, that have nothing to do with plasma physics but are just simple parallel operations. Same as PIConGPU, these can be built to run on both GPUs and CPUs. In case you want only Alpaka examples, I believe it is easier to take Alpaka directly from its repository (or our `thirdParty`, which is just a certain commit of Alpaka) and build examples with CMake.

**Comment by hpcresearch-ht** [comment]
Thanks for the detailed info @sbastrakov

**Comment by sbastrakov** [comment]
@hpcresearch-ht in case you encounter problems or need our help with either PIConGPU or Alpaka please feel free to reopen / open new issues.
