### ISSUE TITLE
printing text lines

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3131]
Since I generate some charge density I wish to check assigned values at the terminal. I was looking for some thing like `println(" .... ");`

` cout<< "\n\nINITIALIZE POSITIONS\n\n" << endl;`
with 
`using namespace std; `
in the header has no effects apart from some warnings. Still pic-build completes fine. However my cout call gives a runtime error

terminate called after throwing an instance of 'std::runtime_error'
`  what():  /home/cristi/src/spack/opt/spack/linux-linuxmint19-westmere/gcc-7.4.0/picongpu-0.4.3-gsy5h4idvpfvsvlf2e2qj6xbaptdvg7h/thirdParty/alpaka/include/alpaka/event/EventCudaRt.hpp(195) 'ret = cudaEventQuery( event.m_spEventImpl->m_CudaEvent)' returned error  : 'cudaErrorLaunchFailure': 'unspecified launch failure'!`

Is there another option to use for printing a line of text?
I attach the density.param file here. 

[density.param.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/3946227/density.param.txt)

**Comment by sbastrakov** [comment]
Your `initPositions()` should be `HDINLINE` since it's called inside a kernel, so on a device side.
In case you compile for GPUs with CUDA (as I believe you do), `std::cout` does not work in kernels. However, `printf` should.

I think debugging might be easier if you compiled for a CPU backend (`pic-build -b omp2b` or perhaps even `pic-build -b serial`) because then `std::cout` should be fine.

**Comment by sbastrakov** [comment]
I believe this is figured out by now, closing the issue.
