### ISSUE TITLE
Absorber and symmetry

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3148]
1) I try to understand what the absorber means namely ABSORBER_CELLS and ABSORBER_STRENGTH. I couldn't find information in the manual, apart from guidance on the usage. My assumption is that absorber makes sense only when a laser or background field is present and enables interaction between this and the matter as declared in density.param. Since in my case matter and interactions are present for the whole simulation domain, a declaration such as: 

    constexpr uint32_t ABSORBER_CELLS[3][2] = {
        {0, 256},  /*x direction [negative,positive]*/
        {0, 256},  /*y direction [negative,positive]*/
        {0, 1280} /*z direction [negative,positive]*/
    };

In the snapshots attached I used TBG_gridSize="384 384 32" and TBG_periodic="--periodic 1 0 1" so there is a mismatch. The simulation domain along y (laser direction) is 384 cells long while the interaction region (absrber cells) is only 256. However, I see that the interaction happens really within the first half of the region. For the second half I see only the laser pulse passing unaffected. 

![Screenshot](https://user-images.githubusercontent.com/7108691/72736518-c2a54b80-3b95-11ea-9d38-68d3a85adcc0.png)

Also, how is the ABSORBER_STRENGTH defined since I always see values like 1e-03? Is it fine to work with:
 
    constexpr float_X ABSORBER_STRENGTH[3][2] = {
        {1.0e-3, 1.0e-3}, /*x direction [negative,positive]*/
        {1.0e-3, 1.0e-3}, /*y direction [negative,positive]*/
        {1.0e-3, 1.0e-3}  /*z direction [negative,positive]*/
    };

though absorber cells may not be defined in both sides for all three directions?

2) I once tried to align the material density with respect to the x-vertical axis. With respect to the image below, I have used negative coordinates for x (upper part) trying to get a circular shape but when I ran with something like TBG_gridSize="N N M" TBG_periodic="--periodic 1 0 1" only the part hashed with red appeared.

![circle](https://user-images.githubusercontent.com/7108691/72738217-02b9fd80-3b99-11ea-87b7-5e7691a20757.png)

Is it necessary to work with a centred target? If yes, how can I do it?

Many thanks

**Comment by sbastrakov** [comment]
About the absorber. The parameters in question are for exponential damping absorber, the only available in version 0.4.3. Please note that the `dev` branch has a more advanced [convolutional PML absorber](https://github.com/ComputationalRadiationPhysics/picongpu/blob/a66ef391069d58bdebe41046664466d2bca1cc8d/include/picongpu/param/fieldSolver.param#L64-L66) which does not require nearly as thick absorbing layer. However, this is, unfortunately, not available in 0.4.3, so the rest of my message concerns the exponential damping absorber.

I believe the `TBG_periodic="--periodic 1 0 1"` is processed first, and so the code will only apply absorber along the Y axis in this example, even if you set non-zero thickness for X or Z. (However, it is still required to specify the parameters for all 6 boundaries to keep the structure intact, as you correctly did).

`ABSORBER_CELLS` defines thickness, in number of cells, of the absorbing layer along each of the 6 boundaries of your simulation domain, the order is given by the comments. Please note that in case it exceeds the domain size, the domain will be extended to fit the absorber. Geometrically, the absorber starts at the outer boundary of the domain and **goes inside the domain**. For your example, 256 cells were requested for the Y positive absorber, and your domain has 384 cells in Y, so it is mostly covered with the absorber. This is probably suboptimal. Generally, it is desirable to have no particles in the absorber area (since their behavior would be not physical in the absorber area). For this one would virtually split the domain into absorber area (near the outer border) and no-absorber area (internal part of the domain) and only put particles in the internal part.

Having `ABSORBER_CELLS[...][...] == 0` at some axis and direction means there is no absorber there, so the corresponding value of `ABSORBER_STRENGTH` is not used, but you still have to specify it to keep the structure intact. The values of `ABSORBER_STRENGTH` define the decay rate inside the absorbing layer. The absorber introduces two kinds of reflections: from the boundary between the absorber and the internal area, and from the outer boundary of the absorber. Increasing the absorber strength will increase the first kind of reflections, and decrease the second, and vice versa. Since one would like to minimize the combined effect of such reflections, there is a tradeoff and the strength value should be not too small and not too large. I don't think there is a good recipe of what value to use, 1.0e-3 is reasonable in our experience. You might try to adjust it in case there are visible reflections.

**Comment by sbastrakov** [comment]
Regarding the second part about symmetry. Could you attach your set of `.param` files which results in this asymmetry? I understand you might have done it in another issue, and sorry for asking again, however, this way makes this issue more consistent and guarantees we look at the most up-to-date version.

**Comment by sbastrakov** [comment]
Just based on your comments about negative `x` I am confused. The PIConGPU global coordinate system is set up so that the domain always starts at (0, 0, 0) and goes to the positive direction, with the size being a product of cell size and number of cells. So in terms of this coordinate system there can  be no negative coordinates. Of course, inside your density, and other setups you can use any coordinate system and in the end transform it to ours.

**Comment by cbontoiu** [comment]
It is clear now. I was confused by one of the earlier replies to my "Periodicity" inquiry saying that "the asymmetry is coming from the non centered target." So I thought that the code can handle negative coordinates but I didn't see how to handle this with the only positive TBG_gridSize="m m n", so I turned my attention to the absorber which allows for the negative sides.

Here is a snapshot of what got. For my the y-axis is horizontal here and the laser comes from the left to the right. 

![e_png_yx_0 5_000000](https://user-images.githubusercontent.com/7108691/72744415-7530da80-3ba5-11ea-9de0-03d312be1dd0.png)

In my density file I had 

 // horizontal axis ..........
    constexpr double Y_O = 1*(tube_out_diam + tubes_gap)*cossin45;      // middle 
    constexpr double Y_A = 0;                                           // upper-left 
    constexpr double Y_B = Y_O + (tube_out_diam + tubes_gap)*cossin45;  // upper-right 
    constexpr double Y_C = Y_O + (tube_out_diam + tubes_gap)*cossin45;  // lower-right 
    constexpr double Y_D = 0;                                           // lower-left 

    // vertical axis ............
    constexpr double X_O = 0;        // middle 
    constexpr double X_A = X_O - 1*(tube_out_diam + tubes_gap)*cossin45;  // upper-left 
    constexpr double X_B = X_O - 1*(tube_out_diam + tubes_gap)*cossin45;  // upper-right 
    constexpr double X_C = X_O + 1*(tube_out_diam + tubes_gap)*cossin45;  // lower-right 
    constexpr double X_D = X_O + 1*(tube_out_diam + tubes_gap)*cossin45;  // lower-left 

and as you can see the upper left and upper right tubes are not rendered which is just expected, but I couldn't be sure without your clarifications. 

Thanks. I don't think the param files are necessary in this case. 

I

**Comment by sbastrakov** [comment]
Sorry for confusing names. The absorber also does not go into negative, we just call the border that's near min value of x / y /z "negative". So this "negative border" absorber starts at 0 and goes towards the positive direction. I believe your middle in X just needs to be in the middle of the domain.

**Comment by cbontoiu** [comment]
I read all I could about the absorber and thanks for the explanation above. Still I don't know what is its meaning and if I should use ``` c++ YeePML< CurrentInterpolation >: standard Yee solver with PML absorber ```. And, in this case how? Do I still need the ``` c++ ABSORBER_CELLS[3][2]```, or maybe something else? I am working with the @develop version.

My worry comes from the fact that a plane wave laser could create a quadrupole pattern as that in the picture attached. 

![index](https://user-images.githubusercontent.com/7108691/73377777-82da1480-42b7-11ea-8a06-1e12b4e2621a.png)

There were 32 absorber cells along each of the 6 cube faces. It seems that the laser field is constrained in the simulation box and resonates?

**Comment by sbastrakov** [comment]
Yes, so in `dev` you could set `Solver ` to `YeePML< ... >` in fieldSolver.param. In this case the PML absorber will be used, it has its own set of parameters in `pml.param` file. The parameters for the exponential damping absorber is then ignored. The default values in `pml.param` should be reasonable, maybe you only need to change the thickness set by `NUM_CELLS` variable there.

**Comment by sbastrakov** [comment]
Please note that in case your setup directory does not have a certain .param file, the default version will be used. To override this, copy a .param file there and modify or use `pic-edit` to create it first.

**Comment by cbontoiu** [comment]
I knew about the param files and everytime I need to modify something I bring a copy of the corresponding .param file from the repository inside spack.
Still with the YeePML solver i get the situation below. Puzzling.

![Screenshot_2020-01-29_17-50-06](https://user-images.githubusercontent.com/7108691/73382663-da7c7e00-42bf-11ea-84ac-215ffefdae88.png)

**Comment by cbontoiu** [comment]
Also I wonder why the laser field amplitude is wiggling? Is there a precision problem with my data?

![laser](https://user-images.githubusercontent.com/7108691/73383739-d5203300-42c1-11ea-98fc-7071475fc92e.png)

**Comment by sbastrakov** [comment]
Thanks for reporting @cbontoiu , I will take a look at the PML weird results later today. About wiggling: i probably do not follow, since on the picture from your last post the amplitude seems the same along y = const lines?

**Comment by cbontoiu** [comment]
Thanks for replying. The quadrupole pattern appeared also with the classical absorber. About the wiggling if you choose any value of x and look upwards along the y axis you can notice variations of the colours. I understand the there is ramping of the pulse until it reaches a plateau but this ramping has variations of ~4e10 V/m if you compare the first to colour stripes.

**Comment by sbastrakov** [comment]
Concerning the [latter picture](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3148#issuecomment-579885153). As far as I can see (and if i did not make a mistake in calculations), your spatial step is 6.19e-11 meters and so the domain size is roughly 13.8 nm. However, the pulse wavelength is 75 nm. So what we see is just the very start of the first (and only) wave of the pulse.

**Comment by PrometheusPi** [comment]
@cbontoiu as @sbastrakov correctly pointed out at 33 iterations you laser propagated `delta_t * 33 *c = 1.2 * 10^-19 s * 33 2.9979e8= 1.2nm << lambda_0 = 75nm`. The initialization plane is at 2nm, so your laser field should go from ~0.8nm till 3.2nm - which you see in red in the plot above.

**Comment by cbontoiu** [comment]
Thank you! I will try with the interpolation. Meanwhile, is there a way to change to background of the pictures produced with png.param from black to white please?

**Comment by sbastrakov** [comment]
Not sure if we support it, @psychocoderHPC do you have any idea? I guess most graphics programs support such a color replacement manually, although that would be not automatic.

**Comment by psychocoderHPC** [comment]
> Thank you! I will try with the interpolation. Meanwhile, is there a way to change to background of the pictures produced with png.param from black to white please?

You can try to change in `png.param` 
```
namespace preParticleDensCol = colorScales::grayInv;
```
to
```
namespace preParticleDensCol = colorScales::gray;
```

Please keep in mind the pngs are only a preview.

**Comment by cbontoiu** [comment]
One remark here:
Although I set ```PARAM_FIELDSOLVER YeePML``` in ```fieldSolver.param``` and this means that number of cells for the absorber is controlled now by ```NUM_CELLS``` in the ```pml.param``` file there is an error at compilation time if the laser is introduced let's say at the 9th cells while the corresponding ```ABSORBER_CELLS``` number is 16 in ```grid.param```. My understanding is that when using ```YeePML``` the ```ABSORBER_CELLS``` in ```grid.param``` is ignored as the ```pml.param``` file takes over. Is it true? If yes, the error should not appear.

**Comment by sbastrakov** [comment]
@cbontoiu you are right, there is a bug with that check for laser init plane always using `ABSORBER_CELLS` in `grid.param` regardless of the field solver being used. I will check if this is easy to fix. For now, as a workaround please set `ABSORBER_CELLS` so that it passes that check. And PML would use `NUM_CELLS` from `pml.param` anyways.

**Comment by sbastrakov** [comment]
@cbontoiu FYI a fix for the bug you [pointed out](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3148#issuecomment-582865342) has just been merged to `dev`, thanks!
