### ISSUE TITLE
calling from the cfg file

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3153]
I am trying to find a way to relate the laser wavelength to the cfg file which is called by the tbg tool. When I enter something like

tbg -s bash -c etc/picongpu/1.cfg -t etc/picongpu/bash/mpiexec.tpl ~/PIC_RUN/....

the 1.cfg controls the number os steps as TBG_steps="..." and the repetition of the output as TBG_e_pngYX="--e_png.period ... " or TBG_hdf5="--hdf5.period .... " 

but what I really want is to find a way in which data is written out as figure and as hdf5 files only every quarter of the laser period that is 0.25*laser_period/unit_time. This would require access to the laser WAVE_LENGTH_SI defined in laser.param and also to the  DELTA_T_SI defined in grid.param. 

I guess one would need an additional file defining two new parameters ((1) write out period and (2) number of simulation steps) placed somewhere and compiled together with the other files. It would also require the cfg file to read in these two parameters as period = parameter1 and TBG_steps=parameter2.

An example: I use WAVE_LENGTH_SI = 53.6375e-9 m for the laser which means a period of 1.7891e-16 s and with my time unit 1.1927e-19 s this give me a ratio period/unit_time = 1500. If I want to run the simulation for just one complete laser period I have to manually write TBG_steps="1500" and then if I want to write out data every quarter of the period I need to manually write .period 375 in all instances across the cfg file. But since I am changing the laser wavelength frequently changing the cfg file by hand becomes tedious and error prone. How can one automate this process?

Thank you.

**Comment by sbastrakov** [comment]
You are right that the `.cfg` and `.param` files do not easily integrate together, since `.param` files are in C++ and `.cfg` are basically generators of command line parameters and thus could not access C++ variables inside.

For the `.param` files we already have `cmakeFlags` ([example](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/share/picongpu/examples/LaserWakefield/cmakeFlags)) which can specifying parameter values (or help doing parameter scans). By default it just uses the first set of settings, you could specify a specific one to build, or all of them. Then the parameter values are given as `-D[parameter]=[value]`, and in your `.param` files you do something like [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d340812641320d3a61e343a521287fd0720ba55b/share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param#L83-L86).

However, I am not aware if there is a simple way to do the same for your `.cfg` files. The two simplistic solutions would be a) to precompute the output parameter values corresponding to your parameter values and make a bunch of `.cfg` files manually or b) make some form of templates for `cmakeFiags`/`.param` files and `.cfg` and make a small script that generates the matching pairs of files.
