### ISSUE TITLE
moving electron bunch

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3169]
I want to generate an electron bunch moving along the y-axis in two situations:

1. without any laser pulse at all;
2. at some time behind a laser pulse;

I know that there was some work on this topic three years ago as I found in this issue #1914 but I am not sure where to start from. 

All I have is the official Bunch model in which the laser impinges on a Gaussian electron distribution. I thought I could generate my bunch from there but it seems that the electron bunch is a charge density region at rest in that model. How to make it move?

Thank you

**Comment by n01r** [comment]
Ping @steindev, @PrometheusPi and @BeyondEspresso, can one of you assist?

**Comment by PrometheusPi** [comment]
@n01r Thanks for forwarding the question.

@cbontoiu There are various ways we currently implement electron bunches in PIConGPU. 

**1.) Bunch as in Bunch example:**
One way is as charged bunch of electrons which do not participate in current deposition. This is done in the [**Bunch** example](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/share/picongpu/examples/Bunch) and is used for non-linear Thomson light sources. It uses the mentioned [Gaussian electron distribution](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/share/picongpu/examples/Bunch/include/picongpu/param/density.param#L52-L82) but also [adds a velocity](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/share/picongpu/examples/Bunch/include/picongpu/param/particle.param#L55-L70) to the bunch particles - which is combined in the [species initialization](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/share/picongpu/examples/Bunch/include/picongpu/param/speciesInitialization.param#L50-L59).
Be aware that this example explicitly does not perform current deposition and that therefore no electromagnetic fields from the particles are introduced. If current would be created, the initial field-free initialization would cause a pseudo-positive background remaining at the initial electron bunch position that would pull back the electrons. (The error is here to initialize field-free.) However, since this is an example to test against analytical radiation predictions, a bunch self-field is neglected on purpose. This option works *with and without moving window*. 

**2.) Bunch from hdf5 and init phase:**
The option discussed in #1914 is to add particles in an empty checkpoint and than push them using the [free pusher](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/include/picongpu/param/species.param#L79-L80). (In principle a similar particle initialization as above is also possible.) With current deposition enabled this allows to slowly create a field around the bunch and avoids the pull-back effect of the "wrong", field-free initialization. 
Since however the fields are generated quite slowly, 100k iterations are usually needed to at leads get a decent field distribution surrounding the bunch. This *requires* in most cases a *moving window*. After the field is generated, the executable is replaced with a version that has a normal (e.g. [Boris/Vay](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/include/picongpu/param/species.param#L72-L73)) pusher by recompiling the executable. This allows "real" simulations only after this long field-generating phase. 

**3.) Bunch with accelerating pusher:**
The more convenient version is to initialize the particles with (nearly) zero velocity and accelerate them in a field-generating phase similar to case 2. For this the [accelerating pusher](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/include/picongpu/param/species.param#L78) is used which defines a [pseudo-field](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/include/picongpu/param/pusher.param#L31-L54) to perform the accelerating to the final velocity and thus self-field generation. This method is more stable than option 2 and requires an order of magnitude less iterations (~10k). After the acceleration, the code needs to be recompiled to use a normal (e.g. [Boris/Vay](https://github.com/ComputationalRadiationPhysics/picongpu/blob/5725049b384fccca384d74f18a31ace066d25e36/include/picongpu/param/species.param#L72-L73)) pusher as in case 2.  


Please by aware that self-field generations currently requires an initialization phase >10000 iterations in PIConGPU using a moving window. Thus this might not be suited for your nanotube setup right away. To introduce a bunch into your nanotube setup, you would need to initialize a bunch (at the same resolution and simulation extend) separately and then add it to the 0th checkpoint of your nanotube simulations by coping/adding the particles and overwriting the fields. (similar to point 2. - as implemented in #1914.)

This should cover your point number *1. without any laser pulse at all*.
For point *2. at some time behind a laser pulse* you can initialize the laser via init plane before the laser while the bunch particles still do not have a normal pusher (as a second init stage since the plane needs to be in the yet not moved window). cc'ing @psychocoderHPC (laser init plane after slides).
 
I hoped this brief introduction helped. If you have further questions, feel free to ask.

**Comment by cbontoiu** [comment]
Thanks! I am always impressed with your answers guys. Let me digest. :)
