### ISSUE TITLE
Feature request: Electron-ion recombination

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3178]
I know that for the moment PIConGPU does not model the recombination of ions with the electrons generated by a laser pulse through ionization. The situation can be seen in the figure attached.

![image](https://user-images.githubusercontent.com/7108691/75142863-de979200-56eb-11ea-8d7f-36d0a71ce47c.png)

Is there a plan to introduce such a feature in the future? It would be very useful because now I can only work below the ionization level in order to have a realistic charge density behind the laser pulse.

Thank you,
Cristian

**Comment by psychocoderHPC** [comment]
CC-ing: @n01r

**Comment by n01r** [comment]
Hey @cbontoiu, thanks for your question. :)
So far, we only have the issue of missing recombination on a lower priority - or mid- to long-term timescale.
For us, with the setups we usually simulate, the targets are either not dense enough or still very thin so that the time scale at which recombination happens is still longer than our time of interest.
I see a total of 100 fs in your simulation there. What would be the estimated recombination rate if you pick out the density and temperature of your material there and just calculate it quickly?
> It would be very useful 

Do you know how large the error is that you're making by neglecting recombination in your setup?

Recombination is a little harder to implement correctly because it is sort of a **collision process (1)** where we then need to **remove (2)** an existing macro-electron and increase the number of `boundElectrons` for a macro-ion that is present in the vicinity and then treat the kinetic **energy** of the electron to make sure it **conserved (3)**.

Regarding (1), we're still missing binary collisions (as the more basic feature) but we have the structure for this already. The physical cross-section needs to be implemented and the model needs to be tested, then. These steps and then the release to the user would take some time already.

For (2), this is similar to the particle merging we have but for (3) we also need to think about how we distribute the energy or when we count it as radiative losses from the plasma.

We are missing the man-power to tackle this quickly and implementing the binary collisions is more pressing for us, at the moment, so that I would think that you'd want to use your simulation results before we could start working on this. As for me, personally, I'm still in the middle of writing my thesis. ^^;

I hope I didn't disappoint you too much and perhaps you'll find out that neglecting recombination for now is still not too bad regarding the effects that you would like to observe in your simulations.

**Comment by cbontoiu** [comment]
Thanks for your quick reply. 
I fully understand the situation. 

I am not able to compute the recombination mean time because I don't have yet a figure for electrons momentum, but the base density is ```~10^27 m-3``` so much higher than for gases. 

While for gases target survival makes no sense and thus recombination can be neglected, for carbon nanotubes a sample is worth ~$1000. We would want to fire several laser pulses and be able to repeat the experiment with the same target in its initial form. 

Anyway, I realize that implementing the concept would be a tedious job and I shall deal without it.

Kind Regards,
Cristian

**Comment by n01r** [comment]
> We would want to fire several laser pulses and be able to repeat the experiment with the same target in its initial form.

Oh wow, that is something that we typically have no chance of doing.
PIC codes in their original form, without added physics, work best for collisionless plasmas - so very high energy density.
That means, either gas targets or totally *obliterating* our solid density targets.
Wouldn't moving a very large free electron density wave along your nanotubes (IIRC that was what you wanted to do) result in at least a break of the Carbon-Carbon bonds?

**Comment by cbontoiu** [comment]
Well, PIConGPU simulations show that a0 = 1e-04 and lambda = 282 nm give no ionization (using barrier suppression and ADK only) to the fifth electron, and waves generated in the the 6th electron layers should not break the bonds; they are stronger than those of diamond. However, I haven't tested Thomas-Fermi ionization yet; I am not sure if the algorithm deals with collisions between ions or between electrons and ions. Maybe the electron waves can knock out electrons from the Carbon ions in my model? In reality the 6th electrons are de-localized and easily respond to external excitation. 

Since I got your attention, could you please ask someone to look to issue #3169. It remained without reply for a week or so.

**Comment by n01r** [comment]
> I am not sure if the algorithm deals with collisions between ions or between electrons and ions.

The model treats collisions between electrons and ions, but in a statistical way (just using the averaged electron energy and ion density, macro-particle-shape-considered, for each cell. The hollow-cylinder shape of the tubes could make the result very different from what the model predicts, though.
