### ISSUE TITLE
Ionization and charge density

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3207]
Hello,
I am trying to make sense of laser interaction with a carbon structure, preionized one. I have two cases:

1)  the wavelength is 25 nm and a0 = 1e-03 and i get a kind of standing wave; ionization progresses at the maxima of the laser Ex electric field as shown in the first gif. Is this an error? I expected the laser pulse to ionize all the way at a growing rate as the Gaussian pulse reaches the top.

![1](https://user-images.githubusercontent.com/7108691/76215462-b6895200-6206-11ea-83d1-05e59e6193aa.gif)

2) the wavelength is 20 nm and the a0 = 1e-2. Now I get something more related to what i expect bu at some point all electrons disappear and the same happens with the carbon ions. What am I doing wrong here?

![2](https://user-images.githubusercontent.com/7108691/76215821-6e1e6400-6207-11ea-8ce0-1033501686af.gif)

On the other hand for the second case the default png images still show the electrons as you can see in the gif below.

![3](https://user-images.githubusercontent.com/7108691/76216258-2f3cde00-6208-11ea-8548-87b67fd36614.gif)

Yet another situation of losing the beam is shown in the figure below

![4](https://user-images.githubusercontent.com/7108691/76233508-353eb900-6220-11ea-840e-47f93dbac2f7.gif)

for this last one I used absorber at all 6 faces with the YeePML solver so

![image](https://user-images.githubusercontent.com/7108691/76233645-67501b00-6220-11ea-892c-d3a6613979c9.png)

I don't know if it was a good idea.

I would be grateful for any suggestion.
Thank you.

**Comment by PrometheusPi** [comment]
Dear @cbontoiu,

thank you for reporting this issue. In order to make sense of the simulation output, could you please provide the `laser.param`, `density.param`and `speciesInitalization.param` (for now). 

Could you also upload `fields_energy.dat` and ` e_macroParticlesCount.dat`? 

That would help us tremendously in understanding/guessing what happened.

**Comment by cbontoiu** [comment]
Thank you very much for your availability to help. I attach the whole input folder below

[one-tube-thick.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/4310903/one-tube-thick.zip)

The model uses a PlaneWave laser as 

`struct PlaneWaveParam
            {
                //##################################################
                static constexpr float_64 PULSE_LENGTH_SI = (10e-15)/2.354820045;
                static constexpr float_64 WAVE_LENGTH_SI = 20e-09;
                static constexpr float_64 _A0 = 5e-03;
                //##################################################
                static constexpr float_64 UNITCONV_A0_to_Amplitude_SI = -2.0 * PI / WAVE_LENGTH_SI *
                ::picongpu::SI::ELECTRON_MASS_SI * ::picongpu::SI::SPEED_OF_LIGHT_SI *
                ::picongpu::SI::SPEED_OF_LIGHT_SI / ::picongpu::SI::ELECTRON_CHARGE_SI;
                static constexpr float_64 AMPLITUDE_SI = _A0 * UNITCONV_A0_to_Amplitude_SI;
                static constexpr float_64 LASER_NOFOCUS_CONSTANT_SI = 0.0;
                static constexpr float_64 RAMP_INIT = 3. * 2.354820045;
                static constexpr uint32_t initPlaneY = 0;
                static constexpr float_X LASER_PHASE = 0.0; // 3.14159265359/2;
                enum PolarisationType { LINEAR_X = 1u, LINEAR_Z = 2u, CIRCULAR = 4u };
                static constexpr PolarisationType Polarisation = LINEAR_X;
            };`

**Comment by sbastrakov** [comment]
Hello @cbontoiu , thanks for reporting the difference in CFL checks. The condition should definitely be the same for both solvers, looks like I forgot it in the YeePML, will fix.

**Comment by PrometheusPi** [comment]
@cbontoiu The (only) issue with your setup is that is does not fulfill the Courante Friedrich Levy condition. In line 33 of your `grid.param`, you define your time step duration as
```c++
constexpr float_64 DELTA_T_SI = CELL_HEIGHT_SI/(1.73205080756888*SPEED_OF_LIGHT_SI);
```
This holds only true for cubic cells. You cells are however not cubic, but slightly longer in y-direction. 
```python
CELL_WIDTH_SI =  0.904 nm
CELL_HEIGHT_SI =  0.929 nm
CELL_DEPTH_SI =  0.904 nm
```
Instead your time step duration should be 
```python
0.9999 / SPEED_OF_LIGHT_SI * sqrt( 1.0 / (1. / CELL_WIDTH_SI**2 + 1. / CELL_HEIGHT_SI**2 +  1/CELL_DEPTH_SI**2)) = 1.7570190875068175e-18 
```
(Please be aware that `sqrt` can not be used directly in this definition in `grid.param`.)


(The original [paper of Yee](https://www.doi.org/10.1109/TAP.1966.1138693)  derives the CFL condition only for cubic cells. The full derivation of the CFL condition can be found [here](http://ece-research.unm.edu/summa/notes/In/0044.pdf).)

**Comment by PrometheusPi** [comment]
@cbontoiu Did you intentionally deactivated the feedback of the current?

**Comment by cbontoiu** [comment]
> @cbontoiu Did you intentionally deactivated the feedback of the current?

I don't know what is this feedback. I have this in the ```fieldOurput.param```

![image](https://user-images.githubusercontent.com/7108691/76418225-28dc6c80-6396-11ea-9ffa-71b578513867.png)

**Comment by cbontoiu** [comment]
Thank you for your corrections about the time step. I modified the ```grid.param``` file accordingly.
I have a few questions:
1. What happens if during the laser-matter interactions particles enter the cells which bear the absorber/PML condition? Are they affected in any way?
2. Are the absorber/PML layers menat to prevent laser/wave reflection back into the simulation domain?
3. Should I initialize the laser (plane wave) with ```initPlaneY = 0``` such that the absorber/PML layers in the left Y region are disabled? Should I initialize the laser inside the absorber/PML layer for example with ```initPlaneY = 16``` for 32  absorber/PML cells. Should I do it just after this layer with ``initPlaneY = 33```?
4. Should there be a few void cells between the left Y absorber/PML layer and the matter, such that the laser pregresses a number of cells in vacuum before hitting the target? 

Thank you.

**Comment by sbastrakov** [comment]
Hello @cbontoiu , `CELL_WIDTH_SI**2` is notation in some programming languages, but not in C++. The simplest way is just to have `(CELL_WIDTH_SI*CELL_WIDTH_SI)` instead. The brackets might be necessary for priority of operations.

Regarding the absorber questions.
1. In the current implementation particles in the absorber areas are not affected while they are still in the simulation volume for both exponential damping and PML. However, the particles leaving the simulation area through these boundaries are removed. We understand this might be suboptimal, but do not plan to change it immediately.
2. Yes, so they simulate free space where ideally outgoing waves never return back to the simulation area.  Exponential damping just decays any waves inside, while PML only absorbs orthogonal to the boundary part, but the motivation is the same.
3. `initPlaneY = 0` is a special case, if this is enabled we will not do absorption at that boundary during the laser duration (even when you set this boundary as non-periodic) and enable it later. So in this case absorber and laser are never operating together. In case you set `initPlaneY > 0` it has to be outside of the absorber width on that boundary, and this should be checked at compile time (please report if this check also does not work as intended!). So for 32 cells of any of the two absorbers (tho it is way too large for PML in my opinion, 16 should be very good already) please set ``initPlaneY = 33``.
4. I think this might indeed be useful with the current implementation in mind, also taking into account the Yee cells with staggered components.

**Comment by n01r** [comment]
@cbontoiu There is definitely something fishy with the ionization pattern you see.
I have seen a standing wave pattern before in an overdense setup where the laser that propagated in the medium ionized it and then the rest of the laser would feel the increase in electron density which caused it to blueshift. The waves started to catch up with one another and cause an oscillating field spike that always fluctuated around the BSI threshold of the next charge state.
Here is an image of that setup to illustrate this effect.

![Ar_jet_electron_density_stripes_combined svg](https://user-images.githubusercontent.com/5416860/76421323-c7bb9580-63a3-11ea-9cd9-675c4c6a66d7.png)

So I'd also be really interested in the absolute electric field from that simulation.
I would also recommend choosing either the normal `BSI` or the `BSIStarkShifted` which seems to overlap better with the regions where the tunneling models level out.

I quickly calculated that in that first GIF that you show you also only seem to resolve your laser period with 4 sample points which are very few. In the setup folder you sent that resolution is increased, however.
For this extremely short wavelength ([Keldysh](https://iopscience.iop.org/article/10.1088/0953-4075/47/20/204001) parameter for C1, and C2 for the maximum intensity of this setup are 6.93 and 10.21, respectively - and if >> 1: multi-photon regime) the target is fully transparent. The electric field could really help and show what's happening there.

Another thing that seems concerning: if you look at E_kin from the `e_energy_all.dat` you can see that in the end of the simulation all of your electrons have a combined energy in the *MegaJoule* range. I assume you do not have a laser that delivers MJ of energy to the target. ^^ So there might be really strong numerical heating happening. In a 2D simulation you would expect your particles to receive orders of magnitude less energy than the full laser pulse carries because you're just simulating a slice.
You could plot `fields_energy.dat` against `e_energy_all.dat` to see where/when things really diverge.

I checked the `ThomasFermi` model for its prediction at the CNT density and you can see that everything gets ionized drastically between 1 and 100 eV of electron temperature.
I assume your single-particle electron energies are unphysically high there. 
![TF_prediction_CNT](https://user-images.githubusercontent.com/5416860/76424654-d35d8b00-63a8-11ea-858d-8b05c02aeebf.png)

Did the suggestions of the others already change the results?

**Comment by cbontoiu** [comment]
Thank you all for your help,

I removed the ionization by collision and the beam is not lost anymore. With only ```BSIEffectiveZ< Electrons >``` and ```ADKLinPol< Electrons >``` the electrons and carbon ions charge is as shown below. I used the classical Yee solver here with the new time step as advised above.

![image](https://user-images.githubusercontent.com/7108691/76437192-17ed2480-63b1-11ea-8e3c-2736789938e3.png)

The electric field is strongest in the vertical X component as it comes from the laser. I did increase the a0 potential to 0.1, a value which I have never used before, being afraid of destroying the target completely. As you can see in the last 25 snapshots (just before the pulse maximum) there are really standing waves

![EX](https://user-images.githubusercontent.com/7108691/76437670-cdb87300-63b1-11ea-9e12-dab541625e51.gif)

and this explains why charge gathers in the minima regions. The density is 1e28 1/m3 as calculated analytically for carbon nano tubes. I limited the right y-axis span of my tube, to stay out of the absorber.

![echarge](https://user-images.githubusercontent.com/7108691/76438278-b2019c80-63b2-11ea-923f-0bcb0f6c9be6.gif)

Carbon ions stay still 

![ccharge](https://user-images.githubusercontent.com/7108691/76438721-466bff00-63b3-11ea-8726-8db1234a6be9.gif)

and here are other relevant plots.

![image](https://user-images.githubusercontent.com/7108691/76441496-6dc4cb00-63b7-11ea-937e-07a57e92f7f8.png)

![image](https://user-images.githubusercontent.com/7108691/76446135-7ec50a80-63be-11ea-8b54-f67cb3113f1b.png)

![image](https://user-images.githubusercontent.com/7108691/76446664-4d007380-63bf-11ea-9998-0a8515a4e6a0.png)

but I don't know how to interpret them yet.


and the interrupted  output file with typical macro particle weighting: 0.151947
[output.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/4319381/output.txt)

I don't know what could I do with the h5 files which apper in two dedicated folders because I use in my cfg file:
```
TBG_e_countPerSuper="--e_macroParticlesPerSuperCell.period 19"
TBG_C_countPerSuper="--C_macroParticlesPerSuperCell.period 19"
```
![image](https://user-images.githubusercontent.com/7108691/76439880-faba5500-63b4-11ea-91a5-de3966ba6141.png)

 
Is is something that I do wrong? Should I trust the result? Please not that 20 nm that I use for the laser is actually much shorter than the plasma wavelength, 280 nm in this case.

**Comment by n01r** [comment]
Did you find out what the problem was, @cbontoiu?

**Comment by cbontoiu** [comment]
> Did you find out what the problem was, @cbontoiu?

Yes, I found the solution. I will upload some movies with my results. for the moment I think only YeePML solver gives the travelling wave expected solution, or at least this is how I got rid of the standing wave pattern for the Ex laser field.

**Comment by cbontoiu** [comment]
the electron charge density:

![charge](https://user-images.githubusercontent.com/7108691/76903196-804a7300-6895-11ea-9150-735311dcc510.gif)

the laser transverse electric field Ex

![EX](https://user-images.githubusercontent.com/7108691/76903225-91937f80-6895-11ea-92ef-d2cefca95fb9.gif)

the longitudinal (generated due to the tube) electric field Ey

![EY](https://user-images.githubusercontent.com/7108691/76903277-aa9c3080-6895-11ea-8be0-7e36c327aec6.gif)

Here is the complete input folder

[one-tube-thick-parallel-LX.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/4345896/one-tube-thick-parallel-LX.zip)

**Comment by n01r** [comment]
Yes, your box simply seems too short.
Do you have access to more computing resources to make it longer?
However, it seems wide enough. What would you say @sbastrakov? D'you see anything abnormal/ any boundary effects transversally?

**Comment by sbastrakov** [comment]
Thanks for reporting @cbontoiu . This looks suspicious to me as well. Looking now.

@n01r as far as I see in the `1.cfg` in the attached archive, that simulation only used absorbers along Y (which by itself it fine and should not cause any issues with PML).

**Comment by n01r** [comment]
Ah, right, there were periodic boundary conditions transversally.

Still, I'm a little concerned by the standing wave of the other solvers. ^^;
Would be good if we could pinpoint why that happened.

**Comment by cbontoiu** [comment]
> 
> 
> Thanks for reporting @cbontoiu . This looks suspicious to me as well. Looking now.
> 
> @n01r as far as I see in the `1.cfg` in the attached archive, that simulation only used absorbers along Y (which by itself is fine and should not cause any issues with PML).

If you refer to tha latest archive, I wonder how can you know about the absorbers from the ```1.cfg``` file? There is only the periodicity there as ```TBG_periodic="--periodic 1 0 1"```? Does it mean that enabling the periodicity disables the aborber layers on both sides? It make sense so. Also I recall that enabling periodicity at the X edges for example makes the particles which excced the the lower x-limit of the simulation domain, appear moving downwards across the upper x-limit. Is this as it should be with periodic conditions?

**Comment by sbastrakov** [comment]
Yes @cbontoiu , absorbers (both PML and exponential damping) only work for axes with periodic set to 0. Since the periodic property is for both the min and max border, it is set for each of 3 axes, and not 6 borders separately. So in your `1.cfg` the absorber was activated for the min and max Y borders. It is still possible to effectively disable one of those by setting the corresponding size to 0 if needed.

**Comment by cbontoiu** [comment]
> 
> 
> Yes, your box simply seems too short.
> Do you have access to more computing resources to make it longer?
> However, it seems wide enough. What would you say @sbastrakov? D'you see anything abnormal/ any boundary effects transversally?

Thank you for looking to my results. This simulation took 38 hours on my computer.  For the moment I don't know how to run the code on a cluster, but I just got acceess to one at Liverpool University. I am in the process of learning. 

If you have a chance you could run the files in the last zip folder using other solvers and check for the standing waves. The zip-folder attached in this thread, ```one-tube-thick.zip``` should result in such a situation, but I don't rember all differences between the two simulation cases.

**Comment by sbastrakov** [comment]
For spotting the differences please use [`diff -r [directory1] [directory2]`](https://superuser.com/a/481595). Earlier in that thread there were also commands to get the list of files that are different, not the differences themselves.

**Comment by sbastrakov** [comment]
Hello @cbontoiu , I tried to reproduce by running the setup in `one-tube-thick-parallel-LX.zip`. The `one-tube-thick.zip` as attached does not match the CFL condition - now the PML solver also checks it. There are also other differences between the two, as shown by `diff -r` (described in the previous message).

I am confused by values of `dt` and `t` in the gifs you attached for the ...parallel-LX version. Here the actual `dt = 0.0002 fs`. This does not match 10 fs in the output, but also even t in the .gifs is not equal to iteration multiplied by 10 fs. However, I assume this is just a visualization inconsistency due to changes in the setup, and not different simulation parameters. If the parameters were indeed different, please attach the up-to-date version.

I ran that setup for 5000 iterations. Just FYI, on a Tesla V100 GPU these iterations took 33 minutes. I did not observe the deformations in electron change density, attaching a couple of pictures. Sorry for not making a gif, I had some difficulty with doing it, but I think even from these pictures some differences are seen from your .gifs. I also did not see visible laser reflections from the absorber. I also noticed that your original 1.cfg uses a much larger number of time steps: 144896, so I only simulated the very start. Are the iterations numbers in your .gifs also for the very start of the run? So basically something does not match, I am not completely sure what. 

<img width="249" alt="e_chargeDensity_0200" src="https://user-images.githubusercontent.com/6825656/77059818-d9babb00-69d7-11ea-9d8d-a9ef60730b49.png">
<img width="246" alt="e_chargeDensity_0600" src="https://user-images.githubusercontent.com/6825656/77059819-da535180-69d7-11ea-8cac-06e952c9e8a3.png">
<img width="248" alt="e_chargeDensity_1500" src="https://user-images.githubusercontent.com/6825656/77059820-da535180-69d7-11ea-8016-8fd1805649ad.png">
<img width="244" alt="e_chargeDensity_4500" src="https://user-images.githubusercontent.com/6825656/77059821-daebe800-69d7-11ea-9b07-73921faefffc.png">

**Comment by cbontoiu** [comment]
Hello, thanks for looking into this. The simulation resulted in more than a thousand files, as I am sampling four times per laser period. A .gif with all of them would be in the order of 5-7 MB and impossible to upload on github. Even the Jupyter kernel dies if overloaded. What I do instead is to write out an image every 50 files or so and then upload here
https://ezgif.com/maker
to create the gif. This is why you see less snapshots in the uploaded gifs. However, even in your last picture I see the electrons fluctuating;  with 5000 iterations you are just in the beginning of the laser pulse and the electric field is still small. 

I will keep you updated on this problem of the standing waves as soon as I notice it again, but so far I am happy with the latest model and I managed to work with longer tubes at lower meshing. The next step I have to do is to include the ionization by collision and maybe decrease a0 not to pulverize the target below the minimum weight.

Cheers,
Cristian

**Comment by PrometheusPi** [comment]
> I don't know what is this feedback. I have this in the `fieldOurput.param`

Sorry for the delayed answer: The feedback I meant was the current deposition. But it was my mistake - you chose the default current deposition scheme by not setting (due to not having a `species.param`). I was confused with the current interpolation method, which was set to `None` in your `fieldSolver.param` - but this is all fine.

**Comment by sbastrakov** [comment]
@cbontoiu FYI we just discovered a bug in the `dev` version regarding the exponential absorber. It was there since February 20 and will be fixed today. Perhaps this can explain the standing waves in all solvers but `YeePML`, since that was the only non-affected solver+absorber combination.
