### ISSUE TITLE
Is HasIonizersWithRNG and UsesRNG needed?

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3336]
`HasIonizersWithRNG` seems to be never used. I am not sure, if it just became obsolete and was not removed, or is it planned to be extended on?
I stumbled upon it while investigating the same question for `UsesRNG`. It is similarly only specialized by ionization but this information seems to never be used anywhere, so it seems can be just removed.

@n01r I guess you know it?

**Comment by n01r** [comment]
All the BSI models don't need an RNG and therefore it can be optimized out.

**Comment by sbastrakov** [comment]
@n01r my idea was not that some ionizers do not actually need it, but for what purpose are these traits at all. It looked to me as if just removing these traits whatsoever will change nothing.

**Comment by n01r** [comment]
Hmm, [this](https://github.com/ComputationalRadiationPhysics/picongpu/commit/1d80c950b09d20692861e39d0285419834fec804) and [that](https://github.com/ComputationalRadiationPhysics/picongpu/commit/f929052edcab9fd207bc60fe0ea25a76ad9ba0b0) were the initial commits. 
That's why I don't remember writing these :smile:
I think, the idea might have been to write the used ionization models per species to openPMD-flavored output to keep this information even without input files.
Otherwise you're right. They aren't used anywhere at all.

**Comment by sbastrakov** [comment]
These were removed by #3367, closing.
