### ISSUE TITLE
openPMD plugin running with gcc@9.3.0

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3337]
Hello, I wanted to have a fresh installation of ```PIConGPU``` through ```Spack``` so I configured it with the latest version of ```CUDA``` (11) and the lastest version of ```openMPI``` (4.0.5). To test my installation I made a copy of the ```LWFA``` example and the compilation went fine. I attach the log as:

[out.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/5142872/out.txt)

However, there is a problem at the run time and I would kindly as you to look into this.

Here is the error in the terminal:

[error_terminal.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/5142884/error_terminal.txt)

Here is the input model (all files):

[myLaserWakefield.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/5142886/myLaserWakefield.zip)

and here is the output folder (all files):

[outputLWFA_01.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/5142917/outputLWFA_01.zip)

The error is due to the ```openPMD``` plugin because removing it from the ```etc/1.cfg``` files makes the model run successfully. Either I don't have a dependency installed or there is a bug somewhere. Just checking the folders created by ```Spack``` I can see ```adios``` and ```hdf5``` but there is no equivalent for ```openPMD```.

Thank you.
Cristian

**Comment by PrometheusPi** [comment]
@cbontoiu The issue originate from the *openPMD* plugin not being build with your picongpu exectuable. Are you running on a current `dev` version of picongpu? Since #3281, the cmake outputs whether it found openPMD-api (and where) or not. But your build output contains neither output. Thus I can only assume you are running a pre-2020-07-14 version of PIConGPU. Furthermore I am confused that you seem to not have build the openPMD plugin but no "not found" output was given either. Does your code contains the commits from #2966 added on 2020-06-24? (please be aware that currently only the `dev` version of PIConGPU supports the openPMD plugin.) 

Regarding the other error `matches no installed packages`, perhaps @SimeonEhrig or @psychocoderHPC can comment on that.
