### ISSUE TITLE
Complex math is partially broken

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3379]
#3245 introduced at least two bugs in complex math implementation, that originally went unnoticed:
- `abs()` implementation is wrong
- return types of `abs()` and `abs2()` got changed from real to complex, but the remaining implementations, like `pow()`, `log()`, `exp()` seems to assume it's real which results in at least unnecessary recursion and may be an infinite one as well. So will need to go back to real.

We just discussed it offline with @psychocoderHPC and @BeyondEspresso . Please feel free to add if I missed some other malfunctions in the description.

Luckily, this change was made after 0.5.0 release and so does **not** affect it.

**Comment by BeyondEspresso** [comment]
The `abs`- and `abs2`-functions can return a complex number in the form (result,i * 0.0) in order to be more consistent with the other types' implementions. This can also avoid some type-casting in complex-number expressions. However, when reducing to real-valued expressions, such as to avoid recursions in the definition, one has to explicitly call the member-function `get_real()`.

**Comment by sbastrakov** [comment]
Yes, so there is a choice of either returning a complex, but taking the real part explicitly where we need it. Or changing back to returning real numbers like  it used to do before the changes in #3245 . Which was admittedly not very obvious that it did return a real.

**Comment by PrometheusPi** [comment]
@BeyondEspresso @gerompampastrumf This might explain some of the discrepancies observed in #3366.

**Comment by PrometheusPi** [comment]
@sbastrakov great catch :+1:

**Comment by BeyondEspresso** [comment]
@sbastrakov Only that it was the other way round (as it is still in the current master-branch): Before the changes #3245 the `abs`-function returned a complex with the result in the real part. There were two main reasons for this decision. 1) The `abs`-function is the basis of several other complex function implementations, especially `sqrt()`, `pow()` and `log()`, so that a complex return-type for `abs()` avoids immediate back-conversion to a complex in these functions. 2) The implementation should mimick the behavior of std::complex.

For these reasons, the preferred choice is a complex return type.

**Comment by sbastrakov** [comment]
@BeyondEspresso I am not sure your message is accurate. 

In the `master` branch, so before #3245 changes, both [Abs](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/pmacc/math/complex/Complex.tpp#L166-L168) and [Abs2](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/pmacc/math/complex/Complex.tpp#L178-L180) did return a real type (`Complex<T_Type>::type` [is real](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/pmacc/math/complex/Complex.hpp#L37)). 
Also `std::abs(std::complex)` [does return a real number](https://en.cppreference.com/w/cpp/numeric/complex/abs) .

Whether it is better to avoid back-conversion in some places, or have an unusual return type, I am not sure. I would personally prefer to have the return type back to real, and add explicit conversion to complex when necessary. Will open a fixing PR today.

**Comment by PrometheusPi** [comment]
I agree with @sbastrakov. Having a complex return type for `abs` seems very counter intuitive.

**Comment by BeyondEspresso** [comment]
I must apologize, for some unfathomable reason I read the stuff the wrong way round. @sbastrakov is of course right.

**Comment by sbastrakov** [comment]
Solved with #3387, closing.
