### ISSUE TITLE
Density of fully ionised gas does not match?

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#3420]
Hi,

Good evening. I am testing the density of a fully ionized helium gas by using `picongpu@0.5.0`. I initialized a homogeneous profile with the following params:[betatron_test.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/5497380/betatron_test.zip)

The base density is set to be the Helium ion density
```
#ifndef PARAM_BASE_DENSITY_SI
#   define PARAM_BASE_DENSITY_SI 4.0e24
#endif
```
In `speciesInitialization.param`, I am following the manual by using `ProtonTimesWeighting`:
```
    using InitPipeline = bmpl::vector<
        CreateDensity<
            densityProfiles::Homogenous,
            startPosition::Random2ppc,
            PIC_Helium
        >,  
        ManipulateDerive<
            manipulators::binary::ProtonTimesWeighting,
            PIC_Helium,
            PIC_Electrons
        >
    >;
```
So the electron density to be created will be 2 times that is 8e24. I assume ne = Z*ni, where Z is the charge of Helium. I then plot the result of zero time step by using openPMD. The Helium density here is 8e24 while the electron density is 1.5e25, which is 4 times the base density. 
Did I set something wrong or miss something? Thanks.

![Screenshot 2020-11-05 at 10 44 05 PM](https://user-images.githubusercontent.com/52823653/98294484-b40b1200-1fb8-11eb-86a6-339613b41aab.png)

![Screenshot 2020-11-05 at 10 43 38 PM](https://user-images.githubusercontent.com/52823653/98294476-b0778b00-1fb8-11eb-977a-9c8ecd1b0620.png)

**Comment by sbastrakov** [comment]
Hello @StevE-Ong .

Sorry, I am perhaps missing something. But from the colorbars on the plots attached it seems the He_density is about 4e24 (so base density) and e_density about twice that. Could you clarfy where do e.g. 1.5e25 for electron data point comes from? - to me it looked to just be the max tick on the colorbar.

**Comment by StevE-Ong** [comment]
Thanks for your reply @sbastrakov. I am looking at the maximum of the tick at the colorbar so the density is 1.5e25. Isn't it the maximum should not be more than the base density? Or how should I look at it?

**Comment by sbastrakov** [comment]
So initially we generate macroparticles according to the user-given density, in your case uniform. We (and other PIC codes as well as far as I know) do not actually sample the given density fully randomly on the whole simulation area, as this would be problematic computationally. Instead, we do it on a cell basis: evaluate the density functor for each cell, from there get the expected number of physical particles for this cell, then take into account user-requested particles per cell (in your case 2) and `MIN_WEIGHTING` and finally get the number of macroparticles for this cell. This many macroparticles are created and Initial positions are selected according to the second parameter of `CreateDensity`, in your case randomly inside the cell.

So if you integrate along a reasonable large volume, by counting the number of physical particles (as number of macroparticles times weighting, as your weighting is constant in this case) and divide by the volume it should give a number that's very close to your expected density.

However, this density output you've got is not computed like that. Instead, it is based on actual data of macroparticles in simulation and computed with the same resolution as grid node. Since you only have 2 macroparticles per cell, distributed randomly inside, naturally it can be that a certain grid node would have macroparticles spawned near it from each of the adjacent cells. And so this value of density would be larger than average. And some nodes would have particles father than average and so smaller than average density.

**Comment by sbastrakov** [comment]
So as a tl;dr of my last message. The output you posted is the "numerical" density on a really finely resolved grid and on such a small scale you really see the effects of random sampling of macroparticles. And I don't see anything wrong with it, since it's what the simulation actually operates with. These effects should be much less seen on a less resolved grid

**Comment by StevE-Ong** [comment]
Thanks, @sbastrakov for the clarification. So from the figure what I actually see is the density fluctuation, say electron density between 0.2-1.5e25. Taking a larger number of particles per cell can help in reducing the fluctuation. The following is the case for 4 macroparticles per cell:
![Screenshot 2020-11-06 at 4 56 09 PM](https://user-images.githubusercontent.com/52823653/98380385-2cbdad00-2051-11eb-8bfc-95c3344750ba.png)
I guess for a gas target these fluctuations won't have much effect to the outcome.

**Comment by sbastrakov** [comment]
Yes. In other words, what you get from this type of output is the density of markers (macroparticles). Which approaches the real physical density as you increase the number of macroparticles per cell or shape order. However, it can be rather "jumpy" with few macroparticles per density data point. Which is what you setup does, however it should still be fine in terms of whether the PIC method is adequate; you just see the visual effect of sampling and grid discretization.

Or if you just look at less refined detalization level, since then while you would get still the same number of markers per volume, you would get more per density data point and that would smooth the "jumps"

**Comment by sbastrakov** [comment]
@StevE-Ong we have actually done a small study of how macroparticle sampling affects current values on the grid, which is of course a similar type of fluctuations as you observed. The results are reported in #3392
