### ISSUE TITLE
We need to add a check for Debye length resolution

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#3421]
Triggered by #3377.

For now I'm thinking of having it around the same place as we check resolution of the plasma frequency. So only at start of simulation and output it in the same fashion, so that it's a diagnostic warning, not a hard error.

To implement it, I plan to estimate the standard deviations of particle momentums per cell or supercell, and get an estimate of temperature out of it.

@psychocoderHPC suggested we could also consider doing it for the "new" area when a moving window slides.

**Comment by cbontoiu** [comment]
Hello,
Another check that should be there (maybe it is but I am not aware) is a clear message to the user that there is no laser beam in use. That is there might be a laser defined but there is no ```using Selected = ... < ... > ;``` at the end of the ```laser.param``` file. I spent a few days wondering why none of my laser modifications gave any impact onto the target when in fact no laser was used at all. Of course PIConGPU can run models without laser beams, but I think there should be a warning when the simulation starts, because missing ```using Selected = ... < ... > ;``` doesn't end in a compilation error.
Thank you.

**Comment by sbastrakov** [comment]
Sorry @cbontoiu I do not fully understand the issue with no `Selected`. Could you post an example of a `.param` file that illustrated it?

**Comment by cbontoiu** [comment]
> 
> 
> Sorry @cbontoiu I do not fully understand the issue with no `Selected`. Could you post an example of a `.param` file that illustrated it?

The zip folder attached to my issue #3412, now closed contains a ```laser.param``` file with this situation. You can compare that file with other laser files and note that the last statement ```using Selected = ... < ... > ;```, which means my laser is defined but not used.

**Comment by sbastrakov** [comment]
I can see it, however having `using Selected` is a compile-time requirement. And a setup with `laser.param` not having it does not compile. In case a setup does not define its own `laser.param` (does not have it in `include/picongpu/param` of the setup directory), a default version of this file will be used. Which has no laser by setting `using Selected = None<>;`. However, this type name must be defined, otherwise there is no way the code compiles.

**Comment by steindev** [comment]
Closed with PR #3446
