### ISSUE TITLE
Laser pulses

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3482]
Hello,

The image attached shows 3 types of laser pulses interacting with a carbon nanotube. The first one is a PlaneWave without any focus in the transverse zx-plane, the second one is Gaussian with a transverse FWHM diameter of 20 nm and a focus at y = 250 nm and the third one is Gaussian with a transverse FWHM diameter of 20 nm and a focus at y = 0 nm. All three cases use ```static constexpr uint32_t initPlaneY = 17u;``` and there are 8 PML cells at y limits.

I would kindly address some questions:

1. How to use a Gaussian pulse without any focus point?

2. Is the second negative wave generated only once at ``` initPlaneY = 17u``` for numerical reasons or it continues to be generated as the laser propagates?   

3. Is there a way to distinguish the transverse electric field coming from the laser pulse from the transverse electric field coming from the separation of the electrons and ions in the target? 

4. In the case of Gaussian pulses is the strong field envelope modulation due to scattering on the target or there might be something else? Radiation was not switched on so the electrons should not radiate.

Any literature recommendations related to numerical laser implementation is highly appreciated.
Thank you

 
![laser-pulses](https://user-images.githubusercontent.com/7108691/102605470-3987f300-411d-11eb-87e1-089634304b67.png)

**Comment by PrometheusPi** [comment]
@cbontoiu 
**regarding question 1:**
Any electromagnetic wave with a transversal envelope will experience focusing and defocusing. Thus a focus position (in vacuum) is an essential requirement if you introduce a transversal envelope. PIConGPU comes with one laser pulse called `wavePacket` that does not define a focusing position, but this is due to the fact that its focus position is set to `y=0` and the thus much simpler implementation of the pulse allows for easy manipulation of the envelope. 

**regarding question 2:**
The second negative wave originates intrinsically from how we initialize the laser pulse. We avoid computing the magnetic field and thus do not set these values. Thus they are effectively zero. We only set the electric field. However, with regard to Maxwells equations this is equivalent to two counter propagating waves. The have the same electric filed value (thus to combined electric field value is twice as large - that's what we initialize), but the magnetic field values have opposite signs and thus cancel each other. (An alternative approach would be to cancel the electric field and double the magnetic fields.) Since these values are later on handled by a field solver, the only valid solution it can produce are two counter-propagating waves. Thus as long as the laser is initialized in PIConGPU, you will observe the counter propagating wave. 
If you need to avoid this second wave, you could implement a laser init routine that initializes both the electric and the magnetic field - this would avoid introducing the counter-propagating wave. 

**regarding question 3:**
A naive approach would be to run the setup once without particles and once with particles and then subtract the fields of the second simulation from the first simulation. But please be aware that this assumes that the fields can in principle be separated. This is in principle true but might contain more involved physics than just charge separation. E.g. if the laser interacts with a solid target, the laser is reflected. The reflection originates of course from the charge separation but is best described by the oscillating motion of the electrons and nut just by a displacement. 

**regarding question 4:*
Radiation in any PIC code is always treated by the field solver and thus within the limits of the solver. This means that not activating the (classical) radiation plugin, does not deactivate particles radiation. In contrast, the radiation plugin does not imply a feedback to the particles thus the simulation behaves exactly the same (within concurrency effects due to parallel execution) with and without radiation. The purpose of the (classical) radiation plugin is the prediction of the spectrally and directionally resolved radiation beyond the limits of the field solver. If you for example have betatron radiation during LWFA, the radiation is emitted in the x-ray regime. The particle dynamic can be handled by the PIC code. But the emitted radiation (lambda_laser > cell_size >> lambda_betatron) can not be resolved by the field solver. On the other hand, scattering of radiation at the laser frequency or plasma frequency (Raman scattering, etc.) can be resolved by the field solver (possibly not with a good directionally resolution). Thus what you observe might definitely be radiation from the particles - which is according to my guess based on the plots) easily described by scattering - which brings us back to your question 3 - the difference in field values between with and without particles thus not only shows the charge separation fields but also the scattering and (more confusing) the reduction of the laser pulse as a laser pulse with half-period phase shift (=opposite  amplitude sign).

I am not aware of any literature that describes laser implementation in PIC codes in detail. Perhaps @steindev or @sbastrakov could comment on that.

**Comment by steindev** [comment]
> I am not aware of any literature that describes laser implementation in PIC codes in detail. Perhaps @steindev or @sbastrakov could comment on that.

Well, there is literature on methods, but there is no publication on the method we use. 

> Is the second negative wave generated only once at initPlaneY = 17u for numerical reasons or it continues to be generated as the laser propagates?

Is there a specific reason to set the initPlane within the simulation volume and so close to the boundary? If you initialize at the boundary, as usual, there will be no second wave.

**Comment by steindev** [comment]
@cbontoiu Where you able to solve the issue and want to close this or do we need to look into this further?

**Comment by cbontoiu** [comment]
Yes, I solve it by reading about the physics of the Gaussian pulses from Svelto's book Principles of Lasers. I also greatly appreciate the comments of @PrometheusPi  above. Thank you. I will close this issue. Regards
