### ISSUE TITLE
Memory Buffer Error

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3495]
Hello, I got the error below

![image](https://user-images.githubusercontent.com/7108691/105613695-19062500-5dbc-11eb-9bf6-58e9b78dabd3.png)

with these settings for the ```memory.param``` file

![image](https://user-images.githubusercontent.com/7108691/105613717-4357e280-5dbc-11eb-861c-954862ba7094.png)

This error happened while processing some data with ```matplotlib```. It might happen that other processes exhausted the memory available to ```PIConGPU``` or to ```openMPI```. Any idea how can we overcome it?
Many thanks.

Cristian

**Comment by psychocoderHPC** [comment]
How much main memory is available on the host system? How many GPUs and which type do you use per compute node. The output library adios reported that it was not possible to allocate 5GiB memory.

**Comment by cbontoiu** [comment]
Hello @psychocoderHPC 

and thank you for your reply. I have two GPUs as in the image attached (each with 16 GB) and the RAM is 64 GB. I suspect that ```with concurrent.futures.ProcessPoolExecutor() as executor:``` in Python ruins my simulations and other processes on the machine. I wouldn't ask you to investigate this, but maybe my error message can help the developer team to take such problems into account. Perhaps an ```out-of-core``` feature would be helpful https://www.xspdf.com/resolution/20321042.html

![image](https://user-images.githubusercontent.com/7108691/105633358-f887aa80-5e4f-11eb-8610-880ee3e53c78.png)

**Comment by sbastrakov** [comment]
To me the output also suggests ADIOS could not allocate 5 GB of host memory. Normally we recommend having host memory of at least 2x size of device memory for PIConGPU. This seems to be the case for your system already, so maybe it happened because other tasks used up all host memory, or somehow your Python executor limited it (I have no idea about it).

Regarding out-of-core, ADIOS 2.0 is doing something kind of similar for us. In a way that when we output data, we just feed it to ADIOS 2.0 (if it is used as openPMD-API backend in `dev`). And then depending on settings it can go to disk or be in-memory transferred. So I would not call it out-of-core, but it is maybe more what PIC workflows need. Our core simulation data (macroparticles, fields) is however always in memory, but is hardly practical to change it.
