### ISSUE TITLE
Install on a single user desktop computer

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#3622]
I'm a potential new user, interested in developing an academic project that would demonstrate using PIConGPU on a high performance desktop computer.  I have read through your very thorough readthedocs documentation for installation on HPC systems and wonder if an installation procedure for a single user PC exists or could be described.  If not, I may get to work on creating one.  The intended end result will be a basic PIConGPU PC tutorial that describes installation and then running the laser wakefield example.

Let me know if something like this has already been done.  Also, please let me know if there is a more appropriate venue for my question.

Thanks,
Kim

**Comment by pordyna** [comment]
I think on linux you should be able to just follow the instructions from here https://picongpu.readthedocs.io/en/latest/install/dependencies.html to install all dependencies and than compile as usual with `pic-build` and run from the command line (without tbg). Though you would probably run into problems if your are using the same GPU for your monitor output. @sbastrakov @psychocoderHPC should know more about it.

**Comment by sbastrakov** [comment]
Hello @kimjohn1 thanks for your interest in PIConGPU.

Yes, it is possible to install PIConGPU on a single PC as well. [The general schema](https://picongpu.readthedocs.io/en/latest/install/instructions.html) from the docs applies to any machine. You have a choice between spack, docker, and manual management of dependencies. The latter meaning a combination of system-installed libraries and built-by-yourself ones. So if your machine and operating system supports spack or docker you could try that, since it's in theory most easy for a user. I am not 100% PIConGPU spack would work perfectly fine on Windows, didn't work last time I tried, but that was a while ago. On Linux both spack and docker should in principle work.

If you fall back to manual installation, it is also possible, PIConGPU is just an application written in standard C++, just with some dependencies. This for sure works on Linux and Windows, on Mac OS I do not know if anyone did it recently but also see no reason why that would not work. If you take that route, please note that most dependencies are optional (and marked as such in rhe documentation). If you are doing a first installation of PIConGPU I think it is more practical to only have required dependencies (so basically just cmake, boost and what PIConGPU has inside) and make it work. Other dependencies can be added later on incrementally.

In case you need a more specific advice or encounter any issue, please ask further and provide your OS and hardware configuration, we will assist you.

**Comment by sbastrakov** [comment]
To add up to my example a little bit. Most PIConGPU developers and users/developers use it on an HPC cluster or a workstation. For each such a system, we create an "environment" such as [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/juwels-jsc/gpus_picongpu.profile.example) to load all dependencies, that is reusable. Note that it combines system-installed modules for what was available, and own-compiled libraries for the rest.So on a Linux-based system you would need to gradually build something similar. Again, it will come out gradually from only mandatory dependencies, and than add optional ones that you need. On a Linux PC you could do the same in principle.

On Windows, our build scripts will not work in the standard terminal (and not really in a Linux terminal on Windows). But one can use just plain cmake to generate projects e.g. for Visual Studio and build from there. I have experience there and can share if needed.

**Comment by kimjohn1** [comment]
Thank you for the responses.  I believe this provides me with exactly what I need for how to begin.  Based on your suggestions, I plan to build PIConGPU from scratch, installing the minimum number of dependencies, then expand the dependency list ad hoc as I work through the project.  I have a couple of follow on questions, which I will post here, but please let me know if you would prefer that I close this issue and open a new one for my follow on questions.

My project will use Linux for the OS, and will include physically separate GPUs for general purpose processing, and for visual output.  The project includes using PIConGPU and in situ visualization using a scientific visualization application.  Can you recommend the simplest or most efficient approach I might take for passing output from PIConGPU to the visualization application?

Finally, an eventual goal of the project is to package the PIConGPU/Scientific Visualization end product in a Singularity container.  I happened to try using a PIConGPU Singularity container link that I found in your documentation, and it appeared to be broken.  Do you have an old Singularity definition file that I might use as a starting point to build from?

Thanks,
Kim

**Comment by pordyna** [comment]
Hi @kimjohn1, for the visualization you can use the ISAAC plugin which is an in situ visualization tool that is directly coupled to PIConGPU. You could also pass the field and particle data using the SST backend of ADIOS2 with our openPMD plugin to some other visualization tool but I guess that wouldn't be in situ anymore.

**Comment by kimjohn1** [comment]
@pordyna, thank you for this particularly useful information.  Can you tell me how data is passed to ISAAC, and describe what else I would need to do to replace ISAAC with another visualization tool?

Kim

**Comment by psychocoderHPC** [comment]
> @pordyna, thank you for this particularly useful information. Can you tell me how data is passed to ISAAC, and describe what else I would need to do to replace ISAAC with another visualization tool?

If you would like to use a different tool for the visualization you should dump your data with the OpenPMD plugin PIConGPU provides and visualize the dums after the simulation. The disadvantage is that you can not dump each simulation step else your hard disk will be filled very fast.
ISAAC is giving you the infrastructure to visualize the data during the simulation is running. It is not possible to replace ISAAC by another visualization tool because the workflow how data is passed to ISAAC is defined by ISSAC and will **not** follow any standard e.g. vtk.

I suggest starting with compiling and starting PIConGPU base on the documentation and if this works please open a new issue if you have trouble using ISAAC with PIConGPU. 

We try to use one issue per topic to avoid confusion if the topic is changed in an issue. This issue should handle the installation on a desktop computer.

**Comment by sbastrakov** [comment]
@kimjohn1 openPMD also supports streaming (so your "file output" data reside in memory, not disk), so you can still do in-memory visualization with that. However ISAAC or coupling another visualization tool would be closer to traditional meaning of in-situ visualization.

For ISAAC there should be some documentation, @FelixTUD could you recommend what's best suited?

**Comment by psychocoderHPC** [comment]
@kimjohn1 I opened in the ISAAC repo an issue where we can collect information about ISAAC workflows.
How ISAAC works is independent of PIConGPU. PIConGPU is only one application which is using ISAAC.
To understand how ISAAC works you could also have a look to the example provided by ISAAC, it is much easier than the PIConGPU monster^^.

https://github.com/ComputationalRadiationPhysics/isaac/issues/142

**Comment by FelixTUD** [comment]
@kimjohn1 the plugin, where ISAAC accesses the particle and field data in PIConGPU, can be found here:
[include/picongpu/plugins/IsaacPlugin.hpp](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/include/picongpu/plugins/IsaacPlugin.hpp)

**Comment by kimjohn1** [comment]
Thank you all for the explanations and source references.  I believe there is plenty of information here for me to get going.  I will investigate 3 options for in situ visualization with PIConGPU in my project:
- Using ISAAC
- Replacing ISAAC with another visualization plugin
- Using OpenPMD streaming with an external visualization tool
Thanks for being patient with me.
Kim

**Comment by psychocoderHPC** [comment]
> Thank you all for the explanations and source references. I believe there is plenty of information here for me to get going. I will investigate 3 options for in situ visualization with PIConGPU in my project:
> 
> * Using ISAAC
> * Replacing ISAAC with another visualization plugin
> * Using OpenPMD streaming with an external visualization tool
>   Thanks for being patient with me.
>   Kim

@kimjohn1 For which organization, university, or company do you work on this topic? If you like we could also have a VC to get a better overview of your needs. With more background knowledge we can maybe help you to choose one of the three or maybe a different option. Feel free to contact me via email: r.widera@hzdr.de
