### ISSUE TITLE
segfault with SST on current dev

### ISSUE THREAD

**Issue by pordyna** [ComputationalRadiationPhysics/picongpu#3631]
When I enable the `openPMD` plugin and set it up to use `SST` I get a segmentation fault  in `PIConGPU` when I try to connect a reader. Also the reader complains about the `/openPMD` attribute not being set correctly by the reader.  

The simulation run on the `fwkt_v100` queue on `hemera` the reader was starter from the `jupyter` service on the `csk001` node.
.
`PIConGPU` error:
```bash
[gv019:79694:0:79694] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x2ac327d80000)
```
reader error:
```
[ADIOS2] Warning: Attribute with name /openPMD has no type in backend.
[ADIOS2] Warning: Attribute with name /openPMD has no type in backend.
[~ADIOS2IOHandler] An error occurred: [ADIOS2] Requested attribute (/openPMD) not found in backend.
terminate called after throwing an instance of 'std::logic_error'
  what():  ERROR: EndStep() is called without a successful BeginStep()
```
Here is the full simulation stderr 
[sst_bug_writer.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/6554960/sst_bug_writer.txt)

Here are the streaming settings from my `.cfg` file 

```bash
TBG_ADIOS2_SST="'{                            \
  \"adios2\": {                               \
    \"engine\": {                             \
      \"parameters\": {                       \
        \"RendezvousReaderCount\": \"1\"      \
        , \"ControlTransport\": \"sockets\"   \
        , \"DataTransport\": \"WAN\"          \
        , \"BufferGrowthFactor\": \"1.1\"     \
        , \"InitialBufferSize\": \"36Gb\"     \
        , \"Profile\": \"Off\"                \
      }                                       \
    }                                         \
  }                                           \
}'"
TBG_openPMD1="--openPMD.period 10:100:2  \
             --openPMD.file simData \
             --openPMD.ext sst \
             --openPMD.json !TBG_ADIOS2_SST"
```

@psychocoderHPC @sbastrakov @franzpoeschel did you maybe encounter something similar before?

**Comment by franzpoeschel** [comment]
Hi @pordyna,
PIConGPU writes each time step as a single file by default, which for streaming does not make a lot of sense (and we don't support it). Note to self: Throw an error if such a situation is detected, and maybe in PIConGPU, undo that default behavior if SST engine is chosen.

To override that default, you should specify `--openPMD.infix NULL`.

However, the error message that you get still looks weird and suggests something else could still be wrong. If the above setting doesn't work, can you tell me the software versions that you use (ADIOS2, openPMD, maybe PIConGPU)?

**Comment by pordyna** [comment]
Hi @franzpoeschel , I think you are already taking care of this here https://github.com/ComputationalRadiationPhysics/picongpu/blob/131aad5211464c05cf240232dc1717e45a046a8e/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L366
So for PIConGPU I used the modules from the fwkt_v100 priofile  `ADIOS2=2.7.1` and `openPMD=0.13.2`.
PIConGPU was on dev branch, I already tried pulling dev and recompiling today. 
`openPMD-api` on the reader side was on the 6fd39365ff4bf6e350faec66a5ebac2f3804e8dd commit (dev branch from 07.04.2021) (compiled against ADIOS2 2.7.1). I did also try using this commit for PIConGPU instead of the hemera module but it didn't change anything.

**Comment by franzpoeschel** [comment]
Huh, I don't even remember that. I should still keep in mind to do that error-check in openPMD though.
Back to the issue, I think I saw similar errors some times and if I remember correctly, this usually was an issue of using too much memory.
For verifying that, could you try running the same simulation but with a lower grid size or something else that would significantly decrease the memory usage? That way, we could cancel out a logical error.

If the issue actually is with memory usage, you can try setting the `"QueueLimit"` parameter of ADIOS2 to `"1"`, we recently had trouble with not setting that, see [here](https://github.com/openPMD/openPMD-api/pull/971) and [here](https://github.com/ornladios/ADIOS2/issues/2689).

**Comment by pordyna** [comment]
@franzpoeschel I will try setting the queue limit, I can see how that could be problematic, especially when writing every other step

**Comment by pordyna** [comment]
@franzpoeschel So setting the queue limit to 1 didn't help. It looks like the job didn't use all of the available host memory 
```bash
seff 3493723

Job ID: 3493723
Cluster: hemera
User/Group: ordyna35/fwt
State: FAILED (exit code 139)
Nodes: 1
Cores per node: 24
CPU Utilized: 00:15:24
CPU Efficiency: 14.86% of 01:43:36 core-walltime
Job Wall-clock time: 00:04:19
Memory Utilized: 249.11 GB
Memory Efficiency: 67.48% of 369.14 GB
```
though maybe it was trying to allocate more so I will try reducing the simulation size.

**Comment by pordyna** [comment]
@franzpoeschel Ok this is definitely a memory issue I did reduce the simulation size and I was able to process one step but I run out of memory on the reader side on the second one. I also ssh to the simulating gpu node  and looked on the memory consumption with htop. It got pretty close to 100% (with the much smaller setup). So I guess this answers my question, unless there are some other memory optimization tweaks that I don't know about.

**Comment by pordyna** [comment]
Another question, would setting `--openPMD.dataPreparationStrategy hdf5` help?

**Comment by franzpoeschel** [comment]
Ok, that's good to know.
I should note that the SST engine in ADIOS2 with the `QueueLimit` parameter set to `1` should not use more memory than the `BP` engine. I don't know exactly how readers and writers were scheduled in your workflow, but it is very likely that the same configuration with file output should run into memory issues, too.

By using `--openPMD.dataPreparationStrategy hdf5`, you should be able to trade some runtime for a lower memory usage, yes.

**Comment by pordyna** [comment]
Ok, I will try running it with a `BP` output if I don't get the error than maybe `QueueLimit` didn't propagate properly.

**Comment by franzpoeschel** [comment]
Do your readers occupy the same node or different ones? Given the state of the batch system on Hemera, I assume, it's different nodes, but just making sure.

**Comment by pordyna** [comment]
different one :)

**Comment by franzpoeschel** [comment]
Alright, then the memory requirements should be roughly equal

**Comment by pordyna** [comment]
hey @franzpoeschel, I did try changing the backend to `bp`  but the simulation didn't crush.  Memory usage also looks reasonable. 
```
Memory Utilized: 263.22 GB
Memory Efficiency: 71.31% of 369.14 GB
```

This is how I tried setting the queue limit before:

**Comment by franzpoeschel** [comment]
No, those parameters look fine. I am currently discussing a similar issue with the ADIOS2 team and I have found some places in our ADIOS2 backend where return statuses should be checked but aren't. This would make the error message that you are seeing more precise, but not solve the issue.
I'm pretty sure we are looking at some low-level failure inside the SST engine here and I can remember having observed errors in the past where streaming failed despite memory bounds not being reached, but lowering the data amount "solved" the issue.
Two options that I see:

1. Either, this is just a limitation of the WAN data transport and we should focus on getting the RDMA transport running on Hemera. But I'm not sure that this would really help, since the error occurs at the control transport level.
2. Or, this is just a bug and we should forward it to the ADIOS2 devs.

Either way, I think I should (1) fix the bugs mentioned above in our ADIOS2 backend and (2) find a reproducer for the issue and share that with the ADIOS2 devs.

**Comment by eisenhauer** [comment]
Hi all.  I agree that this is likely some low-level failure, but I think this is telling: "ERROR: EndStep() is called without a successful BeginStep()".  This implies that the root of the attribute problem is an unsuccessful BeginStep() resulting in no metadata being loaded. If I were guessing, I'd say that this reader-side problem is happening simply because SST has noticed the writer side failure and returning an error on BeginStep().   If that's right, we should focus on the writer-side failure.  Can ask the size of the reader cohort?  This may matter because our data planes act differently if there is a single reader rank.  They'll assume that that reader will want all the written data and "preload" it (send it to the reader along with the metadata, rather than just sending the metadata and waiting for the data to be requested).  You can turn this off by setting the engine parameter "SpeculativePreloadMode"  to "Off".  That may narrow things down further...

**Comment by pordyna** [comment]
Hi @eisenhauer, I was just trying things out and I had just one reader. I will try to to disable `SpeculativePreloadMode` and see if that changes something.

**Comment by pordyna** [comment]
@franzpoeschel @eisenhauer I think I have found my problem. 
```
[...]
 , \"BufferGrowthFactor\": \"1.1\"     \
 , \"InitialBufferSize\": \"36Gb\"     \
[...]
````
are not SST options. ADIOS documentation doesn't list them for SST. It looks like this buffer is still allocated but it is not used. So in the end the memory usage will be whatever ADIOS with SST actually needs + the 36Gb of an unused buffer. This happens on both writer and reader side. Removing those lines from writer and reader configurations drastically reduced memory usage on both sides.

**Comment by eisenhauer** [comment]
Interesting...  SST uses the BP3Serializer/Deserializer, but it uses it in a different way than the BP file engines.  I would have had to do some digging to see exactly what the interaction was for these parameters.   @JasonRuonanWang, any thoughts here? (Buffer preallocation is generally a big win for BP because starting small and using realloc() to increase the size when you do a new put() gets very expensive as the data gets large.)

**Comment by franzpoeschel** [comment]
>  It looks like this buffer is still allocated but it is not used.

I cannot confirm this observation. The following memory profiles are in order:
1. InitialBufferSize=5GB
2. InitialBufferSize=10GB
3. InitialBufferSize default
![Bildschirmfoto vom 2021-06-23 13-42-31](https://user-images.githubusercontent.com/14241876/123090875-f3438180-d428-11eb-8b55-8247e403587d.png)

Only the memory that I specified was used, no further memory was used.

I see that you set the memory to 36Gb. Is that your per-node or your per-process memory @pordyna? Notice that the InitialBufferSize must be the per-process memory. I guess the 36Gb are simply too much.

(Also notice how you really shouldn't use the default initial buffer size with SST as each step uses its own buffer in that engine).
