### ISSUE TITLE
PIConGPU and stable spack incompatible

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#3634]
Wang, Manhui and @cbontoiu trying to install PIConGPU with spack, they reported incompatibilities between spack and PIConGPU. Some PIConGPU versions require the dev branch of spack and other combinations failing always. 

```
spack "develop" +  picongpu "develop"  --> work
spack "develop" +  picongpu 0.5.0           --> fail
spack  v0.16.1     +  picongpu "develop"  --> fail
spack  v0.16.1     +  picongpu  0.5.0          --> fail
```

Spack should be integrated in our CI to be sure this workflow is working.

**Comment by BrianMarre** [comment]
@psychocoderHPC can be closed since the picongpu spack-recipe is no longer supported #4375
Note: spack may still be used for administration of dependencies, for example see [bash-devServer-hzdr](https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/etc/picongpu/bash-devServer-hzdr) together with the standard profile workflow.

**Comment by PrometheusPi** [comment]
We do not provide a spack setup anymore. (This does not mean that you do can not use spack for our dependencies - we just do not have the manpower to maintain a speck recipe.)
