### ISSUE TITLE
Particle Tracing

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3700]
Hello,
I noticed that the newest manual refers to the possibility to track a small number of particles from the charge density distribution. Would it be possible to have an example of this usage, please?

Thank you.
Cristian

**Comment by sbastrakov** [comment]
Hello @cbontoiu ,

So there is a number os ways to achieve it, which is more applicable depends on the use case.
Anyhow, you would need to separate those tracked particles either into a separate species (which may be otherwise same as normal) or define a particle filter which for each particle tells if it should be tracked. I assume you meant the latter and [`--openPMD.source` argument here](https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html#cfg-file)?

We can assist if you provide more information. I think it mostly comes to this: do you know in advance which particles you want to track? In a sense of fixed position, or what initial distribution they have. We do probe particles in some example setups with fixed positions, but they could be spawned otherwise as well. Or do you define to track or not as a condition for each particle.

**Comment by sbastrakov** [comment]
@cbontoiu perhaps the discussion in #3666 helps.

**Comment by cbontoiu** [comment]
Hello again on this topic,

I would state the thing I am looking for with respect to the first two images below. I have layers of Carbon atoms ionized three times and a laser coming from the left. Because I don't know how to loot to the (macro)particles, I can only plot the charge density.

![image](https://user-images.githubusercontent.com/7108691/129610627-080b9f45-b3f8-4a0a-b510-2d1a09bdeedf.png)
![image](https://user-images.githubusercontent.com/7108691/129610685-720ccb41-9f51-4c9e-8858-a27cf6331f75.png)

I suspect that electrons undergo acceleration but to prove it, apart from the energy histograms (with some manual filtering) I would need to show trajectories for a few electrons. Maybe they are only oscillating back and forth being caught in bunches and then being scattered.

I am looking for the possibility to create images like those given through the openPMD_viewer examples as for instance

![image](https://user-images.githubusercontent.com/7108691/129611122-fc8f1be5-ce10-4b4d-830d-abe0321bd6fe.png)

Now, all I have about Tracer Particles is from the documentation

![image](https://user-images.githubusercontent.com/7108691/129609690-78d07c5d-3051-417d-acee-0fc71b73386f.png)

and I have no clue how to implement more than setting the particleID in my ```speciesDefinition.param``` file

![image](https://user-images.githubusercontent.com/7108691/129609930-78091fba-e516-4a8c-bc81-c437f14b16f5.png)

Maybe @ax3l as author can help with a few lines of code required, please?

Many thanks,
Cristian

**Comment by ax3l** [comment]
Hi,

Yep so that section describes the same mechanism that @sbastrakov describes and linked above: if you want to avoid outputting all electrons and then filtering by their ID, you can either filter them (#3667) by ID from the beginning, e.g. every ID where `% 1000` is `0`, or you just add an extra species with tracer electrons. In case the tracer electron species density calculation is tricky, you could also deactivate their current deposition - that way they react like normal electrons but don't have any influence on the dynamics of the sim.

With regards to the openPMD-viewer example that you show: that example simply assumes you output a complete species and filter post-output on the IDs. That's also possible if you simulation is not too large, just remember to add an ID and otherwise keep everything as always.

A third way to proof acceleration without output of particles: plot phase spaces directly with our phase space plugin.

In the end it just comes down to how large your simulation is and how often you need the data.

**Comment by cbontoiu** [comment]
Hello and thank you all for the useful replies.

Running the standard LWFA example I get the error below. Anyone can help? Also I couldn't find in the manual what are: ```ux```, ```uy```, ```uz```and ```w```. I would appreciate any help.

![image](https://user-images.githubusercontent.com/7108691/129907841-1aec9f6e-35ab-4774-8e35-1230ca94e780.png)

**Comment by steindev** [comment]
Well 'ux' isn't part of PIConGPU output data. Probably it is the variable for the normalized particle momentum in x direction, i.e. u=gamma*beta. 

I would guess `w` is the the weighting.

**Comment by cbontoiu** [comment]
> Well 'ux' isn't part of PIConGPU output data. Probably it is the variable for the normalized particle momentum in x direction, i.e. u=gamma*beta.
> 
> I would guess `w` is the the weighting.

Hello Klaus and thank you for the reply. 

I found ```ux``` ... when loading the output in the ```openPMD``` viewer 

![image](https://user-images.githubusercontent.com/7108691/130226196-8487a15b-9184-472a-b87f-4ac3ca942151.png)
