### ISSUE TITLE
Energy Density : e_all_energyDensity

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3789]
Hello,

I am trying to make use of the field ``` 'e_all_energyDensity' ```. If I understand correctly, the manual says that within each mesh cell, this is the sum of the kinetic energies divided by the cell volume. That is all particles that happen to be in a cell will have their kinetic energy added up and the result will be divided by the cell volume.

In the figure below, plotting ``` 'e_all_energyDensity' ``` shows a tiny region where this field has a maximum of about 0.7e+17 (I assume in Joule/m^3) 

![image](https://user-images.githubusercontent.com/7108691/133421527-aca93a09-3e0d-4130-aea0-2fe9a198e4c8.png)

and because my cell volume is ```CELL_VOLUME = 1.33504e-30 m^3``` I can multiply  ``` 'e_all_energyDensity' ``` by ```CELL_VOLUME```  to get the energy to about 1.0e-13 (I assume in Joule)

![image](https://user-images.githubusercontent.com/7108691/133422059-e6f8c847-507b-49be-af8c-717256fcf411.png)

This can then be divided by the electron charge ```e``` to get the energy in eV so I can finally say that the tiny electron bunch has an average kinetic energy of ~0.60 MeV.

![image](https://user-images.githubusercontent.com/7108691/133422456-4a5845eb-8144-4b70-922c-30acd5adefcd.png)

Is my reasoning right? 
Does the choice of particle per cell (6 PPC here) influence the result somehow, I mean do I have to use 6 in my conversions ?
Does it make a difference if I dump all particles or only probes, as it is the case here with 
```using ProbeEveryTwentiethCell = EveryNthCellImp l< mCT::UInt32 < 20, 20, 20 > >;``` ?

Many thanks for attention.
Cristian

**Comment by sbastrakov** [comment]
Hello @cbontoiu . All data we output is openPMD-annotated. So each field should have a `unitSI` attribute to convert them to a value in SI. Out of my head I do not know if your interpretation happen to match it in this case. However when working with PIConGPU output in general, it's best to not assume any normalization (as it depends on the internally used units) and use this metainformation to interpret the data,

Number of particles per cell should not matter for it in the SI system, as it is only the "resolution" of PIC method, and not a physical quantity like the distribution density.

**Comment by sbastrakov** [comment]
The second part of the question I do not quite understand. You are now only outputting the energy density for electrons (via prefix `e_`). So unless `ProbeEveryTwentiethCell ` is somehow used for electrons, it should have no influence on it at all? Sorry if i'm missing something

**Comment by cbontoiu** [comment]
About the second part of the question I realize now that the probes or particles dumped through the ```fileOutput.param``` are not related to the ```'e_all_energyDensity'```. This is my file

![image](https://user-images.githubusercontent.com/7108691/133428876-d2d292c4-8276-4b0d-bb55-4e1648d84953.png)

**Comment by cbontoiu** [comment]
About the metadata, I think this refers to the second field called ```info_Epe``` in the line below

![image](https://user-images.githubusercontent.com/7108691/133429173-29969d10-5517-41ef-a8e1-e6a87818b3c0.png)

but I don't know how to use it, so I dangerously convert like this

![image](https://user-images.githubusercontent.com/7108691/133429369-043d3ae6-d753-492d-b7b0-cd3f54e9cfd3.png)

where ```CA[16]``` is 1e-06 to convert the energy into MeV.

**Comment by sbastrakov** [comment]
Ah, originally I didn't realize you were using openPMD viewer and not reading "raw" data from our output. The viewer seems to internally use that `unitSI` before displaying the data to you. And so then your conversion from J/m^3 to MeV should be fine.

However, keep in mind I am no physicist. Does it look good to you @PrometheusPi  ?

**Comment by PrometheusPi** [comment]
@cbontoiu Please excuse the late replay. 
Regarding: 
> I am trying to make use of the field 'e_all_energyDensity'. If I understand correctly, the manual says that within each mesh cell, this is the sum of the kinetic energies divided by the cell volume. That is all particles that happen to be in a cell will have their kinetic energy added up and the result will be divided by the cell volume.

This it totally correct. I would just add, that since we are using macro-particles with a spatial shape, neighboring particles will also influence this sum over all particles. (see https://picongpu.readthedocs.io/en/latest/models/shapes.html for more details) 

Regarding:
> (1) In the figure below, plotting 'e_all_energyDensity' shows a tiny region where this field has a maximum of about 0.7e+17 (I assume in Joule/m^3)
(2) and because my cell volume is CELL_VOLUME = 1.33504e-30 m^3 I can multiply 'e_all_energyDensity' by CELL_VOLUME to get the energy to about 1.0e-13 (I assume in Joule)
(3) This can then be divided by the electron charge e to get the energy in eV so I can finally say that the tiny electron bunch has an average kinetic energy of ~0.60 MeV.
(4) Is my reasoning right?

To (1): as far as I understand your code in [your later comment](https://github.com/ComputationalRadiationPhysics/picongpu/issues/3789#issuecomment-919955589) you did not convert to SI units - thus your energy density is still in PIConGPU units. (Assuming you are using the openPMD-api) Perhaps this is defined in `CA[4]`- I do not know what this variable means.

To (2): If your previous result would have been in SI units, that step would be correct.  

To (3): (Assuming you where is SI units before.) No, the value is not an average value. The number you calculated is the total kinetic energy within the volume of a cell.  To convert this to an average energy of the electrons you need to dived that total energy per cell by the number of electrons per cell. This is however a dynamic quantity. I would recommend to use the charge density here. This would also allow you to avoid the multiplication with the cell volume and the division by the elementary charge (to convert from J to eV) .

To (4): your general reasoning is correct, but there were some minor errors.  

Regarding:
>Does the choice of particle per cell (6 PPC here) influence the result somehow, I mean do I have to use 6 in my conversions ?
Does it make a difference if I dump all particles or only probes, as it is the case here with
using ProbeEveryTwentiethCell = EveryNthCellImp l< mCT::UInt32 < 20, 20, 20 > >; ?

The numbers per cell that you initialize should not matter if the analysis is set up correctly. However, the number of electrons per cell (dynamic quantity) is essential for computing the average (please see "To (3)".)

**Comment by sbastrakov** [comment]
@PrometheusPi i thought the openPMD viewer always gives SI?

**Comment by cbontoiu** [comment]
@PrometheusPi  ```CA[4]``` is only a numeric conversion and equals ```1e15``` for time, that is I think in ```time = 2``` meaning femtosecond but for ```openPMD viewer``` time needs to be in seconds as ```time = 2e-15```. It shouldn't affect the results at all.

Thank you for your kind reply. I will read it carefully.
Kind reagrds

**Comment by PrometheusPi** [comment]
@sbastrakov You are right :+1: - I thought @cbontoiu  is using the openPMD-api and not the openPMD-viewer. (Is this correct @cbontoiu?) 

If you are using the  openPMD-viewer interface, my comment on "To (1):" can be ignored and your only error occurs at computing the average (see "To (3):").

**Comment by cbontoiu** [comment]
Yes, I always use ```openPMD viewer```.

**Comment by PrometheusPi** [comment]
Perfect :+1: - than the only issue I see is how you define "average" - but perhaps I misunderstand your goal here?

**Comment by cbontoiu** [comment]
As I understood the average is given by ```'e_all_energyDensity'``` itself with respect to a 3D mesh cell and I am happy with the concept. My problem was two fold:
- if the number I see is affected by the number of macroparticles per cell (PPC) and their shape;
- if the unit is Joule/m^3 or eV/m^3;
but you clarified this for me mentioning the SI units, always delivered by the ```openPMD``` viewer.

Thank you

**Comment by sbastrakov** [comment]
As I mentioned above, the number of macroparticles per cell and shape are merely "sampling resolution" of the PIC method. So they should not significantly affect the physical picture you see. If they do, it hints at either a mistake at interpreting the data, or that the method with chosen parameters is not well-applicable to the problem.

**Comment by PrometheusPi** [comment]
Okay, I thought you were interested in the average energy per real electron.

**Comment by PrometheusPi** [comment]
Thus the increase in energy density you are seeing between y=550nm and 650nm comes from the energy gain in the laser field. 
The energy density between y=420nm and 500nm might have two reasons: either there are just more particles as the back of the wake and thus the sum over particles produces a higher total energy, or you have energetic particles (injection) or both.

**Comment by cbontoiu** [comment]
Yes, so now I can safely state the energy gained by injected charge density cloud, and from the integration of this in volume I can infer the number of electrons captured and accelerated. 

![2021-09-17_10-30](https://user-images.githubusercontent.com/7108691/133760852-c27ff428-d4b0-40ff-a15b-5d4d8e2494cc.png)

**Comment by PrometheusPi** [comment]
An easier way to determine the "the number of electrons (captured)" would be to use the `e_chargeDensity`, do the same stabs as above (1)-(3) (but now dividing by charge converts charge density to number density) and than you now exactly how many electrons are in each PIC cell.

**Comment by PrometheusPi** [comment]
@cbontoiu What did you change between your second-to-last and last plot? (the color scale changed by 7-8 orders of magnitude).

**Comment by cbontoiu** [comment]
@PrometheusPi this last image can be compared to the last from the batch of three shown previously. The latter is in MeV and the former in eV, hence the orders of magnitude difference. However, they are from different simulations.

**Comment by cbontoiu** [comment]
> 
> 
> An easier way to determine the "the number of electrons (captured)" would be to use the `e_chargeDensity`, do the same steps as above (1)-(3) (but now dividing by charge converts charge density to number density) and than you now exactly how many electrons are in each PIC cell.

Yes, This is the usual way I do it. Not shown here.

**Comment by PrometheusPi** [comment]
@cbontoiuCould you please explain, what the issue with the 
>  the colour density plot 
is in detail? 

Why did you plot your energy density twice and with a 90° rotation?

**Comment by cbontoiu** [comment]
Hello @PrometheusPi and thank you for looking to this issue. The situation is like this. I have two 2D simulations for exactly the same setup: laser, target, ionization, particle per cell etc except for the mesh. More details are shown together with the colour plots provided. My problem is that I get different energy densities. 

The two colour plots with the y-axis vertical are directly from the ```openPMD viewer``` just to check the raw ```e_all_energyDensity```. Already, the growth of the peak value from ~7e16 [J/m^3] to ~ 8.5e16 [J/m^3] is of some concern.

The other two colour plots are my conversion to ```keV``` average energy after multiplying by ```CELL_VOLUME/e```. However in both case the energy histogram looks similar, which makes me think that my colour plots should be smoothen. I just wanted to check with you how can mesh impact the energy density.

**Comment by PrometheusPi** [comment]
@cbontoiu If you say, they are exactly the same, I assume you mean from the point of few of physical parameter setup (including laser parameters, density, etc.) not physically-equivalent that they should behave the same due to symmetry reasons, is this correct?

Assuming the previous assumption is correct: 
How do you initialize your particle distribution? 
Do you use [random](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/picongpu/param/particle.param#L135) our [quite](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/picongpu/param/particle.param#L153) start in your [initialization pipeline](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/picongpu/param/speciesInitialization.param#L42)?
One reason for different plasma dynamics despite the same global physics parameters might be that the initial random particle position when using [random](https://github.com/ComputationalRadiationPhysics/picongpu/blob/454a28efe6a6eb0fa1e0e97031ef2569a1ad313b/include/picongpu/param/particle.param#L135) start positions results in different global physics effects. Another could simply come from the non-commutability of float additions which becomes a source for randomness even more with parallel processing.  
Both cases would pinpoint to the fact that the system you are trying to simulate is intrinsically dynamic (at least at your resolution scale) and thus small changes might have a big effect. 

Could you provide a difference plot to estimate the effect. Ideally by something like
abs( sim_1_value - sim_2_value ) / abs(max(sim_1_value, sim_2_value) + epsilon)
with epsilon being a minimal value of certainty you think should be achieved.

If your system is intrinsically dynamic, only statical predictions are possible. Bt before you assume that, you could test whether increasing the ppc and resolution results in more stable predictions.

**Comment by cbontoiu** [comment]
Hell @PrometheusPi  and thank you so much for your reply. Your assumption is correct, I meant the setup. I don't use any symmetry, not even for x-direction though the laser is a plane wave and it is recommended to apply the x-symmetry. However I don't want to get the charge density cloud swapping sides; I mean what leave from max(x) shouldn't enter back from x = 0; 

Here is how I initialize the Carbon atoms in the ```speciesInitialization.param```, three times ionized and their released electrons

![image](https://user-images.githubusercontent.com/7108691/140954302-04440e1b-4c0a-4e26-b219-36ca4d007575.png)

with fragments from the ```particle.param```

![image](https://user-images.githubusercontent.com/7108691/140954643-68b6e481-8dc4-4134-b382-cab87062a7b7.png)
![image](https://user-images.githubusercontent.com/7108691/140954734-9f82b529-d638-4430-8ec5-a272bc7a6e30.png)
![image](https://user-images.githubusercontent.com/7108691/140955003-c192810e-97b1-4264-bee5-8eb993ecc5f5.png)

I will do the comparison with a larger PPC. For now I can say that my injected charge moves non relativistically as shown below. I am not sure if this complicates the stability of the results.

![image](https://user-images.githubusercontent.com/7108691/140959025-8f58c029-eded-40fe-9e5d-e8e189bb24b4.png)

**Comment by cbontoiu** [comment]
I have some results on this aspect. With the same mesh changing the PPC as 6,9,12 there is no difference on the histograms.
![image](https://user-images.githubusercontent.com/7108691/141521584-cc900d29-7b7d-4b82-bb86-0f16e41639bb.png)
There is however a difference on the colour density plot.
![image](https://user-images.githubusercontent.com/7108691/141522157-1be96029-103f-430b-8638-2e5f353725ff.png)
I can understand that with larger PPC the figures become more accurate and and converge, but I am not sure how to relate the colour plots to the histograms. Looking at the colours I can see that the injected bunch shows an energy spread in the range 0 - 100 keV at most, while there are some pixels going higher in energy. At the same time, the lower lines in the histograms (inside the bubble) show a sharp drop in the range ~75 - 100 keV and this is consistent. 

The problem is that the Counts for > 200 keV that is energy values which don't appear in the colour plots. Their colour bar refers to the whole simulation domain and it is not restricted to the bubble. The histograms are binned  in 1000 bins for a maximum energy of 1000 keV
![image](https://user-images.githubusercontent.com/7108691/141523416-a8c73052-4b48-460e-bb05-5953392d7f22.png)

I guess I need to reduce the number of bins and thus get rid of the high energy tail.
