### ISSUE TITLE
Laser pulse errors

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#3797]
Hello,

I have a problem with the laser pulse defined in the ```param``` file below.

[laser.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/7184576/laser.txt)

On the image below, there should be no negative X field for y > 85 nm but there is some error there. The image shows vectors here

![image](https://user-images.githubusercontent.com/7108691/133761738-2e5850ff-beea-4a19-8094-7b3237e5bb46.png)

but the error is visible in the Ex colour density plot below, though at another moment of time, this is about 10% of the peak laser field. It is as if I have a small prepulse in front of the main pulse. 

![ex](https://user-images.githubusercontent.com/7108691/133762549-45ecb77a-b704-4221-97e2-3a7be49e29f0.png)

Can this be due to the fact that I use 32-bit accuracy? Is there something wrong with the ```laser.param``` file?

Thank you,
Cristian

**Comment by PrometheusPi** [comment]
Hi @cbontoiu ,
as far as I understand your `laser.param`, you laser front is at a phase `\in [0,1)`:
```
RAMP_INIT / 2. * PULSE_LENGTH_SI * c / WAVE_LENGTH_SI = 
3. * 2.354820045 / 2. * 7.082581446e-17 * 2.9979e8 / 5e-8 =
1.4999
```
which is numerically close enought to halfe a wavelength to not show the above field.

However, your `RAMP_INIT` is very small and thus the electric field witch is initially introduces is:
```
exp(-0.5 (3. * 2.354820045 / 2.)^2) = 
0.002
```
still quite large. 

I would propose the following checks:
 - set RAMP_INIT to at least 10 and see whether the artifacts vanish
 - If not, try again without particles and see if the effect is perhaps coming from a reflection/feedback from the particles

I hope this helped. If you have any further questions, please feel free to ask.

**Comment by sbastrakov** [comment]
To add up to @PrometheusPi 's answer. It is indeed recommended to start off the laser smoothly, so that its value and itime-derivative are close to 0 at `t=0`. Doing otherwise would often introduce spurious waves and potentially numerical artifacts.

Generally, in the numerical media formed by the field solver in use, the values could propagate one cell per time step for the standard Yee solver due to the nature of its finite-difference scheme. However, with proper initialization this is not a problem by itself, as meaninful waves would still propagate with speed of light, or rather the "numerical speed of light" defined by the solver and Courant numbers

**Comment by cbontoiu** [comment]
Hello again and thank you. It is not clear to me what ```RAMP_INIT``` does but tuning the factor in front of ```* 2.354820045``` works like phasing. So instead of ```3``` I tested some values nearby as shown below

![image](https://user-images.githubusercontent.com/7108691/134002163-df0834c5-6f92-4f18-a83f-deaa9f2fc5b1.png)

An optimum is around ```2.8`` and I am happy with this. Factor of ```10``` switches the phase even worse than ```3``` as initally used.

![image](https://user-images.githubusercontent.com/7108691/134002854-e7cff6e4-e871-4cf4-b74f-05ca6e7c5a7e.png)

**Comment by PrometheusPi** [comment]
Great to hear that this numeric optimization works for you @cbontoiu :+1:
