### ISSUE TITLE
openPMD density input via plugin during runtime

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#3960]
Currently, it is already possible to provide openPMD-flavored files for species `densityProfile` input within `density.param`.

It would improve usability and setup time majorly if specifying the path for the files was done via a plugin (via the `openPMD` plugin?) during runtime.

**Comment by sbastrakov** [comment]
I suggest the following change. One still defines a type for density-from-file in `density.param`, so that it acts like all other densities interface-wise in functors like `CreateDensity`. But this struct only has one member - a string that is a prefix for command line parameters. And all other current members become runtime as `--[plugin].[prefix].[name]`, following our standard naming for command-line parameters. Note that we still need these prefixes as one could have multiple densities from a file.
