### ISSUE TITLE
CUDA dependency of SliceFieldPrinter

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#3965]
Hello,

I am currently working on a new plugin which is based on the `SliceFieldPrinter` plugin and I was wondering, why [the docs](https://picongpu.readthedocs.io/en/latest/usage/plugins/sliceFieldPrinter.html#known-limitations) say that the `SliceFieldPrinter` plugin is depending on CUDA. When @steindev and I looked through [the files](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/include/picongpu/plugins/SliceFieldPrinter.hpp) we couldn't really find anything CUDA-dependent. But when @steindev tried to compile and run a simulation on his laptop without CUDA installed but with the plugin manually enabled in the `PluginController.hpp`, PIConGPU could compile with the plugin, but it crashed without any output. So the questions are:

Where does the SliceFieldPrinter plugin depend on CUDA?
Would it be possible to bypass this dependency?

PS: Additionally we briefly looked at the `PositionsParticles` plugin and we are not sure, why it depends on CUDA either

**Comment by sbastrakov** [comment]
For the slice field printer, I think the reason is the plugin uses cuSTL. I am not 100% sure what goes wrong there and if it's supposed to work with CUDA. However I did a revision of plugin dependencies not that long ago and apparently left it cuda-only.

The positions particles one is parallelized in a naive CUDA way, assuming cupla block size equals supercell size. This is just not a portable way. Replacing with our normal lockstep style loop should solve it

**Comment by sbastrakov** [comment]
The plugin was removed, closing the issue.
