### ISSUE TITLE
Not all CPU cores are used with OpenMP backend

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/picongpu#4012]
@sbastrakov 

Your instincts serve you well.  The LaserWakefield simulation runs to completion now.  I have attached the 1.cfg file and the picongpu.dependency and picongpu.profile scripts I used to set up and run the simulation.

I am running the simulation on a CPU with 16 hyper-threaded cores.  A total of 2 out of 32 available processing cores are used to process the simulation, which runs for an hour and 45 minutes to finish.  Can you tell me if there is a simple way to task all available cores?  Let me know if that should be opened in a separate post.

Thanks,
Kim 

[dependency and profile scripts 4 March 2022.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8184188/dependency.and.profile.scripts.4.March.2022.tar.gz)
 used to install and run the simulation.

_Originally posted by @kimjohn1 in https://github.com/ComputationalRadiationPhysics/picongpu/issues/4004#issuecomment-1058945857_

**Comment by sbastrakov** [comment]
According to my understanding, by default the OpenMP backend is using all cores exposed to this application. So in case only 2 cores are used, I would first look into if only those 2 are exposed due to your environment variables or other settings.

To investigate, I suggest the following. Take your existing profile and other environment settings (number of openmp threads, affinity) that you used for PIConGPU runs. Make a simple C++ application using native OpenMP that simply prints result of `omp_get_max_threads()` and starts an `#omp parallel for` section with default settings to then print how many threads are created. E.g. you could use [this](https://www.geeksforgeeks.org/openmp-hello-world-program/) as base. Edit: in case you are familiar with OpenMP environment variables, you could simply query the respective values after loading your PIConGPU profile.

This way, we will check if OpenMP resources are properly exposed to a simple native OpenMP application, within the environment you use for PIConGPU. If that case works fine, we will investigate what goes wrong on our side. In case it doesn't, the issue is in your environment.

**Comment by kimjohn1** [comment]
@sbastrakov 

Thanks for the suggestion!  I have attempted to carry it out as best I could.  

For a comparison base, I checked to see if there was an OpenMP num_threads variable already set, by opening a terminal and running `echo $OMP_NUM_THREADS`.  I observed there was no response.  I then ran the picongpu.profile script, verified that OMP_NUM_THREADS was still not set, then ran the LaserWakefield simulation to completion.  I found that it took 1 hour and 22 minutes to complete.

I looked up the link you provided, then compiled and ran the `hello.cpp` OpenMP program.  I learned that I needed to implement an OMP_NUM_THREADS environment variable to get it to work, so I added 
`export OMP_NUM_THREADS=8` to the picongpu.profile, ran the profile and verified that the variable was set using 
`echo $OMP_NUM_THREADS`, which reported 8.  I then ran the hello OpenMP program and saw that it worked.  I then ran the LaserWakefield simulation and found that it took 1 hour,  21 minutes.  I ran 
`echo $OMP_NUM_THREADS` after LaserWakefield was finished to see if the setting had been altered.  It still reported 8.

It appears that all available CPU cores are not being fully engaged during a PIConGPU simulation running on a PC with a multi-core CPU.  Are there other OpenMP environment variables that I should implement in my .profile script to enable use of the OMP_NUM_THREADS variable when PIConGPU runs a simulation?  Also, does the PIC_BACKEND selection contain OpenMP settings that affect the use of OpenMP?

A little more info on the testing:
I ran this test 5 times on the lab computer that has a 4 core CPU and 6 times on the computer that has 16 cores, using different selections for OMP_NUM_THREADS.  I used both System Monitor and HTOP to observe what CPU cores were being tasked.  All of the tests indicated that 2 CPU cores were being tasked during the simulation, with one exception.  I noted on both computers that if I set `export OMP_NUM_THREADS=1`, then just one CPU core was used during execution and the total run time increased by 15 minutes (ex; run time was 1 hour 36 minutes for the lab computer with 4 core CPU, an increase of 17% if I did the math right).  I have attached the modified picongpu.profile script, the OpenMP test program, the output file generated during the final test using `export OMP_NUM_THREADS=8` running on the computer with a 4 core, dual threaded CPU, and a couple of the screenshots showing that 2 cores were being tasked at near 100%.

Kim

[testing.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8191605/testing.zip)

**Comment by kimjohn1** [comment]
@sbastrakov 

The Read The Docs, Installation, Dependencies section describes installing openMPI using the apt package manager:
`sudo apt-get install libopenmpi-dev`
Then the instruction indicates setting an environment variable:
`export MPI_ROOT=<MPI_INSTALL>`

I have not set that variable since my installation is on a single desktop PC and seemed unlikely to use MPI.  Does PIConGPU use MPI to enable or facilitate multi-core (thread based) parallelism?  If MPI_ROOT needs to be set even when PIConGPU is installed on a PC, what should it be set to, after a package manager installation?

Kim

**Comment by psychocoderHPC** [comment]
@kimjohn1 

If PIConGPU is compiling without `MPI_ROOT` all is fine. `MPI_ROOT` is only a helper to point to MPI. Normally CMake is fining MPI additionally via checking where `mpicc` is installed to.

MPI is used to connect boundaries if you e.g. run on a single GPU and use periodic boundary conditions. With multi GPU it is used to communicate the local guard/helo cells between GPUs. If you run PIConGPU with CPUs MPI is used to communicate the boundaries too. 

Since this issue is handling `OMP_NUM_THREADS` I assume the simulation is running and there is not need to set `MPI_ROOT`

**Comment by kimjohn1** [comment]
@psychocoderHPC 

All sounds good there.

Right now I am setting `PIC_BACKEND="omp2b:native"`.  Read The Docs: Usage, Basics indicates that there are other settings for PIC_BACKEND, but I have not found documentation that describes the various settings, and possible options.  Taking a guess at another option for omp2b, I set  `PIC_BACKEND="omp2b:8"` and get a compile error indicating that `Could NOT find MPI_CXX (missing: MPI_CXX_WORKS)`.  I've attached the error reports for reference.  I get the same compile error if I set `PIC_BACKEND="threads:8"`.  Are these meaningful error reports or am I just using invalid settings for PIC_BACKEND?

Is there a print statement that I could insert somewhere that would indicate how many threads are being commanded to be used?

Kim

[error_reports_with_threads:8.tar.gz](https://github.com/ComputationalRadiationPhysics/picongpu/files/8325267/error_reports_with_threads.8.tar.gz)

**Comment by psychocoderHPC** [comment]
You are right we missed documenting it for `pic-build`, `pic-build` is internally using `pic-create` where we have a short documentation for this option https://picongpu.readthedocs.io/en/0.6.0/usage/basics.html?highlight=march#pic-configure

After the `:` you can set the architecture. For an old AMD Bulldozer architecture, it is e.g. `bdver1`. This option will be passed as `-match=bdver1` to the compiler. To build explicitly for an new AMD CPU with Zen3 architecture you would use `PIC_BACKEND="omp2b:znver3`
If you compile directly on the system where you run the application the option `native` is the best. The compiler will check which instruction set is available and build a binary explicitly for the CPU where you compile PIConGPU.
We added the possibility to build for other architectures because on HPC system the head node is not always hosting the same CPU as the compute nodes.

In your test `PIC_BACKEND="threads:8"` is not a valid option therefore make died during the compile of a small test application. `PIC_BACKEND="threads:i486"` would be valid if you like to target your old 486 CPU from before the year 2000 :-)

**Comment by kimjohn1** [comment]
@psychocoderHPC 

Excellent explanation.  I have test computers with CPUs:
* Intel I7 8650U
* AMD Ryzen Threadripper 1950X (Zen architecture)
* AMD Ryzen Embedded V1605B
* Intel I5-11600K (multiple GPU testbed - under construction)

All of these CPUs are multiple core with hyperthreading.  I'll stick with using `PIC_BACKEND="omp2b:native"` for testing with CPU only, unless you think I should use something else.

Moving on.  I note that Read The Docs, Installation, picongpu.profile, 'Your Workstation' has no openMP related system variables being set.  Should there be a set of variables in 'Your Workstation' that set up an openMP operating environment?

Kim

**Comment by psychocoderHPC** [comment]
Good point the documentation should be extended. I opened an issue that we do not forget about it #4031

**Comment by j-stephan** [comment]
I'm hitting this bug, too. On a system with 80 available cores, only two are being used despite `OMP_NUM_THREADS` being set to 80. This seems to be a MPI-related problem; when I run the picongpu executable directly (without `mpirun`), all cores are used.

**Comment by sbastrakov** [comment]
Oh, thanks for reporting. It could be a problem on a system side, but could also be something we affect in [this script](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/cpuNumaStarter.sh) that normally wraps all calls on CPUs (i.e. it is used in all or most profiles for CPUs).

**Comment by psychocoderHPC** [comment]
> This seems to be a MPI-related problem; when I run the picongpu executable directly (without `mpirun`), all cores are used.

In this case I assume that MPI is already pinning threads you need to disable thread pinning in this case. Depending on the MPI flavor the option `--bind-to none` should disable MPI pinning.

@sbastrakov I think @jan is not using the script to pin host threads.

**Comment by sbastrakov** [comment]
Oh we also do `--bind-to none` in some places, e.g. for the `defq` partition on Hemera.
Ah true, with directly launching PIConGPU the script won't be used, it's only when launching through `tbg`.

**Comment by j-stephan** [comment]
Yup, it seems that the `--bind-to none` was the missing factor. The performance looks much better now.

**Comment by kimjohn1** [comment]
@sbastrakov 

Sounds exciting. Tell me how I can implement this fix in my Desktop PC installation of PIConGPU.  I have been using the tbg execution step from Usage, Basics, Step-by-Step, 3
`tbg -s bash -c etc/picongpu/1.cfg -t etc/picongpu/bash/mpiexec.tpl $SCRATCH/runs/lwfa_001`

What do I need to change?
Kim

**Comment by sbastrakov** [comment]
Hello @kimjohn1 ,

The `etc/picongpu/bash/mpiexec.tpl` file you used is located in the directory where you complie PIConGPU. When this directory was created with `pic-create`, the file was copied from the code base [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/bash/mpiexec.tpl). The line that actually launches PIConGPU is [this one](https://github.com/ComputationalRadiationPhysics/picongpu/blob/6ebd97ab5cb5690e94e3d8f6c30ada644ad3f925/etc/picongpu/bash/mpiexec.tpl#L60).

A user could adjust the `.tpl` file when needed. So what you could try to do is to edit (or make a copy and then edit) that file in your directory (if you edit at the repository, would need to make another setup with `pic-create`) and re-run, no recompilation is needed. I would suggest trying to change two things:

- add `--bind-to none` to the `mpiexec` call
- wrap the PIConGPU call in `!TBG_dstPath/tbg/cpuNumaStarter.sh`

These may make sense separately or together, I guess it's easier to just try all combinations. For an example please see [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/etc/picongpu/hemera-hzdr/defq.tpl#L108-L109) and nevermind the other differences from your .tpl file.

**Comment by kimjohn1** [comment]
@sbastrakov 

I tried both of your suggestions.  Adding `--bind-to none` to 
`src/picongpu/etc/picongpu/bash/mpiexec.tpl` resulted in all available cores being engaged when `PIC_BACKEND="omp2b:native"` is used.  Huzzah!

I removed `--bind-to none` and replaced  `!TBG_dstPath/tbg/openib.conf` with
`!TBG_dstPath/tbg/cpuNumaStarter.sh`.  That had no effect, and the LaseWakefield simulation executed on 2 cores as described in the original post.

I put `!TBG_dstPath/tbg/openib.conf` back in its original spot and moved `!TBG_dstPath/tbg/cpuNumaStarter.sh` to just prior to `!TBG_dstPath/input/bin/picongpu`.  That resulted in all available cores being engaged when `PIC_BACKEND="omp2b:native"`.  Again, Huzzah!

I did not test having both `--bind-to none` and  `!TBG_dstPath/tbg/cpuNumaStarter.sh` in `src/picongpu/etc/picongpu/bash/mpiexec.tpl`.  It seemed pointless since either change was driving all available cores at or near 100%.

For a bit of a regression test, I left the changes in and ran with `PIC_BACKEND="cuda:86"` on my lab computer equipped with an RTX 3060 GPU.  The GPU was engaged as expected during the LaserWakefield simulation runs.  One CPU core was engaged.  I presume that is the normal expectation.

Pending a decision to make a code change of some kind for a systemic fix, we could close this issue.  Thanks for the patient and energetic response that it took to track this one down.

Kim

**Comment by sbastrakov** [comment]
Glad it can use all cores now!

We definitely need to extend docs on CPU utilization as suggested by issue #4031 , I just self-assigned it

**Comment by kimjohn1** [comment]
@sbastrakov 

Correction to my report; Reviewing my notes, I find that I did not conduct a test with `!TBG_dstPath/tbg/cpuNumaStarter.sh` in `src/picongpu/etc/picongpu/bash/mpiexec.tpl` without ` --bind-to none` in there.

I ran a test with that configuration just now and find that only 2 cores are engaged during execution.  So the conclusion of my little series of tests is that including `--bind-to none` results in engaging all cores.  including `!TBG_dstPath/tbg/cpuNumaStarter.sh` (without `--bind-to none` present) does not.

I apologize for my incorrect initial report.

Still glad with the successful fix!

Kim

**Comment by sbastrakov** [comment]
Thanks for testing @kimjohn1 . So now i think we can consider this issue resolved and i'm closing it. Feel free to reopen if needed.

We made another issue to extend the CPU documentation #4031 and I now provided PR #4039 to try and fix it, your input is welcome there.

**Comment by kimjohn1** [comment]
I agree the issue is resolved.  Excellent job finding the problem and
identifying a resolution!

Thanks,
Kim
