### ISSUE TITLE
suggestion for writting data

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4051]
Hello,

I was surprised to find out that my computational memory limits for a given model can be extended if I run the model more times and ask for less data to be written. Example for a model:

My limit for the local machine is 

- ```10``` macroparticles per cell and ```0.115 nm``` mesh size if I ask for: electric field, magnetic field, particles, energy density, energy histogram and charge density to be written all together in a single output directory;

and becomes

- ```16``` macroparticles per cell and ```0.105 nm``` mesh size if I ask for: 

1. electric field, magnetic field;
2. particles;
3. energy density, energy histogram;
4. charge density;

So, the disadvantage is that I need to run the same model 4 times and I get 4 directories with data, which I will need to use when merging information but the gain is higher resolution of results. There is also the ```memory.param``` file paying a role here. For me it looks like this:
![image](https://user-images.githubusercontent.com/7108691/162635558-63eca3e6-b9f5-4418-8d09-da0e7ea1fe9d.png)

The **suggestion**:
Don`t you want to work on kind of multi-threaded algorithm for buffering the data that needs to be written such that we could achieve this kind of modularization of the output in a single simulation at the expense of longer simulation time and maybe larger number of files?

**Comment by sbastrakov** [comment]
Hello @cbontoiu , thanks for your feedback.

We actually do try to keep a small amount of data output "slots" are reuse them for different kinds of output. So in principle the amount of extra memory required for output should **not** scale with number of output fields. Apparently, something like that still happens for your use case. Could you attach extra information:

- Your full set of `.param` files and `.cfg` files used for the first "full output" scenario and the second 4 separate runs
- If you have a log of the failing run with e.g. "full output" scenario with 16 macroparticles per cell - so basically what you would like to do, but it doesn't work
- What hardware and memory size do you have, also on host side

**Comment by cbontoiu** [comment]
Hi @sbastrakov 
Thank you for your quick reply. In this case, it meeans that I don't fully use the ```memory``` scaling option (see the image above) because I don't understand how it works. However I acknowledge impact of those parameters on performance and memory limitations. I tried a new run with 
![image](https://user-images.githubusercontent.com/7108691/162699520-d3cbc02c-6ec4-497d-a8f5-3b0738ba4e12.png)
and ```PPC = 15```, mesh size: ```0.105 nm``` asking for 
![image](https://user-images.githubusercontent.com/7108691/162699816-226a3a14-a51c-4de6-aab2-ae1a0c04ff05.png)
and it failed. Here is the input folder with all data required:

[graphene-graded-layers-2D.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8462521/graphene-graded-layers-2D.zip)

and the failure message:

```initialization time:  5sec 573msec = 5.573 sec
  0 % =        0 | time elapsed:       1min 18sec 589msec | avg time per step:   0msec
  4 % =     2052 | time elapsed:      17min 34sec 521msec | avg time per step: 322msec
  9 % =     4104 | time elapsed:      35min 10sec 804msec | avg time per step: 323msec
--------------------------------------------------------------------------
prterun noticed that process rank 1 with PID 0 on node kubuntu exited on signal 9 (Killed).
```

And these are my machine specifications (2 GPUs in SLI):

![image](https://user-images.githubusercontent.com/7108691/162699934-d52cfa27-14b9-4db6-910a-f2f1cf0b040b.png)
![image](https://user-images.githubusercontent.com/7108691/162700041-bb62419e-9e3a-40a2-9707-02962b7259b3.png)

The commands to run were:

```
conda deactivate && source $HOME/src/spack/share/spack/setup-env.sh && spack load picongpu && spack load openpmd-api && export PIC_BACKEND="cuda:75" && export OMPI_MCA_io=^ompio
rm -r .build/ && pic-build &> out_log.txt && tbg -s bash -c etc/picongpu/runConfiguration.cfg -t etc/picongpu/bash/mpiexec.tpl /media/quasar/RawDataDisk1/PICONGPU/picongpu-0.6.0/OUT_LAYERS-GRAPHENE-2D/LAYERS-GRAPHENE-2D_ION_3_XY[nm]_1500_1500_WL[nm]_100.0_I[Wcm-2]_1.0e+21_A0_2.70_Dt[fs]_1.00_w0[nm]_500_f0[nm]_200_pol_LX_msh_14272_14272_ppc_15_un29b_run_01_e
```

**Comment by psychocoderHPC** [comment]
Its sounds like your memory limitations is based on the host memory. If you write all derived fields, particles and normal fields (electric field, magnetic field, particles, energy density, ...) together within one IO step than you need all on host side at least the memory of the resulting file, mostly more. If you run the simulation 4 times and only select few files you need less host memory.
You can avoid rerunning the simulation with a different setting if you use `--openPMD.source` and use the openPMD output as multi plugin https://picongpu.readthedocs.io/en/0.6.0/usage/plugins/openPMD.html#cfg-file (please scroll down to the `Note box`. 
Multi plugin means nothing else than that you can define all parameters multiple times on the command line or in the cfg. PIConGPU will handle each instance of the multi plugin as an independent plugin, this means the output will go in a separate file you must specify. The memory footprint should be some same as you need if you run the simulation 4 times if you group your IO into for multi plugin instances. Please run `./picongpu --help` to see all options you have for `--openPMD.source` because the possible values depends on your input set and defined species.

```
--openPMD.period 200 --openPMD.ext bp --openPMD.source 'species_all' --openPMD.file particles
--openPMD.period 200 --openPMD.ext bp --openPMD.source 'e_all_chargeDensity,e_all_energyDensity' --openPMD.file derivedFields
--openPMD.period 200 --openPMD.ext bp --openPMD.source 'E,B' --openPMD.file fields
```

**Comment by sbastrakov** [comment]
Regarding, the "memory scaling option" you mentined, if you meant `DIR_SCALING_FACTOR` it is not related to your issue, changing it should have no effect in your case. Sorry for confusing wording in my reply.

Thanks for providing the data, I am looking into it now.

**Comment by sbastrakov** [comment]
I agree with @psychocoderHPC that it may be that the issue comes from host memory, not device memory.

@cbontoiu  From the images you provided, the system should have enough host memory, but could it be that your job did not fully allocate it? I am not familiar with your system, but for example it could be that there is some amount allocated by default and you need to explicitly put a parameter somewhere to get more. With your use mode, I imagine you should try to take all available host memory for your job and use it exclusively (so that no other users run jobs there at the same time as you)

**Comment by cbontoiu** [comment]
@sbastrakov I don't touch the computer while heavy ```PIConGPU``` simulations run so most of the resources should have been allocated. I don't think my OS or GPUs limit the memory allocated to a given process and if they do, I don't have a clue where to look for.

**Comment by sbastrakov** [comment]
Okay, then i have no explanation so far. For your grid size 14272 x 14272 x 1 the stored-in-simuation grid data should actually be quite small relative to your hardware: about 7.3 GB for E + B + J, and each scalar field output like charge density should be only about 0.8 GB. For particles it's harder to say, but you can get the actual number of macroparticles in simulation by adding `--e_macroParticlesCount.period 100 --C_macroParticlesCount.period 100`.

Perhaps we could get some insight to how memory is allocated internally by re-building PIConGPU in [debug mode](https://picongpu.readthedocs.io/en/latest/dev/debugging.html) using `pic-build -c "-DPIC_VERBOSE=127 -DPMACC_VERBOSE=127 -DPMACC_BLOCKING_KERNEL=ON -DCUPLA_STREAM_ASYNC_ENABLE=OFF"` and rerunning the failing job with redirecting stdout output to a file. You do not need to run it for very long, just a couple of your output periods (or it even crashes sooner, which is okay for this purpose). Please also add particle counter flags from the previous paragraph and post values from those files. The run will produce a lot of text output due to verbose settings, please attach the resulting file.

**Comment by sbastrakov** [comment]
Oh, also as a simplistic but useful way to get extra information, you could also just use any "normal" utility of your operating system to check CPU memory usage during the run.

**Comment by cbontoiu** [comment]
Hello again and thanks for your helpful input. For the memory usage in the compilation phase I have
![image](https://user-images.githubusercontent.com/7108691/162728850-3c2125f7-f179-4e14-98f2-ca51ad083dec.png)
but execution failed to start because of mistakes in the ```.cfg``` file

I guess there can be only one ```TBG_openPMD``` plugin and i need to concatenate my thee plugins. also note that I added the ```fieldAnsorber.pml``` only to the fields.

![image](https://user-images.githubusercontent.com/7108691/162729225-838655c7-e028-41eb-8876-edaef18e73a7.png)

Below is the text of my ```.cfg``` file. How would you arrange it to convey all requirements listed but also be syntactically correct?

```
TBG_wallTime="1000:00:00"

TBG_devices_x=1
TBG_devices_y=2
TBG_devices_z=1

TBG_gridSize="14272 14272 1"
TBG_steps="41052"
TBG_periodic="--periodic 0 0 1"

# OUTPUT SNAPSHOTS ------------------------------------
source /home/quasar/PIC_INPUT/PICONGPU/picongpu-0.6.0/INPUT_LAYERS-GRAPHENE-2D/graphene-graded-layers-2D/outSteps.sh
TBG_plugin_period=$stps

# DATA ------------------------------------------
TBG_openPMD_particles = "--openPMD.period !TBG_plugin_period --openPMD.source 'Electrons' --openPMD.file particlesData --openPMD.ext bp"
TBG_openPMD_fields    = "--openPMD.period !TBG_plugin_period --openPMD.source 'E,B,J' --openPMD.file fieldsData --openPMD.ext bp --fieldAbsorber pml"
TBG_openPMD_densities = "--openPMD.period !TBG_plugin_period --openPMD.source 'e_all_chargeDensity,e_all_energyDensity' --openPMD.file densitiesData --openPMD.ext bp"

# HISTOGRAMS OF PARTICLE ENERGY IN [keV] -------------
TBG_e_All_energy_histogram = "--e_energyHistogram.period !TBG_plugin_period --e_energyHistogram.binCount 100 --e_energyHistogram.minEnergy 0.00 --e_energyHistogram.maxEnergy 10000.00 --e_energyHistogram.filter all"
TBG_e_1B_energy_histogram  = "--e_energyHistogram.period !TBG_plugin_period --e_energyHistogram.binCount 100 --e_energyHistogram.minEnergy 0.00 --e_energyHistogram.maxEnergy 10000.00 --e_energyHistogram.filter Bubble1"

# PLUGINS --------------------------------------------
TBG_plugins="!TBG_e_All_energy_histogram !TBG_e_1B_energy_histogram TBG_openPMD_particles !TBG_openPMD_fields TBG_openPMD_densities"

TBG_deviceDist="!TBG_devices_x !TBG_devices_y !TBG_devices_z"

TBG_programParams="-d !TBG_deviceDist -g !TBG_gridSize -s !TBG_steps !TBG_periodic !TBG_plugins --versionOnce"

TBG_tasks="$(( TBG_devices_x * TBG_devices_y * TBG_devices_z ))"

"$TBG_cfgPath"/submitAction.sh

```

**Comment by sbastrakov** [comment]
@cbontoiu i believe you forgot `!` before `TBG_openPMD_densities` when defining `TBG_plugins`

**Comment by sbastrakov** [comment]
Oh, and also before `TBG_openPMD_particles`

**Comment by cbontoiu** [comment]
I corrected those but still get the error
![image](https://user-images.githubusercontent.com/7108691/162733154-415485cb-d328-4dfc-a3b6-cd5d3785c235.png)
It must be something inside one ore more of the ```DATA``` plugins syntax

**Comment by cbontoiu** [comment]
my ```fileOutput.param``` contains
![image](https://user-images.githubusercontent.com/7108691/162733352-99767ddc-ab2a-4998-b403-26c8d432bffa.png)
so all required data should be there.

**Comment by cbontoiu** [comment]
Solved. It is about the white space around "=" just after the plugin names.

**Comment by cbontoiu** [comment]
Now my problem is that I have in my ```speciesDefinition.param```
```
using VectorAllSpecies = MakeSeq_t< Electrons, Carbon, >;
```
and thus using in the ```.cfg``` file

```
--openPMD.source 'species_all' 
```

seems to dump particle data for the Carbon ions as well, at least I saw a related message in the verbose output:

![image](https://user-images.githubusercontent.com/7108691/162738380-3ab20f62-5aba-4400-8cee-3836eec33f66.png)

But neither

```
--openPMD.source 'Electrons' 
```
nor
```
--openPMD.source 'e' 
```
works, though my ```speciesDefinition.param``` declares
![image](https://user-images.githubusercontent.com/7108691/162738669-e36c6bbd-7119-490d-af7a-a261e8ef9a4d.png)

**Comment by sbastrakov** [comment]
`species_all` is all species you declared in the setup. To have a single species, please use the text name that you put when declaring it, for your setup should be `e_all`, `C_all`. Running help for PIConGPU after building it (`./bin/picongpu -h`), shows all available options for your setup.

**Comment by cbontoiu** [comment]
Unhandled exception of type 'St13runtime_error' with message 'openPMDWriter: unknown data source 'species_e'', terminating

**Comment by sbastrakov** [comment]
Oh sorry I gave a wrong flag.

It's actually `e_all` to get all derived fields for electrons, and `C_all` for carbon

**Comment by cbontoiu** [comment]
Hello again,

I have a model that failed at ~12%. In the archive attached there is ```build_log.txt``` which contains the output written during compilation and ```runtime_log.txt``` which contains the verbose output written at runtime. 

Please check if you can spot anything interesting. I cannot confirm that this model will work in four separate runs as described above but writing the ```openPMD``` plugins in a modular way didn't help here

![image](https://user-images.githubusercontent.com/7108691/162923372-4bb34e76-baa0-4189-b74e-096110f9348b.png)

The model is different than the first one submitted above, but similar in what concerns the number of cells (2.83e8 instead of 2.03e8) and with lower number of macroparticles per cell (12 instead of 16). 

[graphene-graded-layers-2D.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8471406/graphene-graded-layers-2D.zip)

**Comment by sbastrakov** [comment]
Thanks for the log. It appears reasonable in terms of how things are allocated. However from this log it is still unclear when and why the crash happens. I saw you redirected both streams to the file, but somehow only the terminate message got there and not the "reason". Did it happen to output something more, maybe on the screen or there is also a special file created for each job and some output goes there?

Since the device memory usage appears fine from this output, we again have to suspect host memory. Did you check host memory usage during the run (externally or just by having another terminal to same machine at same time)? As a simple test, you could make another identical run and check memory usage periodically during the run to see if e.g. it starts growing and at some point becomes too much.

This growing of host memory could be caused by default behavior of openPMD API with ADIOS2 backend. Some users faced it and we have workaround settinsg for it. However, that would likely require you to switch to more modern version of PIConGPU. So before getting into that work I think it's reasonable to see if host memory is indeed the issue with simple check as described in the previous paragraph.

**Comment by sbastrakov** [comment]
Oh, if we suspect openPMD API (which we do not know for sure yet), you could also try switching to the HDF5 backend. For that, (assuming your openPMD API installation has both HDF5 and ADIOS) no need to recompile, simply replace `--openPMD.ext bp` with `--openPMD.ext h5` in multiple places of your `.cfg` file.

**Comment by cbontoiu** [comment]
@sbastrakov I didn't look at the memory usage on the system. I am afraid that in this case, the model was using all resources and the computation crashed when I wanted to do a plot in Jupyter Lab so adding a little bit of overhead. It is not clear if it will have crashed anyway because particles were still being produced through ionization and the size of the model keeps rising in my experience.

**Comment by cbontoiu** [comment]
On a fresh run, with a little lower number of cells that is 2.64e8 and PPC = 10, my memory usage looks like this around 7% of solution

![image](https://user-images.githubusercontent.com/7108691/162942307-f875b2ef-b989-466a-84ef-e38f5256a571.png)

and like this around 10% of the solution 

![image](https://user-images.githubusercontent.com/7108691/162942422-f99e0352-a815-4be2-bde4-89342bfb41b4.png)

**Comment by cbontoiu** [comment]
In the first snapshot the ```mount.ntfs``` can be an issue with 44.7% of the CPU. Data is stored on an external disk. But also, why are there two instances of ```picongpu```?

**Comment by sbastrakov** [comment]
> But also, why are there two instances of picongpu?

You are running 2 MPI processes on same node, both are picongpu. They run on separate GPUs so each will have 16 GB memory of a GPU, but share your host memory.

I am not sure why each process takes 40 GB of virtual memory if there is only 16 GB on a GPU, but maybe it's fine. After all, resident memory seems reasonable for both screenshots. The second screenshoot looks just healthy tbh, but please track further if those `%MEM` values will grow

**Comment by psychocoderHPC** [comment]
> I corrected those but still get the error ![image](https://user-images.githubusercontent.com/7108691/162733154-415485cb-d328-4dfc-a3b6-cd5d3785c235.png) It must be something inside one ore more of the `DATA` plugins syntax

spaces around the assignment operator in bash are not allowed. 

```
TBG_openPMD_partticles = "foo"
```
must be

```
TBG_openPMD_partticles="foo"
```

few other variables are wrong too

**Comment by cbontoiu** [comment]
This simulation crashed later but the error message is different. I barely hit the PrintScreen on time to find about the processes running. It looked like this (CPU usage 100.3% !)

![image](https://user-images.githubusercontent.com/7108691/162970363-591e76be-071b-4adc-a8e8-9b9999bb7a29.png)

The crash happened without me doing other things on the computer. This is the previous snapshot

![2022-04-12_13-44](https://user-images.githubusercontent.com/7108691/162970823-ce96f9eb-d347-4313-9785-501f418ebbbe.png)
