### ISSUE TITLE
particle openPMD output

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4055]
Hello, 

I found a potential problem with the ```openPMD``` output. I have a model which runs smoothly and in general I can easily get particle data with ```yp, xp = ts.get_particle( ['y', 'x'], species='e_all', iteration=..., plot=False);```. From time to time I get the following error:

![image](https://user-images.githubusercontent.com/7108691/163162197-c8789198-05f6-4809-a492-2abf13eddfa8.png)

which does not seem to be related to incomplete data written on the disk. I am familiar with the relevant error when trying to read data, while it is being written, namely 

![image](https://user-images.githubusercontent.com/7108691/163163048-9800e708-9071-4359-9c44-6960eda3d657.png)

but this new error started to appear after splitting the ```openPMD``` output in three parts:

```
# DATA ------------------------------------------
TBG_openPMD_particles="--openPMD.period !TBG_plugin_period --openPMD.source 'e_all' --openPMD.file particlesData --openPMD.ext bp"
TBG_openPMD_fields="--openPMD.period !TBG_plugin_period --openPMD.source 'E,B,J' --openPMD.file fieldsData --openPMD.ext bp --fieldAbsorber pml"
TBG_openPMD_densities="--openPMD.period !TBG_plugin_period --openPMD.source 'e_all_chargeDensity,e_all_energyDensity' --openPMD.file densitiesData --openPMD.ext bp"
```
I just want to make you aware of this exception in case you want to investigate it. Here is my model:

[graphene-graded-layers-2D.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/8480817/graphene-graded-layers-2D.zip)

**Comment by sbastrakov** [comment]
Hello @cbontoiu , thanks for your report.

Could you clarify, what does "from time to time" mean? E.g. are some time-iterations working fine and others in the same file produce this, or even same time-iteration sometimes works and sometimes doesn't?

**Comment by cbontoiu** [comment]
> Hello @cbontoiu , thanks for your report.
> 
> Coult you clarify, what does "from time to time" mean? E.g. are some time-iterations working fine and others in the same file produce this, or even same time-iteration sometimes works and sometimes doesn't?

Hi @sbastrakov 

Yes, it happens like this:

- I keep on loading data, say every 5 seconds thinking that at some point the set would be complete;
- A cycle of 3 data sets is finished and I still cannot plot particle data (the openPMD exception);
- A new cycle is written and by some random chance I get the particle data;
- At later times this repeats. 

It helps to add that when a simulation crashes while data is written out, it is normally required that the last incomplete set(s) is deleted to avoid the error shown in the second snapshot above. However, in such a situation, I kept deleting quite a few sets backward and got the error shown in the first snapshot again many times. This made me think that somehow the whole output was compromised, though I had able to get the first snapshots, just after the simulation started.

**Comment by sbastrakov** [comment]
So the openPMD model is essentially that there are independent time iterations and each time iteration has certain data sets like E, B, charge density, etc. I think a lot of tools assume the same data sets are available on all time iterations. Then it could indeed happen that incomplete time iterations cannot be reliably processed. 

Note that generally PIConGPU output is not synchronous to simulation, so that e.g. when time iteration 700 is completed it does not guarantee that the output for this iteration is fully written and ready to be used. At that time we gave the data for output to openPMD API and guaranteed we won't change it anymore, [and it may do its magic how it chooses to](https://openpmd-api.readthedocs.io/en/latest/usage/workflow.html). So it could take some further time until the files are written and ready to be used. I guess if PIConGPU crashes before some output is completed it would also interfere with said output. From your description I got an impression you rely on the synchnonicity that we do not generally have.
