### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4206]
Hello

I have a problem when reading many snapshots from a data series

![image](https://user-images.githubusercontent.com/7108691/178489688-7345c085-db41-48a8-98d8-12fdf72cb1e3.png)

This is the Python code used with the _openPMD Viewer,_ to load the series and read the charge density. 

```
ts = OpenPMDTimeSeries(DIR  + "/simOutput/openPMD/");  # load series for charge density  
for k in range(0, len(ITER)):       
     Ecd, info_Ecd = ts.get_field(iteration = ITER[k], field = 'e_all_chargeDensity', plot=False); 
```
[AllOscilationsDataImages.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/9092843/AllOscilationsDataImages.txt)

If you spot a problem, please let me know.
Thank you.

**Comment by BrianMarre** [comment]
First, this looks like a openPMD-viewer bug not a PIConGPU bug therefore it might be better to actually ask them, that said you might want to look into [this](https://stackoverflow.com/questions/68784048/oserror-errno-24-too-many-open-files-in-python-difficult-to-debug) and check as suggested here what the maximum number of open files on your system actually is.
If the number is lower than the number of unique entries in ITER, this might the cause an error since the openPMD-api and consequently the openPMD-reader tries to open all the files in its load queue at once. It might be necessary to use the openPMD-api directly to control how many files are opened at the same time and do your analysis in steps.

**Comment by cbontoiu** [comment]
@BrianMarre Very useful reply. Thank you!

I checked and obtained this
![image](https://user-images.githubusercontent.com/7108691/178530762-7c339a3a-b8e0-4c08-999c-f343e94534fb.png)
which indicates that it is rather a problem for the openPMD Viewer, since the limit of files is 1024 and my iterations are ~400.
