### ISSUE TITLE
Openpmd could not be successfully installed

### ISSUE THREAD

**Issue by summer7807** [ComputationalRadiationPhysics/picongpu#4207]
Hi guys：
I encountered the following error when installing openpmd on my terminal (Ubuntu 22.04). I don't know what the problem is. Can you give me some advice or guidance? Thank you.
![1](https://user-images.githubusercontent.com/74045515/178682486-c575a15a-b4ac-48c2-9bfd-9caae381128b.png)
![2](https://user-images.githubusercontent.com/74045515/178682508-0e83387b-1c22-41eb-a10a-dab6f034e018.png)
![3](https://user-images.githubusercontent.com/74045515/178682527-25c73e25-43cb-46df-903a-0eda314d6b9d.png)

**Comment by sbastrakov** [comment]
Hello @summer7807 ,

Please redirect your question to the [GitHub of openPMD API](https://github.com/openPMD/openPMD-api). We are not developers of it, but only users of that library (though there are some connections between the teams).

**Comment by summer7807** [comment]
ok  thanks

**Comment by psychocoderHPC** [comment]
@summer7807 As the error message is saying your openPMD is finding an installed version of HDF5. This version is most likely from your `apt` packages. The version openPMD found is compiled for serial usage only and is not supporting MPI.
Please check the openPMD documentation on how you can compile HDF5 for parallel usage on your own.

Note: I will close this issue because the reason why this error message happened is the wrong version of openPMD. If you still have issues to install openPMD please open an issue in the openPMD-api reposetory.

**Comment by summer7807** [comment]
ok  thank you
