### ISSUE TITLE
Radiation plugin: high frequency radiation "trees"

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4208]
The radiation plugin seems to produce spectra with minima that split over time and create a tree like structure. The effect is observable for frequencies much higher than the laser or plasma frequency.
It is currently unclear whether this is a numerical or real physical effect. 

The "trees" occurs for e.g. betatron radiation during LWFA or hosing during PWFA.

**Comment by Anton-Le** [comment]
Here's an example of such a spectrum radiated by the bunch:
![BunchSpectrumLineDoubling](https://user-images.githubusercontent.com/50339174/178716695-7604178d-1f4c-4532-a879-ef3b3447c732.png)

The bunch travelling at a relativistic gamma of 1900 impacts the background plasma at around 17000 time steps. Frequency ind rad/s (angular frequency).

**Comment by Anton-Le** [comment]
I have run the same set-up for comparison purposes with the **background plasma present** (same as in the post above)
![Spectrum_detector22_withbg](https://user-images.githubusercontent.com/50339174/179086456-63f44877-be71-4b3a-b55d-ac07c2f12c10.png)

and with the **background plasma removed**:
![Spectrum_detector22_nobg](https://user-images.githubusercontent.com/50339174/179087207-09916a08-6796-4736-afa5-3e854c1aace6.png)

Both plots show the same detector at an angle of ~0.08° to the propagation direction of the bunch.
While the upper limites of the log-colorscale are different, the overall structure of the spectrum prevails.

Hence the "trees" are unlikely to be related to the interaction with the background plasma.

**Comment by Anton-Le** [comment]
The following shows the spectrum for the same detector and the same simulation set-up (**no background plasma**) but with the default computational precision set to 64 bit in `precision.param`:
![Spectrum_detector22_nobg_64bit](https://user-images.githubusercontent.com/50339174/179394735-7b4e024c-b252-4bf5-8786-0d2d1203d9cd.png)


Since the pattern vanishes with a switch to higher precision I conclude that the 'tree' structure shown in the above posts is of numerical nature.

Additional information:
For the 64bit simulation the super-cell size had to be reduced to `4x8x4` from `8x8x4` otherwise the PIConGPU throws a compile-time error indicating that the shared memory is not sufficient for the selected combination of precision (64) and particle shape (PQS).

**Comment by sbastrakov** [comment]
Oh that is interesting. Do I remember correclty, that mixed `float_X`-`float_64` arithmetic is used there since the hackathon last summer? And there is only a handful of `float_X` in the kernel. Perhaps it's worth trying to replace `float_X` with `float_64` [in this file](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/include/picongpu/plugins/radiation/Radiation.kernel) and also [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c6d20f27dabfb122cbafcceed301c648294afba5/include/picongpu/plugins/radiation/amplitude.hpp#L133-L137) and still run PIConGPU with single precision. This way we will surely see if some of those internal radiation plugin variables cause this effect. Which seems very likely, but just to be sure it's the real cause here. And then one could investigate further and see which exact variable(s) cause this.

**Comment by Anton-Le** [comment]
Yes. Since the hackathon the implementation is mixed-precision. I'll try your suggestion.

**Comment by Anton-Le** [comment]
I tried to roll back a few changes to precision in `Radiation.kernel` for c6d20f27dabfb122cbafcceed301c648294afba5
and obtained the following spectrum with the default precision of 32 bit:

![Spectrum_detector22_nobg_3264bit_v1](https://user-images.githubusercontent.com/50339174/179701874-88e0bd52-c9ae-42f4-91f2-382d19e293e3.png)

(This is the same configuration as for plot No. 2 in https://github.com/ComputationalRadiationPhysics/picongpu/issues/4208#issuecomment-1184905660 ).

In contrast to the full 64bit run shown in the previous post we can observe a variation of the radiation spectrum in time and remnants of the periodic frequency doubling of the minima. But the characteristic structure is still vaguely present.
The diff of the kernel implementations is [Radkernel_diff.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/9139068/Radkernel_diff.txt)

The main difference being that `t_ret_s`, `particle_locationNow`, `omega` and `phase` have been changed to 64 bit, as they have an immediate effect on the phase computation and hence have the highest potential for rounding effects to affect the spectrum.

--EDIT--:
Additionally, in `amplitude.hpp` the type of `phase` as well as `sinValue, cosValue` has been changed from `float_X` to `float_64`.

**Comment by StevE-Ong** [comment]
Hi, sorry for intervene. 
Does this issue similar to https://github.com/ComputationalRadiationPhysics/picongpu/issues/3658#issuecomment-889179594 which higher harmonics are seen at higher frequencies?

**Comment by sbastrakov** [comment]
Oh you are right, it may be

**Comment by Anton-Le** [comment]
@StevE-Ong  That is very likely and @PrometheusPi has opened this issue in part because of the similarities.
Given the spectrum you observe I'll try a wider range of frequencies below the critical frequency (currently the radiation is computed for the range $[0.1, 7]\cdot\omega_c$ ).

What I'd like to figure out is which of the quantities above will have the largest effect on the spectrum and whether we can maintain the performance improvements of the mixed-precision implementation while preventing this numerical pattern.

**Comment by sbastrakov** [comment]
The following is perhaps unrelated to the issue, but still potentially worth having a look.

We calculate frequencies (on host for output and on device in-kernel) as `float_X` for all 3 of [linear](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4cf1739addad964f26135b8d188a35a474ae4c5f/include/picongpu/plugins/radiation/frequencies/radiation_lin_freq.hpp#L43), [log](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4cf1739addad964f26135b8d188a35a474ae4c5f/include/picongpu/plugins/radiation/frequencies/radiation_log_freq.hpp#L47), and [from file](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4cf1739addad964f26135b8d188a35a474ae4c5f/include/picongpu/plugins/radiation/frequencies/radiation_list_freq.hpp#L58). However it is not clear why doesn't this code just use `float_64` always - it is not done in a hot loop so potential performance gain from `float_X` vs. `float_64` would appear negligible.

Thus, while having variable `omega` as `float_X` probably makes performance sense (if we can afford the accuracy), calculating its as `float_X` imo does not. It also seems these init functors were not changed during the hackathon, so they are `float_X` for a while. And having a cast [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4cf1739addad964f26135b8d188a35a474ae4c5f/include/picongpu/plugins/radiation/Radiation.kernel#L368) maybe even implies that the functor result was expected to be `float_64`?

**Comment by sbastrakov** [comment]
Perhaps @PrometheusPi you could comment on my last message.

**Comment by Anton-Le** [comment]
@sbastrakov If I remember correctly pen-and-paper rounding error analysis indicates that the phase and its constituents _should_ be kept in 64 bit (I will have to check that one in my notes, though).

**Comment by Anton-Le** [comment]
I think I have pinpointed the one (or two) variable(s) responsible for the effect. By reverting the [changes](https://github.com/ComputationalRadiationPhysics/picongpu/issues/4208#issuecomment-1188767843) I came to obtain the following spectrum:
![Spectrum_detector22_nobg_3264bit_v5](https://user-images.githubusercontent.com/50339174/180756302-2c7fe562-04c2-48eb-9b94-4685f1e1988e.png)
Here the only changes left are: `particle_locationNow` and `phase` in `Radiation.kernel` are kept in 64 bit - along with the necessary `float_64()` cast for filling `particle_locationNow`.

The spectral pattern will **reappear** if `particle_locationNow` is of 32 bit precision (default `float_X`).

*I therefore would conclude that the 'tree' pattern is of numerical nature and is due to the accumulation of rounding errors in the computation of the particle's location.*

It is not sufficient to only declare `particle_locationNow` to be `float_64` since the constituents of the expression filling the entries are all `float_X` the problem will persist unless a `float_64` cast is introduced to a component (e.g. `float_64(globalPos[i])`)

**Comment by sbastrakov** [comment]
Fixed with #4231.

**Comment by PrometheusPi** [comment]
Sorry for the late reply:
The original thought of using `float_32 = float_X` was to increase occupancy based on GPUs of the 1.3 generation. 
This is definitely not needed anymore. 

@StevE-Ong Yes, the spikes you observe might very likely come from this rounding error.
