### ISSUE TITLE
Doxygen config file misconfigured

### ISSUE THREAD

**Issue by BrianMarre** [ComputationalRadiationPhysics/picongpu#4270]
The latest readTheDocs Documentation on how to build the doxygen documentation does not work as described, no html folder is actually generated if one follows the documentation, since 
https://github.com/ComputationalRadiationPhysics/picongpu/blob/f272ec49dca42afa16580d81dfedd772b74cc845/docs/Doxyfile#L9

sets generate html to false

**Comment by steindev** [comment]
@BrianMarre Please provide a PR with a fix.

**Comment by steindev** [comment]
Wait. That line was changed the last time 6 years ago. And I generated html after that date. Are you sure you followed the documentation?
See (https://picongpu.readthedocs.io/en/latest/dev/sphinx.html).
I assume you followed (https://picongpu.readthedocs.io/en/latest/dev/doxygen.html) which is indeed not correct, as `doxygen` by default does not generate html, since the html pages are generated by sphinx.

So the fix would be an update of the doxygen page in the manual.

**Comment by BrianMarre** [comment]
I did indeed follow the dev/doxygen documentation

**Comment by steindev** [comment]
Then pls provide a fix for dev/doxygen documentation page.

**Comment by PrometheusPi** [comment]
@BrianMarre What is the status of the fix and this issue?

**Comment by BrianMarre** [comment]
still need to update the documentation, sorry was busy with RPHDM

**Comment by PrometheusPi** [comment]
@BrianMarre ping

**Comment by BrianMarre** [comment]
fixed by [PR#4630](https://github.com/ComputationalRadiationPhysics/picongpu/pull/4630)
