### ISSUE TITLE
openPMD-api output: global window offset only in meshes

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4276]
Apparently, the [*global window offset*](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions) of a simulation is only stored in mashes with PIConGPU's openPMD-api output. 
This is fine as long as both meshes and fields are stored, but highly unpractical if one has only particle data and needs to determine the lab-frame position of particles, which requires the *global window offset* + the *position offset* + the *(in cell) position* to be added. 
Previously, PIConGPU stored a *position offset* with the *global window offset* added to it - but this seems to to be the case anymore. 

I am not sure whether this issue is caused by PIConGPU or the [openPMD-api](https://github.com/openPMD/openPMD-api) standard and whether there is a standard-conform way of solving this. 

Thanks to @nicowrobel for finding this issue.

**Comment by sbastrakov** [comment]
After investigating and discussing offline it seems we have a bug in how the openPMD plugin calculated values for the openPMD `positionOffset` particle attribute. Which means our data does not adhere to the standard and one needs to know it, and also potentially know additional information to properly interpret it. So it is a serious bug.

From the standard, it is supposed to be an offset in what PIConGPU calls total coordinate system. And in the old HDF5/libSplash plugin it was indeed that. The base offset was calculated [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9180c81ba5ae029ee216291264dd1e2a205dff00/include/picongpu/plugins/hdf5/HDF5Writer.hpp#L651-L655) and so was the start of local domain in the total coordinates. [The comment at the usage place](https://github.com/ComputationalRadiationPhysics/picongpu/blob/9180c81ba5ae029ee216291264dd1e2a205dff00/include/picongpu/plugins/hdf5/WriteSpecies.hpp#L160-L165) agrees. It also matches the analysis @PrometheusPi did for those older outputs.

However, in the openPMD plugin this part works differently, and it seems to be at least in the previous release and probably since the very beginning of the plugin. We do the base offset calculation [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/25850d972b48f80a9b7fdfa6b5e9e484623dd854/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L1412-L1415). So it implements a quite different logic alltogether. Notably, we also [clamp it to 0](https://github.com/ComputationalRadiationPhysics/picongpu/blob/25850d972b48f80a9b7fdfa6b5e9e484623dd854/include/picongpu/plugins/openPMD/WriteSpecies.hpp#L501). I will investigate further, but my current understanding is that part uses its own definition of offset that does not match openPMD's and I am also not sure what does it express.

**Comment by sbastrakov** [comment]
I did the following test. Used standard LWFA example, 4.cfg, changed to 2 GPUs and grid in y to 1024. Below is output of [these two variables](https://github.com/ComputationalRadiationPhysics/picongpu/blob/25850d972b48f80a9b7fdfa6b5e9e484623dd854/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L1412-L1415). Since it is used inside both normal output and checkpointing, and the setup uses both, I also added print before.

[output.txt](https://github.com/ComputationalRadiationPhysics/picongpu/files/9424650/output.txt)

I do not currently understand what is happening except it is not correct. Also notably the normal output and checkpoints use different values internally. So the loader from checkpoint must reflect the checkpoint logic I guess, unless it is also broken?
In my understanding, the correct output would have been what it is before the first slide, and then gradually increasing `particleOffset` values, not decreasing.

Hopefully @psychocoderHPC can make sense of all that when he is back.

**Comment by psychocoderHPC** [comment]
I was struggling with the last time too. The problem is that OpenPMD is not clearly defining the position offset.
@sbastrakov and me discussed it and checked also the openPMD standard and come to the result that our implementation is correct.
There was somewhere in the openPMD universe a discussion about it but I cannot find it.
As I can remember it is not possible to work with particles only without the information of the fields. The fields offset to the lab frame are required to have the absolute particle position.

**Comment by sbastrakov** [comment]
> As I can remember it is not possible to work with particles only without the information of the fields. The fields offset to the lab frame are required to have the absolute particle position.

This is true for current PIConGPU implementation, I do not think it is in the openPMD standard. We agreed to discuss it in the office on Wednesday with @psychocoderHPC .

**Comment by psychocoderHPC** [comment]
@sbastrakov and me discussed the issue again. We will change PIConGPU to store particles with total offset. This requires updating the patch offset and during the restart, we need to find suitable patches based on the new indexing and remove the total index to store particles into our hierarchical structure.

**Comment by sbastrakov** [comment]
Solved with #4283.
