### ISSUE TITLE
Field-matter interaction in PIConGPU

### ISSUE THREAD

**Issue by weqoll** [ComputationalRadiationPhysics/picongpu#4286]
Hello! My name is Egor and I'm 4th grade student in Moscow State University.

I have just started working at ionization in PIConGPU and have already had some troubles with understanding the theoretical basics of this process in the code. As far as am I concerned, your PIC-code brings two main particle types through the simulation: ions and free electrons. While species definition occurs, I use particle manipulator called "boundElectrons" that somehow 'stitches' some free electrons to ion. With that thing I can simulate the experimental setup quite closely to what i get in reality (gas instead of preformed plasma and etc.).

However, I have some issues with light-matter interaction in your code. While the motion of plasma components is being calculated with Maxwell-Vlasov equations through PIC-cycle, is there any calculation for the motion of uncharged particles? Does PIConGPU take into account both bound electrons and atomic core separately, or are there some other mathematical models for the atomic motion? If such interactions are provided by the code, could you please show me the equations set or give me some sources to the theoretical basics of your simulation methods?

I'm sorry I couldn't find it in documentations. When I checked it last time, there was only information about PIC-cycle and ionization models.

All the best,
Astashkin Egor

**Comment by sbastrakov** [comment]
@BrianMarre could you have a look?

**Comment by BrianMarre** [comment]
I am not quite sure I understand what you're are actually asking.

In principle, ionization in PIConGPU comes down to creating new free electron macro particles from existing ion macro particles depending on local conditions.

The currently remaining number of bound electrons(read charge state) of a given macro ion is stored for each macro ion in the particle attribute boundElectrons, essentially a counter of the remaining number of bound electrons for each macro Ion (boundElectrons also influences the current charge of a macro ion, which influences it's Lorentz force)

PIConGPU does not model bound electron density functions, nor are different macro particle shapes used for different charge states. Macro ions in PIConGPU are just variably charged macro particles that may spawn new free electrons if boundElectrons has not yet reached zero and local conditions indicate.

PIConGPU supports different models for ionization as you already noted, those mostly describe under which conditions we spawn how many macro electrons.

Currently in the master branch implemented algorithms use local field strength and electron density+[approx.]temperature to decide whether to spawn new free electrons.
We are in the process of improving this by also modelling atomic transitions from and to exited atomic states due to a local non thermal electron spectrum[already in the dev branch], but this implementation is still experimental and not suggested for production use yet.

Photon interaction ionization(+de-/excitation) is planned but not yet finalized.

PIConGPU also includes some Photon transport modelling, elastic scattering, polarization shifts and incoherent bremsstrahlung, but these are not yet integrated with the atomic transition modelling[planned but not finalized] and some of them are not yet in the dev branch.

I hope this fast introduction helps you, if not do not hesitate to ask again.

**Comment by weqoll** [comment]
Thanks a lot for your attention to my problem! Your introduction really helped me.

**Comment by BrianMarre** [comment]
Please remember to close the issue if your questions are answered for now. ;)

You may reopen/(open a new) an issue in the future if further questions arise.
