### ISSUE TITLE
Simple experimental setup with PIConGPU: weighting and grid sizes

### ISSUE THREAD

**Issue by weqoll** [ComputationalRadiationPhysics/picongpu#4304]
Hello everyone!

I'm still trying to deal with PIConGPU ionization module by recreating simple experimental setup. It consists of uniformly distributed argon gas (it was implemented due your documentation in github-wiki) and the transversely polarized laser pulse driving from left to right in the simulation box `Lx=4e-6` (meters), `Ly=6e-6` (meters). The pulse is focused into the gas at the ambient pressure with `waist=0.8e-6` (meters), `max_intensity=1.e14` (W/cm^2), `wavelength=0.8e-6` (meters) and `focus_point=3.e-6` (meters). X and Z are transversal axis, while Y is longitudinal one

Ionization works well and everything is perfect from technical side, but I'm not fully satisfied with resulting output maps. Laser was supposed to ionize the most atoms in the focal spot resulting with organized plasma "spark". However, due to calculations there's only few distinct macroelectrons after the pulse propagation that cannot really simulate behavior of the plasma and its radiation. I was trying to make `MIN_WEIGHTING` parameter lesser while increasing `TYPICAL_PARTICLES_PER_CELL`, minimize the grid and increase intensity of the input laser. Last way results in organizing the whole plasma "column" with the length of simulation box instead of plasma "spot" in the focus position. Other ones weren't successful too, there aren't any changes through increasing/decreasing parameter values. Example colormaps and png from PNGWriter are attached here.

Is there any other troubleshooting ways you could advise me to follow? Is there any "levers" to manage weighting parameter for particles in PIConGPU except for `MIN_WEIGHTING`? 

Also I want to ask about interesting thing I found. If I make grid lesser then `dx=dy=dx=5e-9`(meters), no particles initialize due to simulation. Firstly I was thinking that issue is about particle spatial distribution (that two ion particles with TCS shape just cannot sit in such small cell), but electrons don't initialize too. What is the reason for such issue?

Best wishes,
Egor Astashkin
IMAGES:
1. That's what I've got from calculation: Field maps.
2. That's what I've got from calculation: Electron density by PNGWriter (black dots are macroelectrons)
3. That's what I'm trying to recreate: Electron density and fields E_y, B_z (due to our axes, in the article z-axis was longitudinal instead of y-axis)
![image](https://user-images.githubusercontent.com/112808096/192908944-13d4dbbd-33e1-43fa-8afc-f1b1d256325d.png)
![image](https://user-images.githubusercontent.com/112808096/192909524-9986ba8e-9f33-48ab-a549-0ac72bdea6c7.png)
![image](https://user-images.githubusercontent.com/112808096/192909572-a28b2a5e-74e9-4617-99bb-f05860aaa4e9.png)

**Comment by psychocoderHPC** [comment]
@weqoll Thaks for opening the issue. I have some questions and will ping developers who are more familiar with ionization.

1. Which version of PIConGPU do you used? If dev branch than the commit hash. `git log --pretty=format:'%h' -n 1`
2. Is it possible to append the setup you used for your observation `If I make grid lesser then dx=dy=dx=5e-9(meters), ...` as zip to this issue so that we can see your density profile.
3. Could you please run 10 steps and add `--e_macroParticlesCount.period 1` to your `cfg` file to enable the macro particle counter. This output is required to analyze the possible bug that you see electrons where no electrons should be.
4. How Many GPUs do you used?
5. Is moving window enabled?

**Comment by weqoll** [comment]
1. PIConGPU version 0.5.0. I'm not sure if that's a dev branch, I installed it from spack
2. [IP-21sep22-adk.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/9677968/IP-21sep22-adk.zip) -- that's basically my setup for this experiment.
3. e_macroParticlesCount.dat
![image](https://user-images.githubusercontent.com/112808096/193110442-2f50d90b-f23f-47f8-84c6-90f8f7f2e747.png)
4. i_macroParticlesCount.dat
![image](https://user-images.githubusercontent.com/112808096/193110536-feac5df0-35d6-4615-b939-e025b6d43b94.png)
5. 8 GPUs: 2x4x1 (X_GPUxY_GPUxZ_GPU)
6. No, it isn't. Moving window is disabled

**Comment by BrianMarre** [comment]
First, I think you misunderstood what the parameter 
´´´TYPICAL_PARTICLES_PER_CELL´´´ does. 

This parameter does not set the number of macro particles to spawn, it is merely a hint by the user towards how many macro particles picongpu is supposed to expect per species and cell.

The actual target macro particle number per cell is set for each specie s separately in the init.param of picongpu, set the ppc value to the number of macro particles you want in each cell.

If did. misread your question, sorry I just want to make sure that we all argon the same level ;).

On the "no particle are spawned for small cell sizes" question.

Picongpu does not always spawn exactly the configured amount of macro particles per cell, instead it aims to create as many as specified by the user, by dividing the actually existing species number density times volume in cell in as many macro particles as the user specified, unless the resulting weight would be lower than the minimum weight the user specified, should be at least 1 [one physical particle per macro particle].
If we would fall below this lower, picongpu instead spawns as many macro particles as possible, while still satisfying the lower limit.

This can resulting no macro particles being spawned, if in the entire simulation, no cell exists where the density is high enough to allow spawning at least one macro particle, I have run into this problem myself before ;).

Regarding the number of by ionisation spawned macro electrons.

It would be helpful to know which exact ionisers you configured,they have different characteristics for spawning macro particles. I do not know out of may head, which does what but I can look it up, next week.

Also for all our ionisers, the number of macro particles spawned, scales with the number to initial macro ions, therefore if you started with a low number of macro ions per cell, the resulting number of macro ions per cell is also going to be low.

This is actually usually the case in our examples, since they are trimmed down as much as possible to allow low memory machines to run them.

**Comment by weqoll** [comment]
Thanks for your answer.

In this setup I'm using ADKLinPol model of ionization. I'll be delighted to receive your explanation about ionization. Because of that I'm keeping this issue opened. Also there is high possibility that I'll have another questions to this issue.

**Comment by weqoll** [comment]
However, I didn't saw any file called init.param. 
Did you mean unit.param? Or did you write about some *.param file inside PIC core that cannot be edited by "pic-edit" command?

**Comment by BrianMarre** [comment]
Sorry, the file is called speciesInitialization.param

**Comment by weqoll** [comment]
OK, thanks for your explanations, I'll keep studying this code! Also I'll be waiting for your ionization models characteristics here next week, if you don't mind!

**Comment by PrometheusPi** [comment]
Hi @weqoll, 
could you already analyze your new ionization models characteristics? Do you have any further questions?
