### ISSUE TITLE
Ionisation for gas mixture

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu#4332]
Hi all 👋 

In `fbpic` one can use a gas mixture when simulating LWFA by defining the densities of the two gases separately and then computing the total electron density and creating each ion species. The documented [example](https://fbpic.github.io/example_input/ionization_script.html) shows how to do this for a 20% Nitrogen - Helium mixture.

How can a similar setup be achieved using `PIConGPU`? On a first look, I was not able to find documented examples of this.

Thank you!

**Comment by pordyna** [comment]
Hi @berceanu, 
you could have a look at the FoilLTC example. It is not LWFA, but it has a mixture of different elements and also includes pre-ionization like in your `fpic` example. The most relevant param files are `density.param`, `speciesDefinition.param` and `speciesInitialization.param` (and `particle.param` for the ionization). Also, @BrianMarre may know how one can set it up in python with `PICMI` .

**Comment by steindev** [comment]
Yes, the FoilExample setup is a very good place to start and should tell you everything you need @berceanu. If you have more specific questions, feel free to ping @PrometheusPi (or me), he is doing these things regularly.

**Comment by berceanu** [comment]
I guess this is one of the things that `PICMI` will make much easier, porting input files between codes. Is it already implemented in `PIConGPU`?

**Comment by pordyna** [comment]
Some support for PICMI is already in dev, but not in the release yet. https://picongpu.readthedocs.io/en/latest/usage/picmi/index.html

**Comment by berceanu** [comment]
OK, sorry for the crappy "graphics", but basically the idea is this: we (@StevE-Ong and I) would like to simulate a 2% Nitrogen - Helium mixture, starting from He2+ and N3+. 

![notes](https://user-images.githubusercontent.com/4405658/198326878-05cab61f-0f92-41b2-a60c-9b309ac0ccbb.jpeg)

We have made changes to the [param files](https://gist.github.com/berceanu/80b4644e96f25ac2119d7ff089238719)

However, by our calculation, the `BASE_DENSITY_SI` (which we call n_e) should be 7.8e24 and it is lower than that, even though the densities for Nitrogen and Helium seem to be correct:

![Density_N_0](https://user-images.githubusercontent.com/4405658/198329833-69920344-3ac1-4c22-bf8c-f5373defd1f5.png)
![Density_He_0](https://user-images.githubusercontent.com/4405658/198329859-20a4ca6e-f9c9-437c-98b3-9feb3638b498.png)
![Density_e_0](https://user-images.githubusercontent.com/4405658/198329893-ff5f7609-13f6-4b64-b663-8f4eea78d2db.png)

**Comment by StevE-Ong** [comment]
For `BASE_DENSITY_SI=7.8e24`, then He ion density should be around half of it for fully ionized. The second picture is kind of make sense for 98% He...slightly lower than `7.8/2e24`. I am not sure about others. Can anyone have the experience to set up density for doping gas help? Thanks.

**Comment by PrometheusPi** [comment]
HI @berceanu and @StevE-Ong,
we run doped LWFA  simulations with PIConGPU quite often. The workflow is as follows:
0.) Since in our case, we can assume a weak pre-pulse (or an intentional ionization laser) to ionize all electrons from He and **all but 2** (why is the photo of your derivation using 3?) electrons from the Nitrogen molecules, we will only simulate electrons that are already free (from both N_2 and He), ignore He nuclei and model Nitrogen ions in ratio to the elecron density. 
1.) in your `speciesInitalization.param` derive your Nitrogen ions (with remaining 2 electrons) from your electron density as follows:
```c++
  using InitPipeline = mpl::vector<
    CreateDensity<densityProfiles::FreeFormulaElectronsLWFA,
                  startPosition::Random1ppc,
                  PIC_Electrons>,
    ManipulateDerive< manipulators::binary::DensityWeighting,
                      PIC_Electrons,
                      PIC_Nitrogen >,
    Manipulate< manipulators::PreIonized,
                PIC_Nitrogen >
>;
```
2.) in your `density.param` you can use any density profile that gives the density of your free electrons. In our case this is the self defined `densityProfiles::FreeFormulaElectronsLWFA` profile. 
3.) to get the ratio between electrons and Nitrogen right, you need to add a flag to the Nitrogen ions that contains that ratio. To do that, add in `speciesDefinition.param`
```c++
/* 
percentages in gas mixtures are given in percent partial pressure
that means that 98% He and 2% N_2 are the ratio
1st factor: ratio He/e_He =0.5 (assuming there is much more He than N_2) 
2nd factor: 2 (He_1 vs N_2 molecule) 
3rd factor: doping (=2.0%) 
This assumes that the doping is small, the correct factor is:
N_2_partical_pressure * N_per_N2 / total_free_electron_number = 0.02*2/(0.98*2 + 0.02*5) = 0.0194 ≠ 0.02
*/
value_identifier(float_X, DensityRatioNitrogen, 0.5 * 2.0 * 0.02 );
```
and then adding this value as flag to the Nitrogen definition:
```c++
using ParticleFlagsIons = bmpl::vector< 
    particlePusher< UsedParticlePusher >,
    ...
    densityRatio<DensityRatioNitrogen>,
    ...
    >;
```
4.) finally you need to define the partially-pre-ionized manipulator `manipulators::PreIonized` in `particles.param` as follows:
```c++
namespace manipulators
{

  //! ionize ions to 5+
    struct PreIonizedImpl
    {
      template< typename T_Particle >
      HDINLINE void operator()(
                              T_Particle& particle
                              )
      {
        constexpr float_X protonNumber = GetAtomicNumbers< T_Particle >::type::numberOfProtons;
        particle[boundElectrons_] = protonNumber - 5;
      }
    };

  //! definition of OnceIonized manipulator
  using PreIonized = generic::Free< PreIonizedImpl >;

```
I hope this helps.

**Comment by PrometheusPi** [comment]
The values from your plots look correct to me. If you assume an electron density of 0.78e25 m^-3 the expected He density in cm^-3 is 8e18 cm^-3 * 0.5 = 4e18 cm^-3 - which as you mentioned seems to match. But Nitrogen density should be 0.0194 * 0.78e25 m^-3  = 1.5e17 cm^-3  - also that agrees as you mentioned.

**Comment by PrometheusPi** [comment]
The error in your setup occurs here: https://gist.github.com/berceanu/80b4644e96f25ac2119d7ff089238719#file-speciesinitialization-param-L29-L32
To get the electrons from the He you use `Derive` and thus only initialize one electron per Helium ion making your electron density (when neglecting electrons from Nitrogen) only half the expected value. This explains the lower electron density: 4e18 cm^-3 * 2 = 8e18 cm^-3. 
To avoid this, you can use the same approach as with the Nitrogen electrons:
```c++
ManipulateDerive<
    manipulators::binary::UnboundElectronsTimesWeighting, 
    Helium, 
    Electrons
>
```

Per se I would recommend to avoid this approach from ion to electrons, because with this you are creating with 2ppc:
2 He ions, 2 N ions, 2 electrons from He and 2 electrons from N thus 8 macro particles per cell. 
With the approach described above you neglect He all together and combine the free electrons ending up (assuming 2ppc) with:
2 free electrons 2 Nitrogen ions = 4 macro particles per cell
and thus only half the memory footprint.

**Comment by StevE-Ong** [comment]
Thank you @PrometheusPi for your helps. Applying these changes, 

        using InitPipeline = bmpl::vector<
        CreateDensity<
            densityProfiles::Homogenous,
            startPosition::Random2ppc,
            Electrons
        >,
        ManipulateDerive<
            manipulators::binary::DensityWeighting, 
            Electrons, 
            Nitrogen
        >,
        Manipulate<
            manipulators::PreIonized,  # particle[boundElectrons_] = protonNumber - 5._X; in particle.param
            Nitrogen
        >,
        ManipulateDerive<
            manipulators::binary::UnboundElectronsTimesWeighting, 
            Nitrogen, 
            Electrons
        >

now we have for N5+
<img src="https://user-images.githubusercontent.com/52823653/198533377-7a57f9fa-d6ba-4ef9-aa7d-ed5a24a8e3a2.png" width="300" height="300" /> <img src="https://user-images.githubusercontent.com/52823653/198533386-f8d9b057-ec63-4811-8303-1526b84f23b5.png" width="300" height="300" />

with N3+ 
<img src="https://user-images.githubusercontent.com/52823653/198540522-dea61086-d8cb-43e4-957c-dce4e1704697.png" width="300" height="300" /> <img src="https://user-images.githubusercontent.com/52823653/198540527-9789bf82-45b8-4add-95c4-2d4a70e7a9aa.png" width="300" height="300" />

I think it looks good now.

**Comment by PrometheusPi** [comment]
Perfect - I, personally would still combine the first and last electron init, but this is up to you. 
If your question is answered @berceanu and @StevE-Ong, could you please close the issue?

**Comment by berceanu** [comment]
Thanks again for your help, I hope this will also serve others! Closing.

**Comment by PrometheusPi** [comment]
I hope so too. For now, it is documented in this issue. But your question definitely indicates, that we should improve our documentation regarding doping. 
Thanks for closing the issue.
