### ISSUE TITLE
radiation plugin does not produce openPMD output anymore

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#4397]
The current `dev` version of PIConGPU does not produce openPMD radiation output anymore. 
Most likely this is caused by #4387. A simulation that used the 2022-11-22 `dev` branched produced the openPMD files.

**Comment by PrometheusPi** [comment]
Discussion with @franzpoeschel:
In his case, the files were created. I will test on a different cluster.

**Comment by PrometheusPi** [comment]
@franzpoeschel found out that this is only triggered with checkpoints are also written.

**Comment by PrometheusPi** [comment]
If checkpoints are active - radiation data is stored in the checkpoint directory.

**Comment by franzpoeschel** [comment]
I was not aware that checkpointing uses the same instance of the plugin as normal output. Since the recent PR keeps one instance of the `openPMD::Series` open, whatever call to the plugin comes first – normal output or checkpointing – gets the shot at deciding where output will go.
Should be easy to fix by making the plugin keep *two* instances open – one for normal output, another one for checkpoints.

**Comment by PrometheusPi** [comment]
fixed with #4401
