### ISSUE TITLE
unexpected change in LWA 1.cfg and 1_isaac.cfg

### ISSUE THREAD

**Issue by kimjohn1** [ComputationalRadiationPhysics/picongpu#4414]
During investigation of issue #4410 I noted that the TBG_gridSize specified in 1.cfg and 1_isaac.cfg for the LaserWakefield example simulation is 192 1024 192 in the dev branch and 192 1024 12 in the Master branch.

That seemed like a pretty hefty change in the dev branch for a 1-GPU processed simulation.  Is that a typo or an intentional change?

Kim

**Comment by kimjohn1** [comment]
The changed configuration files appear to be part of a new laser implementation in the LWFA simulation example (see #4394 ).

Changing
`TBG_gridSize="192 1024 12"`
to
`TBG_gridSize="192 1024 192"`

imposes an order of magnitude increase in the processing, memory and storage requirement needed to run the simulation.  The simulation takes 10 times longer to run, and the stored output generated goes from 12GB using the previous laser implementation, to 188GB with the new one.  My low power demonstration lab computer crashes half way through the LWFA simulation when using openPMD SST for in situ visualization because the buffered output exceeds the system memory capacity.

The system requirements imposed by setting the Laser Wakefield simulation grid size Z axis to 192 seem to me to be inappropriate for an example simulation that is included in the PIConGPU installation, and purposely limited for simplicity to facilitate introduction and training.

I suggest that the grid size specified in configuration files for the Laser Wakefield example simulation be set back to 192 1024 12, and the new laser implementation be changed to accommodate that smaller grid size.  Explanation for increasing the grid size for a higher resolution simulation, and the resulting impact on processing time, memory and storage capacity requirements, can be included in appropriate documentation, for users interested in implementing a more robust, production representative LWFA simulation.

**Comment by psychocoderHPC** [comment]
> I suggest that the grid size specified in configuration files for the Laser Wakefield example simulation be set back to 192 1024 12, and the new laser implementation be changed to accommodate that smaller grid size. Explanation for increasing the grid size for a higher resolution simulation, and the resulting impact on processing time, memory and storage capacity requirements, can be included in appropriate documentation, for users interested in implementing a more robust, production representative LWFA simulation.

We decided to do exactly the opposite. The main focus of PIConGPU is running on a cluster, therefore we provided examples for decent-sized systems. A modern GPU as not a problem to calculate the laser wakefield example with `192 1024 192` but as you wrote the data produced a solidly larger and maybe if you use ISAAC to visualize the simulation or openPMD SST to stream out data you will be slower.
We discussed some possible solutions that would allow scaling the global simulation size without redefining the focus position.
Since we do not have currently free capacities to implement it we decided on the requirements to change the focus position if you change the global simulation volume because this is what the physicist must do anyway for his physics setup.

For the issue that openPMD streaming exceeds the main memory please check if you write out only the data to SST you need. for the visualization. You can define the data via command line or in a toml file https://picongpu.readthedocs.io/en/latest/usage/plugins/openPMD.html?highlight=toml#configuring-the-openpmd-plugin-with-a-toml-configuration-file

Let me ping @franzpoeschel he can also point you to an example of how you can define the data you like to write out via openPMD from the data consumer side (your visualization application)

**Comment by kimjohn1** [comment]
@psychocoderHPC 

I understand.  Please do not trouble Franz.  I am not confused by the system crash.  I was simply providing an example of one of the consequences of your decision.

Can you tell me how I would need to modify the Laser Wakefield simulation so I can continue to use a grid size of 192 1024 12.  I have attempted using your suggestion from the closing comment in issue #4410 to set the grid size to 192 1024 12 in the configuration file , and then set the Z axis position for the laser in `incidentField.param` as follows:
`static constexpr float_64 FOCUS_POSITION_Z_SI = 1.0632e-06`

That does not work.  The simulation runs 10 times faster and produces a total of 12GB of data output, so it is definitely using the smaller grid size setting, but the .png files all continue to show a plain grey field with no image.  Do you know what else might need to be done to produce correct output?  For my testing, I used the dev branch downloaded today.

Finally, please consider including a "resource limited" Laser Wakefield example simulation along with the one you have decided to include (perhaps after we have figured out how to create one!).  The less demanding limited version could include the grid size of 192 1024 12, and would be most useful for someone looking at possibly using PIConGPU, or someone who was just starting to learn how to use PIConGPU and are using a Laptop, Desktop or Workstation computer for their introduction and examination.  That is an important demographic for continued use of PIConGPU.

**Comment by kimjohn1** [comment]
Good discussion here, but the original posted issue is completely answered.  Closing the issue.

**Comment by psychocoderHPC** [comment]
> and then set the Z axis position for the laser in incidentField.param as follows:
static constexpr float_64 FOCUS_POSITION_Z_SI = 1.0632e-06

Was this change helping you to reproduce the old behavior? Please to not forget that you need to set the Z direction as periodic else the laser will not shown: https://github.com/ComputationalRadiationPhysics/picongpu/blob/31e6cc64bf8f42987641bf30171c12fd71527231/share/picongpu/examples/LaserWakefield/etc/picongpu/1_isaac.cfg#L43

It could be that https://github.com/ComputationalRadiationPhysics/picongpu/blob/31e6cc64bf8f42987641bf30171c12fd71527231/share/picongpu/examples/LaserWakefield/include/picongpu/param/incidentField.param#L268 bist be set to `{0, 0}` too. I need to double check this because I am also not very familiar with that laser generation of PIConGPU.
