### ISSUE TITLE
Incident field laser in LaserWakefield example doesn't follow the guidelines from the docs

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#4416]
This here is written in the [docs](https://github.com/ComputationalRadiationPhysics/picongpu/blob/31e6cc64bf8f42987641bf30171c12fd71527231/docs/source/usage/workflows/addLaser.rst#L37):
> In principle, the same sources should be applied at the whole generating surface, not just at planes where the lasers enter.

However, the [LaserWakefield example](https://github.com/ComputationalRadiationPhysics/picongpu/blob/31e6cc64bf8f42987641bf30171c12fd71527231/share/picongpu/examples/LaserWakefield/include/picongpu/param/incidentField.param#L238) only has one of the surfaces as generating surface:
```cpp
using XMin = profiles::None;
using XMax = profiles::None;
using YMin = profiles::GaussianBeam<GaussianBeamParam>;
using YMax = profiles::None;
using ZMin = profiles::None;
using ZMax = profiles::None;
```
This should probably also be updated in [other parts of the docs](https://github.com/ComputationalRadiationPhysics/picongpu/blob/31e6cc64bf8f42987641bf30171c12fd71527231/include/picongpu/param/incidentField.param#L49), where this is not suggested yet to be more consistent.

@steindev

**Comment by steindev** [comment]
Yes, this is on purpose and a safety measure. The incident field method calculates the field on the source plane by assuming laser propagation in vacuum from the source plane to the focal plane. Now, the simulation box of the LWFA example is relatively narrow, such that the vacuum laser propagation would result in a significant field at the `XMin`, `XMax`, `ZMin`, and `ZMax` sources planes at some point behind the vacuum laser focus.
This potentially means that we feed field in the simulation although there should not be any field since the laser actually propagates in the plasma where its evolution is different from vacuum propagation.
However, as the energy flow of the calculated field on the source plane behind the focus should be outwards, it is not clear to me, whether field is really fed into the simulation volume or not.
You can try this!

In any case, since the laser propagates in the plasma, we avoid any risk by deactivating the transverse source planes.
