### ISSUE TITLE
How to correctly introduce the laser into the simulation area?

### ISSUE THREAD

**Issue by baobaba13** [ComputationalRadiationPhysics/picongpu#4480]
Hi guys：
@sbastrakov In the `laser.param` file of Bremsstrahlung, `t_InitPlaneY==0` , does it mean that the laser hard source is used? If it is a hard source, when the laser moves to the foil target, will the laser be completely reflected by the target? If so, will the result of bremsstrahlung be affected by this reflection and inaccurate? Another question is, what is the meaning of the mixed hard-soft source described in the online manual?`https://picongpu.readthedocs.io/en/latest/usage/workflows/addLaser.html#usage-workflows-addlaser` If the mixed hard-soft source is used, can the reflection of PEC material be avoided?

**Comment by sbastrakov** [comment]
Hello @baobaba13, hopefully @psychocoderHPC @PrometheusPi @steindev or other developers could answer your questions.

**Comment by BrianMarre** [comment]
It means that the plane on which laser is added onto the field values is located at y=0.
That is by itself independent of the reflection of the laser at some target frontside, which is a physical effect.
I am therefore not quite sure what you mean by hard source, could you explain that in more depth?

**Comment by psychocoderHPC** [comment]
@baobaba13 If and how much the laser is reflected by your foil target depends on the density of your foil. If your foil is dense e.g. as the default FoilLCT  example and https://github.com/ComputationalRadiationPhysics/picongpu/blob/31d6be94c7a40ab3fa4cb3c2bdcd771ba9eae00e/include/picongpu/param/laser.param#L133 is zero than all laser reflection moving from the target to the out simulation borders where the laser is defined will be reflected on the outer simulation border and moving again into the direction of the target.
If you set `initPlaneY` to something larger than the absorber you will have in the negative Y direction an absorber that will reduce the reflected waves coming from the target.

> Another question is, what is the meaning of the mixed hard-soft source described in the online manual?

IMO `mixed hard-soft source` means that applies the laser field with a coefficient ` E(y=0, t) += coefficient * E_source(y=0, t)` as described later in the documentation section and not have a perfect `soft source` as implemented by the incident field laser profiles. The `mixed hard-soft source` has the disadvantage that we create two laser pulses, one moving into the positive Y direction (to the target) and the other into the negative direction because we do not calculate the B field. The negative propagating laser pulse is then mostly absorbed by the boundary absorber.
@steindev @PrometheusPi Could you please check if my (non-physicist) explanation is correct?


Note: 
- We will remove the normal laser profiles soon and will only support incident field lasers anymore https://picongpu.readthedocs.io/en/latest/usage/workflows/addLaser.html#incident-field
- The support for Bremsstrahlung in the dev branch was removed with https://github.com/ComputationalRadiationPhysics/picongpu/pull/4395

**Comment by summer7807** [comment]
Hi @BrianMarre 
Thanks for your reply
Hard source means `E (y=0, T)=E_ Source (y=0, T)` is incident into the simulation area. When the laser is controlled by the pulse length (for example, in the case of bremsstrahlung), they are not transparent for incoming wave (for example, reflected from the target). For details, please refer to the description of `Laser` in the website `https://picongpu.readthedocs.io/en/latest/usage/workflows/addLaser.html#usage-workflows-addlaser`

**Comment by summer7807** [comment]
Hi @psychocoderHPC 
First of all, thank you for your reply. I want to ask why Bremsstrahlung was deleted from dev. You said that you will remove the normal laser profiles soon and will only support incident field lasers anymore，In this case, will Bremsstrahlungs be updated in the old version (0.6.0)？This example is really important to me.

**Comment by psychocoderHPC** [comment]
The bremsstrahlung extensions were based on an old code part called cuSTL from PMacc which was not maintained for years and was blocking us from new development and stabilizing the code base.
At the moment we do not have the developer power to modernize bremsstrahlung and test it.
As soon as someone has time and needs the extension it could be reintroduced based on the implementation available in the history and older releases or a new implementation. A reintroduced version should cover at least basic test cases that the old implementation missed too :-(

@summer7807 please open an issue that bremsstrahlung is important for you. I can not guarantee that someone is implementing it but this is the way to make us aware of the need.

> In this case, will Bremsstrahlungs be updated in the old version (0.6.0)？

We will not update the code base of 0.6.0. As long as you are able to use version 0.6.0 you can work with the Bremsstrahlung extension. Bremsstrahlung is only deleted in the dev branch and will not be part of the soon upcoming release 0.7.0.

**Comment by BrianMarre** [comment]
Small addition, @summer7807 If you are a regular user of the bremsstrahlung plugin you might want to consider contributing to it's maintenance, thereby ensuring a timely return.

**Comment by summer7807** [comment]
Hello@psychocoderHPC , I want to ask if there is a detailed development document about PIConGPU that contains the description of the call between various functions of the program, the program execution process, or the debugging environment of the program. I hope to have a deep understanding of picongpu, but it seems that it can't be done only by running the example. Could you provide me with these, I would be grateful

**Comment by psychocoderHPC** [comment]
@summer7807 Unfortunately we lack a `development document about PIConGPU` and it is something that is not easy to bring up in the near/mid future :-( 
I can offer a 1h VC where we can together go over the structure of the code and I can explain design thoughts and program flows. Writing this down is not as easy because in written form you need images and references else it will not be understandable. The advantage of explaining it will be that questions can be answered directly.

**Comment by summer7807** [comment]
Hi @psychocoderHPC 
Do you mean to communicate through video call, or send me a video material. If it is a video call, I may need to practice my oral English. I am not very confident in my English.

**Comment by BrianMarre** [comment]
there is some introductory documentation [here](https://picongpu.readthedocs.io/en/latest/dev/extending.html) and in more in the sections development and Programming Patterns of the [readthedocs PIConGPU documentation](https://picongpu.readthedocs.io/en/latest/index.html) 

and don't worry about language proficiency we are friendly and will try to accommodate you as much as possible.

apart from that just ask in issues and we will try to answer

**Comment by summer7807** [comment]
Hi@BrianMarre
Firstly，thank you very much ,I don't know what time it is in your area, and what platform or software to use for video calls. I can prepare it in advance. If you are ready, let me know the time. I am very willing to communicate with you face to face. Even if my oral English is not good, I believe I will have a lot to gain from just listening to you

**Comment by BrianMarre** [comment]
Both @psychocoderHPC and I are relatively busy this week, so what about next week, and for a time I would defer to psychocoderHPC for a time slot.

**Comment by psychocoderHPC** [comment]
@summer7807 could you please write me a mail `r.widera@hzdr.de` that I have your contact? I will delete this post after your mail and will write back via mail that @BrianMarre and me can organize a time slot with you.

**Comment by summer7807** [comment]
@psychocoderHPC Ok
