### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by cbontoiu** [ComputationalRadiationPhysics/picongpu#4536]
Please note that this page
https://picongpu.readthedocs.io/en/latest/install/dependencies.html
is outdated for:

#### 1.  ```openPMD-api``` dependency

As explained in this issue: https://github.com/openPMD/openPMD-api/issues/1424#issuecomment-1513632192
the version should be ```0.15.1``` and there is no ```lib64``` coming with that.

#### 2.  ```boost``` dependency

The most recent version is ```1.82.0``` and there should be a space before ```--prefix``` in
```./bootstrap.sh --with-libraries=atomic,program_options--prefix=$HOME/lib/boost```

**Comment by psychocoderHPC** [comment]
Thanks for the report.

1. Older OpenPMD is still supported so there is no strong need to point to the latest openPMD version. The `lib64` is not critical because we used RPath by default so this line can also be removed. I will update the documentation.
2. Yes the space is missing, I will be fixed soon. For boost there is no need to use the most recent version we support all from 1.74.0- latest release

**Comment by psychocoderHPC** [comment]
issue is addressed in https://github.com/ComputationalRadiationPhysics/picongpu/pull/4542
