### ISSUE TITLE
The scaling of PIConGPU on Karolina A100

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#4605]
I am running the FoilLCT test on [Karolina](https://docs.it4i.cz/general/karolina-mpi/) A100 GPU. The submission is PBS pro instead of SLRUM.

I test with 2,4, & 8 GPUs. As the number of GPUs increases, the computational time is getting slower.
The following is the runtime for 2D simulation without any plugin output.

2 gpus->2'42"
4 gpus->11'27"
8 gpus->11'39"

What would possibly be the reason for the slowing down? Is it possible due to the machine topology (--map-by, --bind-to)? How could we optimize it for picongpu?

[8gpus.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11771394/8gpus.zip)
[4gpus.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11771403/4gpus.zip)
[2gpus.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11771424/2gpus.zip)
[it4cz_Karolina.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/11771731/it4cz_Karolina.zip)

Thanks

**Comment by psychocoderHPC** [comment]
The file`stderr` is showing warning about missing configuration of the infinitude device, it could be the fallback is communication of Ethernet which can result in very bad communication performance. Please check together wiht the system admins of the cluster if you submission file `tbg/submit.start` is correct, maybe you use the wrong MPI module or some parameters are required.

Another possibility is that you have output enabled for 4 and 8 GPUs and no output for 2 GPUs. I checked `stdout` of all runs and the timestep itself looks equal to the 2 GPU run. The highest possibility is that the filesystem is very slow. Please do not run the job within the home directly, you should best always use a fast parallel filesystem.

**Comment by steindev** [comment]
@StevE-Ong is your issue resolved?

**Comment by StevE-Ong** [comment]
I was trying the SPEC benchmark following the scaling test on Juwel. Look quite similar, the scaling for 512x256x256 start deviated after 4 GPUs.

![Screenshot from 2023-06-29 14-22-43](https://github.com/ComputationalRadiationPhysics/picongpu/assets/52823653/e2fa9f45-530f-4900-a57a-c75853807050)
![Speed up vs # of GPU](https://github.com/ComputationalRadiationPhysics/picongpu/assets/52823653/41c5110e-6cfe-4b69-8151-214716c9c92b)

**Comment by psychocoderHPC** [comment]
@StevE-Ong Could it be that you are increase the number of GPUs only in one dimension? e.g.
- 1x1x1
- 1x1x2
- 1x1x4
- 1x1x8

If so I suggest to try to distribute the GPUs even over the dimensions. e.g.
- 1x1x1
- 1x1x2
- 1x2x2
- 2x2x2

This will be much better for the parallelization because the local volumes will be more cubic.
For strong scaling you should depending on you communication network see a scaling efficiency of >90% until a increase of compute devices by a factor of 16x.

info: we removed the SPEC benchmark with #4587 because important parts of the PIC loop was underutilized due to to even trajectories of the particles.
I suggest to use maybe
https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/share/picongpu/tests/KHI_growthRate
even if this is not under the folder benchmark. The advantage of KHI-growth rate test is that there is a `./bin/validate.sh` to check the results for correctness.
See here which to know more about the required number of simulation steps and parameters 
 https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/share/picongpu/tests/KHI_growthRate/bin/ci.sh#L120

**Comment by steindev** [comment]
@StevE-Ong Is your issue resolved?

**Comment by StevE-Ong** [comment]
Hi @steindev. It has not been resolved at the moment.  But we will come back to this issue later on.
