### ISSUE TITLE
Taflove PML test (=fieldAbsorberTest) fails?

### ISSUE THREAD

**Issue by SergeyKonstantinErmakov** [ComputationalRadiationPhysics/picongpu#4610]
It seems that the PML boundaries do not absorb incoming waves properly.
The test for PML boundaries described in "computational electrodynamics, Tavlove, 2005", p.315, shows a relative error below far below 10^-2. However, when performing the test simulation "~/src/picongpu/share/picongpu/examples/FieldAbsorberTest", the relative error appears to be multiple orders of magnitude above what we expect:
![image](https://github.com/ComputationalRadiationPhysics/picongpu/assets/88037200/d2589169-1214-4f16-ae8c-55b0ffe50c44)

Commit Hash:
commit 536e1b72139d526de8a0b6da34abe9cbb2dedc29

**Comment by steindev** [comment]
Not good. Thanks for reporting. I'll try to verify.

**Comment by steindev** [comment]
On the side, according to @SergeyKonstantinErmakov, this behavior already appeared before the PML `abs()` fix last week.

**Comment by steindev** [comment]
Cannot confirm the issue. Will remove the bug label. Offline discussion will follow tomorrow, too.
![fieldAbsorberTest_allComponents](https://github.com/ComputationalRadiationPhysics/picongpu/assets/26382442/6acfb9ea-8417-4c3c-95e7-eaa45b16d509)

**Note 1:**
I had to change the fieldAbsorberTest for better consistency.
Specifically, I increased the the box size along z to the same value as for the reference simulation (larger box size), since our current source infinitely extends along z.
For the same reason, I applied periodic boundary condition at the z_min and z_max boundaries.

**Note 2:**
The test is not well documented and misses an (automatic) analysis script.
I already prepared a `README.rst`.
I still need to convert my Jupyter analysis notebook to a script.
Then I will provide a PR with a refactoring of this test.

**Note 3:** I would like to discuss, whether it would be a better option to limit the extent of the current source along z plus applying PML boundary conditions everywhere compared to what I did now.

**Comment by psychocoderHPC** [comment]
@steindev Please keep all your scripts so that we can automate the tests.

**Comment by PrometheusPi** [comment]
@steindev What is the status of this issue and the progress regarding analysis scripts?

**Comment by steindev** [comment]
Actively working on it at the moment.

**Comment by psychocoderHPC** [comment]
ping @steindev
