### ISSUE TITLE
Particle Bookkeeping Documentation/Source

### ISSUE THREAD

**Issue by matthewa150** [ComputationalRadiationPhysics/picongpu#4737]
When reading through this thread, #4199 , the bookkeeping of particle movement between supercells was brought up. I'm having a hard time figuring out how to efficiently filter out the particles that are leaving the supercell to send them en masse to the neighboring supercells.

I was wondering if I could be pointed to the right files to get the more technical details? (Or if anyone could help explain the process.) I read both the [2013 paper](https://ieeexplore.ieee.org/document/6877438) and the [2019 thesis](https://zenodo.org/records/3266820#.Ysfp14TP02w) but found that neither of them got technical enough in this area to help explain the process.

Any help would be greatly appreciated!

**Comment by steindev** [comment]
ping @psychocoderHPC

**Comment by psychocoderHPC** [comment]
@matthewa150 Sry this question slipped throw my fingers. I moved the description to my todo for Monday, I have this week vacations.

**Comment by matthewa150** [comment]
To expand on my question a little: The 2019 thesis mentions (Section 3.3.6)
> After the particle push and communication in each step, a particle frame list is once compacted from back to front guaranteeing that all but the last frame of a list of frames of a supercell are entirely filled.

How are you able to keep the cost of the supercell communication and (stream) compaction manageable? (For example, I think if you were to do a prefix scan for the stream compaction, a single cell could easily require a list larger than the L1 cache.)

I really appreciate the help, and I hope you have a nice vacation!

**Comment by psychocoderHPC** [comment]
Let me try to answer your question. 

A particle is pushed in the kernel [MoveAndMark](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/picongpu/particles/Particles.tpp#L358-L365) based on the field around the particle position. The filed will be [interpolated](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/picongpu/particles/Particles.kernel#L304-L307) to the particle center position based on the activated partcile shape.
After the new position of the particle is calculated the particle is updating some [particle attributes](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/picongpu/particles/Particles.kernel#L315).
We have a marker attributed [multiMask](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/picongpu/particles/MoveParticle.hpp#L153) which is defining if a particle in a frame is valid or if the slot in the frame is free to hold a new particle. `1` means it is a particle `0` the slot is free. We high-jack this marker and set it to a value between `[2:27]` in case ethe particle is leaving the supercell. The value `multiMask -1` in this case is defining the [direction](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/pmacc/type/Exchange.hpp#L45-L53) where the leafing the supercell. Diagonal moves are valid too.
The attribute `localCellIdx` which defines [the cell the particle is located in is updated too](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/picongpu/particles/MoveParticle.hpp#L133). `localCellIdx` is already updated even if the particle is physically still in the memory of the wrong supercell. IN case the particle is not leaving the supercell only `localCellIdx` will be updated and we do not need to set the `multiMask`.
After the kernel `MoveAndMark` is finished we need to copy all particles which have a `multiMask` value `>=2` into the new supercell. This is done [directly after the pusher kernel](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/picongpu/particles/Particles.tpp#L369).
[Shift particles](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/pmacc/particles/ParticlesBase.hpp#L221-L239) is now copying each particle with `multiMask >= 2` to the corresponding supercell. The particles leaving the supercell will will be appended to the neighbor supercell to the last frame if there are free slots a new frame with particles will be appended.
`KernelShiftParticles` will be executed for each supercell but with a double checkerboard striding pattern so that we can reuse the last frame of neighboring supercells without a complicated locking pattern.
After particles of a supercell are copied to the neighbor supercells we have holes (free slots in a frame) in the frames. PMacc/PIConGPU defines the valid frame list that all frames from the beginning of the frame list must be fully filled with particles except the last frame. The last frame must be contiguous filled from the first slot but at the end it is allowed to have free slots in the last frame. 
To fulfill this definition we need to [fill the gaps](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/pmacc/particles/ParticlesBase.kernel#L617) after we shifted particles. 
In fillGaps we have to pointers, one to the first frame (F1) and one to the last frame (F2). We got throw the list of frames and fill all holes (free slots) in the frame F1 with particles from F2. F1 is traversing the frame list forward and F2 backward until both pointer points to the same frame.
Now particles in the last frame can be stored not contiguous, therefore we run [KernelFillGapsLastFrame](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/pmacc/particles/ParticlesBase.kernel#L349) to guarantee that your definition how particles must be stored in the frame list is fulfilled.

Overall the above bookkeeping sounds complicated but this allows that particles that are not leaving the supercell can be linked to the new cell within the supercell without copying all attributes by updating the `localCellIdx` only. The complicated bookkeeping is only performed for particles leaving the supercell.
Additionally, we to not need to maintain a list of particles per cell, this is not required for the base particle in cell loop. For the binary collision extension, we need to create a list of particles per cell.
Another motivation for this design is that a particle in PIConGPU is [freely configurable by the user](https://github.com/ComputationalRadiationPhysics/picongpu/blob/da07060c04b86949a3e3f74017445f29de777f99/include/picongpu/param/speciesDefinition.param#L50) this means a particle can become large, therefore copying all attributes of a particle each time the particle is leaving a cell will be very expensive.
Due to our supercell frame list design, there is no need to sort particles at each time step. Sorting will be expensive too.


>> How are you able to keep the cost of the supercell communication and (stream) compaction manageable? (For example, I think if you were to do a prefix scan for the stream compaction, a single cell could easily require a list larger than the L1 cache.)

We do not perform prfix scans. The reason is that this will always require additional memory on the device. Due to the linked frame list design per supercell we can perform the above described algorithms in place without additional on-device memory.

**Comment by matthewa150** [comment]
Thank you so much for the in-depth explanation and links to the kernels themselves! It's incredibly helpful.
> Additionally, we to not need to maintain a list of particles per cell, this is not required for the base particle in cell loop. For the binary collision extension, we need to create a list of particles per cell.

This is not something I considered, but makes sense as a cost of the supercell system.

> PMacc/PIConGPU defines the valid frame list that all frames from the beginning of the frame list must be fully filled with particles except the last frame. The last frame must be contiguous filled from the first slot but at the end it is allowed to have free slots in the last frame.

This answers another question (Do you remove the gaps every timestep or every N timesteps?)

Once again, I really appreciate the thorough response!

**Comment by matthewa150** [comment]
I'm sorry to re-open this issue, but I realized I had one more question @psychocoderHPC 
> KernelShiftParticles will be executed for each supercell but with a double checkerboard striding pattern so that we can reuse the last frame of neighboring supercells without a complicated locking pattern.

Is the double checkerboard pattern similar to Figure 3.9 (Section 3.3.5) in the [2019 thesis](https://zenodo.org/records/3266820#.Ysfp14TP02w) (Given, the paper is referring to particle current scattering)? You would still need to control where particles are being written to in the last frame of a supercell, or am I mistaken?

Thanks!

**Comment by psychocoderHPC** [comment]
> This answers another question (Do you remove the gaps every timestep or every N timesteps?)

The gaps will be removed each timestep. In case an algorithm is spawning or destroying particles e.g. the ionization kernel or the upcoming atomic physics algorithm the gaps must be filled after each manipulation of the frame list where gaps can be created.

**Comment by psychocoderHPC** [comment]
> I'm sorry to re-open this issue, but I realized I had one more question @psychocoderHPC
> 
> > KernelShiftParticles will be executed for each supercell but with a double checkerboard striding pattern so that we can reuse the last frame of neighboring supercells without a complicated locking pattern.
> 
> Is the double checkerboard pattern similar to Figure 3.9 (Section 3.3.5) in the [2019 thesis](https://zenodo.org/records/3266820#.Ysfp14TP02w) (Given, the paper is referring to particle current scattering)? You would still need to control where particles are being written to in the last frame of a supercell, or am I mistaken?
> 
> Thanks!

Figure 3.9 shows our linked frame list. So it is not related to the double checker board. If you think about supercells are fields on a chess board, so we have stride one. In a double checkerboard, you will have three colors on the board so a stride of two. In a normal checkerboard domain decomposition algorithm, you perform first the calculation for the dark field/supercells, and in a second kernel the calculations for the white fields/supercells.
Particles from the dark field will always move to the white field if they leave the supercell.

> Given, the paper is referring to particle current scattering)?

The current scattering is related to the checker board. In one of the possible execution strategies, we have the possibility to perform the current scattering of particles in a checkerboard domain decomposition. During the current scattering particles write their current contribution to all neighbor cells depending on the particle shape. This contribution is stored in shared memory on the device which has memory for all cells in the supercell and guarding/helo cells and after all particles scatter their current into the shared memory the cached data can be written back to the global memory without using atomic add.
Another execution strategy is that we run the current deposition in all supercell in parallel but in this case we need to write the data from the shared memory back to global memory by using atomic add because we have overlapping domains due to the guards/helos around the cached supercell data.

**Comment by matthewa150** [comment]
That really helps to clear things about. Once again I appreciate your time to explain some of these things to me.

I'll be closing the issue for real this time. Thanks!
