### ISSUE TITLE
Negative focus for Gaussian and Dispersive pulse does not work

### ISSUE THREAD

**Issue by finnolec** [ComputationalRadiationPhysics/picongpu#4884]
When using a Gaussian laser and putting the focus outside of the simulation box behind the propagation direction, one would expect an evenly diverging beam inside the simulation. I have tested this for a Gaussian pulse propagating in positive z direction and a negative focus. Here are my param files: [params.zip](https://github.com/ComputationalRadiationPhysics/picongpu/files/15127021/params.zip). This is called with 2x2x2 v100s on a 512x512x4096 grid with 10k timesteps. In the simulation we then see a focusing beam as if the focus was positive. You can see that here:
 
![defocus](https://github.com/ComputationalRadiationPhysics/picongpu/assets/45068748/53d6d85a-a169-4996-9403-45ee7ae6eeb8)

@steindev @pordyna

**Comment by psychocoderHPC** [comment]
IMO the problem is

https://github.com/ComputationalRadiationPhysics/picongpu/blob/05822d5e01d175564e6316203adafcbbc36a6f59/include/picongpu/fields/incidentField/profiles/GaussianPulse.hpp#L229-L231

and it must be changed to

```C++
auto const focusRelativeToOrigin = this->focus - this->origin;
float_X const focusPos = focusRelativeToOrigin.sumOfComponents() - pos[0];
```
`focusRelativeToOrigin` is a float3 with axis in PIConGPUs coordinate system. Only the transversal component is non zero so for YMIN and YMAX of incident field it is Y and for XMIN, XMAX it is X, therefore we can sum over `focusRelativeToOrigin` to get the distance from the plane to the focus.

**Comment by psychocoderHPC** [comment]
The same issue exists in `DispersivePulse`

**Comment by psychocoderHPC** [comment]
important: The **DispersivePulse** is affected too!

**Comment by psychocoderHPC** [comment]
I am not 100% sure but IMO both lasers are also broken if the laser pulse is not moving on axis.

@steindev This issue should get high priority!

**Comment by psychocoderHPC** [comment]
> I am not 100% sure but IMO both lasers are also broken if the laser pulse is not moving on axis.
> 
> @steindev This issue should get high priority!

@PrometheusPi and I reviewed the old implementation. The laser pulse was correct even if the pulse traveled of axis.
The only issue is that negative focus is not supported.
