### ISSUE TITLE
Time-accumulated Poynting flux through boundaries

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#4972]
Calculating the energy loss of the laser field using the EnergyField plugin is not straightforward as this plugin sums all kinds of fields, including the space charge fields. It is hard to diagnose the incoming and outgoing fields, especially if one needs time integration. 

Is it possible to request a feature that calculates the time-accumulated Poynting flux through the boundaries? 
Similar features are already available in Smilei ([PoyXmin](https://smileipic.github.io/Smilei/Use/namelist.html#:~:text=during%20the%20timestep-,PoyXmin,-Time%2Daccumulated%20Poynting)) and Epoch ([Absorption/Abs_frac](https://epochpic.github.io/documentation/input_deck/input_deck_output_block.html#:~:text=%E2%80%9C-,Absorption/Abs_frac,-%E2%80%9D%20%2D%20The%20fraction%20of)), however, the implementation in PIConGPU appear to be much complicated for me.

This is useful for understanding the laser reflection/absorption in various types of laser-matter interactions. Thanks.

**Comment by BrianMarre** [comment]
You can get the same by using [probe particles](https://picongpu.readthedocs.io/en/latest/usage/workflows/probeParticles.html) to write out E- and B-field on the border of your simulation every time step and accumulate them in post processing.

While I agree that having a built in online evaluation would be better, this is currently not a priority for us right now, since implementating it will get much easier when the binning plugin by @ikbuibui can handle field data.
