### ISSUE TITLE
IncidentField Examples

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#5000]
Is there a missing factor in `incidentField.param` IncidentField Examples at 

>   static constexpr float_64 UNITCONV_A0_to_Amplitude_SI = -1.0 / WAVE_LENGTH_SI * SI::ELECTRON_MASS_SI * SI::SPEED_OF_LIGHT_SI * SI::SPEED_OF_LIGHT_SI / SI::ELECTRON_CHARGE_SI;

where there should be a factor of 2 pi?

**Comment by psychocoderHPC** [comment]
ping @PrometheusPi

**Comment by PrometheusPi** [comment]
@psychocoderHPC Thanks for the ping and sorry for not reacting earlier - I will react asap today.

**Comment by PrometheusPi** [comment]
Yes, @StevE-Ong you are right: instead of `-1.0` it should read `-2.0 * PI`, as e.g. in the [incident field of LWFA example](https://github.com/ComputationalRadiationPhysics/picongpu/blob/56488f7cfcd34809bdad41febfe5923b7779f4f4/share/picongpu/examples/LaserWakefield/include/picongpu/param/incidentField.param#L101). The only case where I found this wrong value is in `share/picongpu/examples/IncidentField/include/picongpu/param/incidentField.param`. 
Is this the error you are refencing to?

**Comment by StevE-Ong** [comment]
Thanks @PrometheusPi. Yes. Only in this example.
I adopted this example for my problem and found the interaction with particles is weaker than it should be.

**Comment by BrianMarre** [comment]
@PrometheusPi @StevE-Ong is the original question answered/resolved?

**Comment by StevE-Ong** [comment]
Yes, thanks.

**Comment by BrianMarre** [comment]
Then please remember to close the issue. Thanks!
