### ISSUE TITLE
SIMDIM not set error

### ISSUE THREAD

**Issue by PrometheusPi** [ComputationalRadiationPhysics/picongpu#5062]
In `dimsension.param` one has to use the pre-compiler definition `#define SIMDIM DIM2` since `SIMDIM` is also used outside the scope of `dimension.param` (in contrast to other pre-compiler setups). 
In case of setting the definition directly in C++ and not via pre-compiler:
 - CFL is assumed to be 1D (which we can not do)
 - and various code blocks will be used depending on their local 2D or 3D decision logic. 
 
 This 2-language-problem needs to be fixed. 

@psychocoderHPC will take care of this since he is currently in the process of refactoring this code anyway.

**Comment by psychocoderHPC** [comment]
The CFL problem will be fixed with https://github.com/ComputationalRadiationPhysics/picongpu/pull/5066 
In this PR the CFL dependent cell size will be derived from the variable `simDim` and not from the define `SIMDIM`.

https://github.com/ComputationalRadiationPhysics/picongpu/blob/64fa0de9ba6dd4647517bdf9bdb20df4f782721e/include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/ArbitraryOrderFDTD.hpp#L65-L67

For include guards we still need the define at some places because not all solver are able to be used in 2d and 3d.
