### ISSUE TITLE
Does PIConGPU run in 1-D?

### ISSUE THREAD

**Issue by StevE-Ong** [ComputationalRadiationPhysics/picongpu#5243]
In the file `include/pmacc/dimensions/Definition.hpp`, there are 

```
//! Defines number of dimensions (1-3)
#define DIM1 1u
#define DIM2 2u
#define DIM3 3u
```
When compiling the example, i.e. KelvinHelmholtz, it fails with the error as attached.
[stderr.txt](https://github.com/user-attachments/files/18197417/stderr.txt)

I was thinking to start an example with higher resolution and larger particle-per-cell setup before going to higher dimensions. 
Does PIConGPU support 1-D simulation?

**Comment by BrianMarre** [comment]
No, currently PIConGPU does not support 1D simulations, since compiling a 1D simulation may take longer than running it.

If you really need a 1D simulation you could build a 2D simulation with the minimal y-dimension and a periodic boundaries in y-direction.

minimal size per direction is 3 super cells, with the minimum size of a super cell dependent on particle shape used.

**Comment by StevE-Ong** [comment]
Thank you for your answer.
