### ISSUE TITLE
Laser Antenna: oblique incidence

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/picongpu#619]
Question of @dengshuan from [here](https://github.com/ComputationalRadiationPhysics/picongpu/issues/616#issuecomment-68998384):

> It seems that PIConGPU can't deal with oblique incidence of laser or maybe I just don't understand PIConGPU well enough. And if not, can you give me some guidance on implementing this.

**Comment by ax3l** [comment]
if you want to shoot a laser under an angle > 0 on a target you got two options:

first, simply tilt the target instead of the laser. depending on the field solver, that might even be beneficial to keep the laser propagating on-axis.

alternatively, one could implement laser initialization via an antenna. [background-fields](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f0051b7f1c33a716fcee8cf91657f78b96e0bffd/src/picongpu/include/simulation_defines/param/fieldBackground.param) can be used for that (via currents).

**Comment by WenyinWei** [comment]
Hello @ax3l , I think the oblique incidence is a necessity for the multiple incident laser array setting, which involves various interfering phenomena. Is it possible to encapsulate the laser input file one more layer? For example, use a vector to include every laser info.

**Comment by sbastrakov** [comment]
Hello @WenyinWei . I am out of the context of this issue. Just to clarify, do you want to have a new type of laser which would act like a number of existing lasers combined?

**Comment by ax3l** [comment]
I think one should (re-)implement lasers in PIConGPU via an antenna for exactly that purpose.

**Comment by ax3l** [comment]
Well, let's open a fresh issue, because that one is from 2015.

**Comment by WenyinWei** [comment]
Hello @sbastrakov , thx for your prompt reply. The combination is exactly what I want indeed as long as I can adjust the oblique incident angle. The issue is really old and we can tirn to the new issue to discuss.

**Comment by PrometheusPi** [comment]
@WenyinWei Just to clarify your issue before going to the full-fledged antenna concept (#3159).

1.) You require an angle between your plasma target and your laser other than 90° - is this correct? 
2.) Do you need multiple laser pulses in your setup?
3.) Do these multiple laser pulses have different propagation directions, or are they just delayed (train of pulses)?

**Comment by WenyinWei** [comment]
Hello @PrometheusPi , here is my request.
1) Yes, not only 90 degree. 
2) Yes, multiple lasers. Each with an incident angle. Because the lasers cross glass to reach vacuum, they have maxiun intensity that the glass can undertake.
3) In fact, I want them to interfere with each other on a specified sphere range. Of course that needs different propagation directions. A delay setup is also needed to make the laser pulses work on the specified range at specified time, but this has been achieved.

**Comment by PrometheusPi** [comment]
@WenyinWei The only way to currently implement such a setup would eb to use background field inialization. For that you need to define the [electric](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d340812641320d3a61e343a521287fd0720ba55b/include/picongpu/param/fieldBackground.param#L30-L61) and [magnetic](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d340812641320d3a61e343a521287fd0720ba55b/include/picongpu/param/fieldBackground.param#L63-L94) field for each position and time in [`fieldBackgroud.param`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d340812641320d3a61e343a521287fd0720ba55b/include/picongpu/param/fieldBackground.param). In order to let these fields acct on the macro-particles in the PIC code (via the pusher) you need to switch the [`InfluenceParticlePusher` bool](https://github.com/ComputationalRadiationPhysics/picongpu/blob/d340812641320d3a61e343a521287fd0720ba55b/include/picongpu/param/fieldBackground.param#L34) to true (for both electric **and** magnetic fields). 

An alternative would be the antenna approach  #3159 which is however not yet implemented.

**Comment by PrometheusPi** [comment]
@WenyinWei: @sbastrakov and I had a brief *offline* discussion: If your (different) propagation direction (of the various laser pulses) are relatively close together, then adjusting the current side initialization might be the fasted way to get to what you want to simulated.
