### ISSUE TITLE
Enable const float_X as flag type

### ISSUE THREAD

**Issue by n01r** [ComputationalRadiationPhysics/picongpu#650]
In order to include effective potential models for ionization it is necessary to give the soon-to-come flags `protonNumber` and `neutronNumber` a **float type**.

**Comment by psychocoderHPC** [comment]
In PMacc and PIConGPU all particle/species flags must be classes. The reason is the C++ restriction that it is not allowed to use `float` in templates.
Therefor it is not possible to wrap a float value in  a class like it is possible with integral values (e.g. `boost::mpl::integral_c<uint32_t,42>`)

If no compile time calculations are needed it is possible to wrap a `float` with the following workaround:
```
alias(protonNumber);
struct IonProtons
{
  static const float_X value = 2.0;
};

typedef bmpl::vector<protonNumber<IonProtons>, ... > IonFlagList;
```

**Comment by n01r** [comment]
As for **why** it can be non-integer and should therefore be float:

http://www.webelements.com/periodicity/eff_nuc_charge_clementi/

**Comment by ax3l** [comment]
thanks for looking up a reference! :+1:

**Comment by n01r** [comment]
I think with the introduction in #687 we can close this issue.
