### ISSUE TITLE
defineAdiosVar() use wrong precision

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/picongpu#663]
The function [defineAdiosVar()](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/plugins/adios/ADIOSWriter.def#L130) use `Dataspace<...>` to define the global number of particles in the simulation.
`DataSpace<...>` is `int` and its biggest value is `2^31` ~ `2*10^9`.

In simulation with more than `2*10^9` particles we get an value overflow.

**Comment by psychocoderHPC** [comment]
**Solution:**
use `PMacc::math::Size_t<...>` instead of `DataSpace<...>`

**Comment by psychocoderHPC** [comment]
We downcast 64Bit to 32Bit [here](https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/plugins/adios/writer/ParticleAttributeSize.hpp#L85)

**Comment by ax3l** [comment]
isn't `size_t` still 32bit on a 32bit system (such as jetson tk1)?

**Comment by ax3l** [comment]
-> I am going to refactor all `libPMacc` vectors: `UInt` -> `UInt32`, add `UInt64`, ...

**Comment by ax3l** [comment]
>  isn't size_t still 32bit on a 32bit system (such as a jetson tk1 cluster)?

IMHO one should do the following:
`size_t` is only a good idea for *local* counts/data sizes that are *guaranteed* to stay below 4G elements.

For all other cases, `size_t` is a very bad idea since we calculate in parallel. Imagine you run on a 32bit host system such as a jetson cluster (with say 200 nodes). Your *local particle number* might be below 4e9 elements, but if you calculate an offset on, e.g., *node 123* this might not be true any more.

For that reason, the evil pull request #666 :smiling_imp: now uses `uint64_t` for such counters in adios.

**Comment by ax3l** [comment]
fixed with #666 :smiling_imp: :open_mouth:
