### ISSUE TITLE
Casting of CONST_VECTOR does not work

### ISSUE THREAD

**Issue by BeyondEspresso** [ComputationalRadiationPhysics/picongpu#736]
Neither direct precisionCast on picongpu::cellSize nor casting on floatD_ works. This leads to workaround code such as
```C++
floatD_X cellDim;
for (uint32_t i = 0; i<simDim;++i) cellDim[i]=picongpu::cellSize[i];
```
Instead of the mess above a short
```C++
const floatD_X cellDim = picongpu::cellSize;
```
would be ideal.

**Comment by psychocoderHPC** [comment]
Can you provide me with the compile time error message?

**Comment by psychocoderHPC** [comment]
`const floatD_X cellDim = picongpu::cellSize;`
Is not allowed because we only support explicit casts (type transformation). `typeof(cellSize)!=typeof(floatD_X)` 

use this (explicit cast):
`const floatD_X cellDim(picongpu::cellSize);`
or remove the `const`:
`floatD_X cellDim;
 cellDim= picongpu::cellSize;`

**Comment by psychocoderHPC** [comment]
The BUG is that this:
```C++
floatD_X cellDim(precisionCast<float_X>(picongpu::cellSize));
```
is not working.
I will fix it soon.

**Comment by ax3l** [comment]
@BeyondEspresso should be fixed in `dev` now :)

thanks @psychocoderHPC :rocket:
