### ISSUE TITLE
Does PIConGPU apply to overdense plasmas?

### ISSUE THREAD

**Issue by dengshuan** [ComputationalRadiationPhysics/picongpu#752]
Recently I made some tests: laser interact with overdense (`4x10^28 ~ 4x10^30 m^-3`) plasmas. All of the simulations have a strange behavior: laser suddenly jumps large step. Sorry I don't know how to describe this in English correctly, here are some output images(step 200,220,240) with gas density `4x10^30 m^-3`:

![pngimageelectrons_yx_0 5_000200](https://cloud.githubusercontent.com/assets/3888664/6573931/b03121fe-c75a-11e4-95cd-f3f77fd7bb02.png)
![pngimageelectrons_yx_0 5_000220](https://cloud.githubusercontent.com/assets/3888664/6573929/af98b4f0-c75a-11e4-8ced-cf70d4eb1df8.png)
![pngimageelectrons_yx_0 5_000240](https://cloud.githubusercontent.com/assets/3888664/6573930/af9d8da4-c75a-11e4-90ab-e95f1a9f5c8d.png)

So is this a bug or does PIConGPU work for overdense plasmas?
And [this](http://1drv.ms/1MpAJGF) is one of my simulation parameters

**Comment by PrometheusPi** [comment]
Of course, in principle yes but it depends on the setup.

As example some pictures of High Harmonics Generation (HHG) with PIConGPU:
![hhg_example](https://cloud.githubusercontent.com/assets/5121158/6576620/aba0c350-c738-11e4-9de7-24ffaafb3740.png)


Of course, whether PIConGPU produces correct results depends on what physics happends in the overdense target. So, e.g. whether **collisions** between particles can be neglected or not. Whether **ionization dynamics** is relevant, etc. 



The pictures you posted look like laser foil irradiation. Are you simulation for example Target Normal Sheat Acceleration (TNSA), RPA, BOA, ...?

I have currently no time to go through your parameter set, but might it be that you do not resolve the plasma wavelength?

**Comment by PrometheusPi** [comment]
Could you post the first lines of your output file (usually `stdout`) till `0 % =        0 | time elapsed:`?

**Comment by bussmann** [comment]
Hi,

PIConGPU can simulate overdense plasmas. But you have to correctly choose the input parameters.

Currently, most of us are on a conference, so we can have a look at your input patameters when we're back next week.

btw: Which version of the code did you use?

Best, Michael

**Comment by dengshuan** [comment]
@PrometheusPi Here is my stdout, and I'm studying energy absorption in laser interaction with solids.
```
Running program...

 ========================   JOB MAP   ========================

 Data for node: hpc-Vostro-3900	Num procs: 1
 	Process OMPI jobid: [47775,1] Process rank: 0

 =============================================================
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | Sliding Window is OFF
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | max weighting 2.78203e+09
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | Courant c*dt <= 1.74147 ? 1
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | omega_pe * dt <= 0.1 ? 9.02633
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | y-cells per wavelength: 18.0587
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | macro particles per gpu: 33554432
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | typical macro particle weighting: 2.78203e+09
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_SPEED 2.99792e+08
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_TIME 8e-17
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_LENGTH 2.39834e-08
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_MASS 2.53425e-21
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_CHARGE 4.45729e-10
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_EFIELD 2.13064e+13
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_BFIELD 71070.4
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | UNIT_ENERGY 0.000227767
[1,0]<stdout>:initialization time:  2min 29sec 963msec = 149 sec
```

@bussmann I pulled the latest dev branch two days ago, and the last commit is `6e3925f348496c5ac7eeed9654c8617a47fd384b`

**Comment by PrometheusPi** [comment]
@dengshuan 
Thank you for your fast reply. The first thing I notice is, that you do not resolve the plasma dynamics of your overdense target. 
```
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | omega_pe * dt <= 0.1 ? 9.02633
```
You should decreade your cell width and time step so that you can resolve the plasma wavelength at least 5 times. 
This will decrease the macro-particle weighting as well
```
[1,0]<stdout>:PIConGPUVerbose PHYSICS(1) | typical macro particle weighting: 2.78203e+09
```
Based on your pictures, I additionally guess that you might run out of memory.
Could you [activate the verbose level](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Configuration-flags) `PIC_VERBOSE` for your memory by setting it to `61`? And could you campare this to the number of macro particles in your simulation (e.g. via [CountParticles Plugin](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/Plugin%3A-CountParticles))?

**Comment by dengshuan** [comment]
@PrometheusPi Oh, yeah you're right. I decreased the cell width and time step and the result seemed reasonable. 

However the output hdf5 files are really huge, about 2.1G per file. Not sure whether it is for every users, but at least for me -:). And actually we don't have to dump all of the data. Now we are also using *OSIRIS*, and it provides an option which we can set a dump fraction. For example by setting dump fraction to 0.1, output file will be reduced to 210M without losing any important details.

I'll try to implement this and maybe I should open a new issue. What do you think?

**Comment by ax3l** [comment]
@dengshuan unfortunately the HDF5 library does [not support compression during parallel output](http://www.hdfgroup.org/hdf5-quest.html#p5comp). That is not a limitation of the file format but a limitation of their reference implementation.

Nevertheless, you can compress the created files post-mortem. Since post-processing is mainly I/O limited and the decompression is not a huge overhead, I really recommend that (saves depending on the setup a factor of 3 to 5).
The following script might help you:
```bash
#!/bin/sh
#
if [ -z "$1" ]
then
  echo "$0 /path/to/simOutput"
  exit 1
fi

find $1 -name "*.h5" | xargs -n1 -P8 -I{} \
    sh -c 'echo "compress $1 ..." && \
    h5repack -i $1 -o $1.gz -f GZIP=1 && mv $1.gz $1' _ {}
```

Independent to that, our support for the ADIOS file format and API [is currently being refactored](https://github.com/ComputationalRadiationPhysics/picongpu/pull/679). ADIOS is in many ways a better choice: it allows on-the-fly transformations such as compression, it has a higher performance on clusters with more than ~1'000 nodes+, it allows in-situ statistics gathering, ... ([homepage](https://www.olcf.ornl.gov/center-projects/adios/)).

Due to conferences it will still take one more month before that update will arrive in the stable `master` branch (which I recommend you to use anyway) :)

**Comment by ax3l** [comment]
Just to make sure to state the obvious: also decreasing the `--hdf5.period <N>` will reduce the total size of the output.

**Comment by ax3l** [comment]
One more thing regarding your image: are you using a Tesla or a Gforce GPU?

As a rule of thumb, try to stay below **~15e6 macro particles per GB** of the GPU RAM, assuming that the main memory is occupied by particles and the GPU is not calculating only vacuum field data.

This is necessary because in the current `dev`, which is always our **experimental branch**, we just changed the memory controller to [mallocMC](https://github.com/ComputationalRadiationPhysics/mallocMC) and can currently not detect if you are overflowing the memory (and your results will simply look weird). This feature will be added again for the next stable `master` release.

**Comment by dengshuan** [comment]
@ax3l yes, we're using Tesla K20 GPU. And I just find how to control output data of hdf5 file in *fileOutput.param* too, it seems to be what I need. Again thank you for your advice

**Comment by ax3l** [comment]
@dengshuan great to hear that, thank you.

In case you feel your initial questions answered feel free to close this issue so we stay on topic. For any further questions, do not hesitate to open fresh issues and keep us posted on your results :sparkles:
