### ISSUE TITLE
A question on tpp v/s hpp

### ISSUE THREAD

**Issue by anshumang** [ComputationalRadiationPhysics/picongpu#791]
@ax3l - This is not an issue per se but a question. Under plugins/radiation, the .hpp file has the method definitions but under plugins/PhaseSpace, the .tpp file has the definitions. When are the definitions moved to a .tpp file?

**Comment by ax3l** [comment]
@anshumang opening an issue for that question or writing a mail to the [PIConGPU-User list](https://cg.hzdr.de/Lists/picongpu-users/List.html) is absolutely the right place, don't worry. :+1: 

Regarding your question: can you please [link](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f0051b7f1c33a716fcee8cf91657f78b96e0bffd/src/picongpu/include/plugins/PhaseSpace/PhaseSpace.tpp#L49) what you mean by "definitions"?

The general format we use is:

- `.def` files: forward declarations (avoiding include loops, just necessary for very general aspects of the code)
- `.hpp` files: usually the header files that implement most of the code, since we use techniques such as template meta programming that prevent clean `.cpp` files
- `.tpp` files: becomes deprecated in recent advances of your coding style, but is still widely used. The initial idea of them was to reduce the amount of code in the `.hpp` files and to create a "fake-look cpp" style include with the actual `implementation` of functions/classes/methods.

Maybe @psychocoderHPC has also some input on that, since he is in favor of deprecating the `.tpp` files at all.

**Comment by anshumang** [comment]
Under plugins/radiation, the .hpp file has the method definitions but under plugins/PhaseSpace, the .tpp file has the definitions/implementations.
So I meant declaration for the first and definition/implementation for the second.

That was my question actually - when do you move some of the definitions by creating a .tpp file? I guess from your answer that when the .hpp file becomes too large you create a .tpp file and move the implementations.

**Comment by BenjaminW3** [comment]
I do not think we can deprecate the `.hpp` and `.tpp` division completely.

As long as you know there will be **no cyclic dependency, no division is required** and you can just write everything in the header.

In case of cyclic dependencies (like in the event system and environment) you can do two things:
- Write everything/something header-only (current state) and provide a general header that includes everything (`.hpp`s and `.tpp`s) in a(/the only) possible order because there are implicit dependencies between the headers. 

 The inclusion of the event system headers themselves will most of the time lead to a wrong inclusion order and you will have to include the whole event system at once although you only needed a small part of it.

 -> longer compile times

- Divide the code correctly into `.hpp` for the class and method declarations using as few as possible includes and forward declare everything else and `.tpp` for the implementations (the same way it should be done for every standard `.hpp` `.cpp` combination).

 At the end of each `.hpp` file include the corresponding `.tpp` file.

 The `.tpp` files themselves now include all the headers they need (the same way it is done in a cpp file) and define the implementations.

 This leads to a clean header structure. Each header can be included independently and will automatically include its `.tpp` file, its `.hpp` dependencies and their `.tpp` files in the correct order. Cyclic dependencies are automatically handeled. There is no need to ever include a `.tpp` file manually anywhere else in the code.

**Comment by ax3l** [comment]
@anshumang yes, that's the rule of thumb.

@BenjaminW3 ther second point is actually how we do it currently. for cyclic dependencies and parts of the code (such as `.param` files) that are not allowed to pull in a huge dependency chain. Including the `.tpp` file at the end of the `.hpp` files does still not save you, since you sometimes need forward declarations. For that we use `.def` files (e.g., or a lot of solvers and fields) that avoid several incoherent forward-declarations for the same thing. `.def` files are always included first in the `.hpp` file.

**Comment by psychocoderHPC** [comment]
@BenjaminW3 For `PMacc`  it is possible to use only `.hpp` and `.tpp` files. As @ax3l said in `PIConGPU` we use `.param` and `.unitless` files as user configuration files, therefore it is not possible to include `.tpp` at the end of `.hpp`.
`.unitless` are a workaround because of the missing `C++11` feature `constexpr`.
