### ISSUE TITLE
No rule to make target   question

### ISSUE THREAD

**Issue by clearlylin** [ComputationalRadiationPhysics/picongpu#804]
[ 33%] Built target picongpu
[ 83%] Built target cuda_memtest
make[2]: *** No rule to make target `/usr/lib64/lib64/libboost_program_options-mt-d.so.5', needed by `build_picongpu/build_mpiInfo/mpiInfo'.  Stop.
make[1]: *** [build_picongpu/build_mpiInfo/CMakeFiles/mpiInfo.dir/all] Error 2
make: *** [all] Error 2

hi,everybody.
deploy picongpu,make install, always arise this error.

**Comment by ax3l** [comment]
Hi @clearlylin, welcome to our issue tracker!

can you please provide your version of PIConGPU, your compiler, OS and libraries including versions?

It looks to me as there is something wrong with your boost install, that happens usually when one forces to install the "multi-threaded" libs or takes pre-compiled boost libraries from distributors (as your library path suggests). I recommend *compiling boost yourself*, e.g., like [this](https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/doc/INSTALL.md#mandatory) (scroll down to *boost*). This is always the best choice, also because many boost libraries have a incompatible ABI between compilers (see [dependency graph](https://github.com/ComputationalRadiationPhysics/picongpu/blob/64846d380843ae09a04dcfd5b729cf25f25cfc6b/doc/INSTALL.md#overview)).

Alternatively, you can try to set
```cmake
set(Boost_USE_MULTITHREADED OFF)
```
in [src/picongpu/CMakeLists.txt](https://github.com/ComputationalRadiationPhysics/picongpu/blob/f0051b7f1c33a716fcee8cf91657f78b96e0bffd/src/picongpu/CMakeLists.txt#L238) before running the
```cmake
find_package(Boost ...)
```

call, **but I really recommend to rather fix the environment** (boost install) :)

**Comment by ax3l** [comment]
@clearlylin did re-installing boost solve your problem?

**Comment by clearlylin** [comment]
Yes .
Thank You .

---- Axel Huebl编写 ----

**Comment by ax3l** [comment]
that is fantastic :rocket: 

I will then close the issue as solved.
